// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableFunctionPathControllerUpdateRequest struct {
	PathID           string                                     `pathParam:"style=simple,explode=false,name=pathID"`
	ProjectID        string                                     `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string                                     `queryParam:"style=form,explode=true,name=environmentAlias"`
	Body             components.StableFunctionPathUpdateRequest `request:"mediaType=application/json"`
}

func (s *StableFunctionPathControllerUpdateRequest) GetPathID() string {
	if s == nil {
		return ""
	}
	return s.PathID
}

func (s *StableFunctionPathControllerUpdateRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableFunctionPathControllerUpdateRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableFunctionPathControllerUpdateRequest) GetBody() components.StableFunctionPathUpdateRequest {
	if s == nil {
		return components.StableFunctionPathUpdateRequest{}
	}
	return s.Body
}

type StableFunctionPathControllerUpdateResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	StableUpdateResponse *components.StableUpdateResponse
}

func (s StableFunctionPathControllerUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableFunctionPathControllerUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableFunctionPathControllerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableFunctionPathControllerUpdateResponse) GetStableUpdateResponse() *components.StableUpdateResponse {
	if s == nil {
		return nil
	}
	return s.StableUpdateResponse
}
