// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAnalyticsControllerQueryDailyTokenUsageRequest struct {
	OrganizationID string                                                `pathParam:"style=simple,explode=false,name=organizationID"`
	Body           components.StableAnalyticsQueryDailyTokenUsageRequest `request:"mediaType=application/json"`
}

func (s *StableAnalyticsControllerQueryDailyTokenUsageRequest) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *StableAnalyticsControllerQueryDailyTokenUsageRequest) GetBody() components.StableAnalyticsQueryDailyTokenUsageRequest {
	if s == nil {
		return components.StableAnalyticsQueryDailyTokenUsageRequest{}
	}
	return s.Body
}

type StableAnalyticsControllerQueryDailyTokenUsageResponse struct {
	HTTPMeta                                    components.HTTPMetadata `json:"-"`
	StableAnalyticsQueryDailyTokenUsageResponse *components.StableAnalyticsQueryDailyTokenUsageResponse
}

func (s StableAnalyticsControllerQueryDailyTokenUsageResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAnalyticsControllerQueryDailyTokenUsageResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAnalyticsControllerQueryDailyTokenUsageResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAnalyticsControllerQueryDailyTokenUsageResponse) GetStableAnalyticsQueryDailyTokenUsageResponse() *components.StableAnalyticsQueryDailyTokenUsageResponse {
	if s == nil {
		return nil
	}
	return s.StableAnalyticsQueryDailyTokenUsageResponse
}
