// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationRequest struct {
	OrganizationID string                                                             `pathParam:"style=simple,explode=false,name=organizationID"`
	Body           components.StableAnalyticsQueryHourlyOrganizationTokenUsageRequest `request:"mediaType=application/json"`
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationRequest) GetOrganizationID() string {
	if s == nil {
		return ""
	}
	return s.OrganizationID
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationRequest) GetBody() components.StableAnalyticsQueryHourlyOrganizationTokenUsageRequest {
	if s == nil {
		return components.StableAnalyticsQueryHourlyOrganizationTokenUsageRequest{}
	}
	return s.Body
}

type StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationResponse struct {
	HTTPMeta                                                 components.HTTPMetadata `json:"-"`
	StableAnalyticsQueryOrganizationHourlyTokenUsageResponse *components.StableAnalyticsQueryOrganizationHourlyTokenUsageResponse
}

func (s StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByOrganizationResponse) GetStableAnalyticsQueryOrganizationHourlyTokenUsageResponse() *components.StableAnalyticsQueryOrganizationHourlyTokenUsageResponse {
	if s == nil {
		return nil
	}
	return s.StableAnalyticsQueryOrganizationHourlyTokenUsageResponse
}
