// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 79f77a02d1f3

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAPIToolVariableControllerGetV2Request struct {
	VariableID       string `pathParam:"style=simple,explode=false,name=variableID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
}

func (s *StableAPIToolVariableControllerGetV2Request) GetVariableID() string {
	if s == nil {
		return ""
	}
	return s.VariableID
}

func (s *StableAPIToolVariableControllerGetV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAPIToolVariableControllerGetV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

// #region class-body-stableapitoolvariablecontrollergetv2request
// #endregion class-body-stableapitoolvariablecontrollergetv2request

type StableAPIToolVariableControllerGetV2Response struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	StableAPIToolVariableResponseV2 *components.StableAPIToolVariableResponseV2
}

func (s StableAPIToolVariableControllerGetV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAPIToolVariableControllerGetV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAPIToolVariableControllerGetV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAPIToolVariableControllerGetV2Response) GetStableAPIToolVariableResponseV2() *components.StableAPIToolVariableResponseV2 {
	if s == nil {
		return nil
	}
	return s.StableAPIToolVariableResponseV2
}

// #region class-body-stableapitoolvariablecontrollergetv2response
// #endregion class-body-stableapitoolvariablecontrollergetv2response
