// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6430a4e1a4a4

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// StableToolControllerGetV2Type - The type of the tool to fetch.
type StableToolControllerGetV2Type string

const (
	StableToolControllerGetV2TypeAPI         StableToolControllerGetV2Type = "api"
	StableToolControllerGetV2TypeMcp         StableToolControllerGetV2Type = "mcp"
	StableToolControllerGetV2TypeFunction    StableToolControllerGetV2Type = "function"
	StableToolControllerGetV2TypeIntegration StableToolControllerGetV2Type = "integration"
)

func (e StableToolControllerGetV2Type) ToPointer() *StableToolControllerGetV2Type {
	return &e
}
func (e *StableToolControllerGetV2Type) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "api":
		fallthrough
	case "mcp":
		fallthrough
	case "function":
		fallthrough
	case "integration":
		*e = StableToolControllerGetV2Type(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableToolControllerGetV2Type: %v", v)
	}
}

type StableToolControllerGetV2Request struct {
	ToolID           string `pathParam:"style=simple,explode=false,name=toolID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	// The type of the tool to fetch.
	Type StableToolControllerGetV2Type `queryParam:"style=form,explode=true,name=type"`
}

func (s *StableToolControllerGetV2Request) GetToolID() string {
	if s == nil {
		return ""
	}
	return s.ToolID
}

func (s *StableToolControllerGetV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableToolControllerGetV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableToolControllerGetV2Request) GetType() StableToolControllerGetV2Type {
	if s == nil {
		return StableToolControllerGetV2Type("")
	}
	return s.Type
}

// #region class-body-stabletoolcontrollergetv2request
// #endregion class-body-stabletoolcontrollergetv2request

type StableToolControllerGetV2Response struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	StableToolReadResponse *components.StableToolReadResponse
}

func (s StableToolControllerGetV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableToolControllerGetV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableToolControllerGetV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableToolControllerGetV2Response) GetStableToolReadResponse() *components.StableToolReadResponse {
	if s == nil {
		return nil
	}
	return s.StableToolReadResponse
}

// #region class-body-stabletoolcontrollergetv2response
// #endregion class-body-stabletoolcontrollergetv2response
