// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 859ed415baa9

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableMessageControllerDeleteVariantRequest struct {
	MessageID        string `pathParam:"style=simple,explode=false,name=messageID"`
	VariantID        string `pathParam:"style=simple,explode=false,name=variantID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
}

func (s *StableMessageControllerDeleteVariantRequest) GetMessageID() string {
	if s == nil {
		return ""
	}
	return s.MessageID
}

func (s *StableMessageControllerDeleteVariantRequest) GetVariantID() string {
	if s == nil {
		return ""
	}
	return s.VariantID
}

func (s *StableMessageControllerDeleteVariantRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableMessageControllerDeleteVariantRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

type StableMessageControllerDeleteVariantResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	StableDeleteResponse *components.StableDeleteResponse
}

func (s StableMessageControllerDeleteVariantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableMessageControllerDeleteVariantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableMessageControllerDeleteVariantResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableMessageControllerDeleteVariantResponse) GetStableDeleteResponse() *components.StableDeleteResponse {
	if s == nil {
		return nil
	}
	return s.StableDeleteResponse
}
