// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 42cfee756a57

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAgentControllerPatchInstructionsV2Request struct {
	ProjectID        string                                    `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string                                    `queryParam:"style=form,explode=true,name=environmentAlias"`
	Body             components.StableInstructionsPatchRequest `request:"mediaType=application/json"`
}

func (s *StableAgentControllerPatchInstructionsV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAgentControllerPatchInstructionsV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableAgentControllerPatchInstructionsV2Request) GetBody() components.StableInstructionsPatchRequest {
	if s == nil {
		return components.StableInstructionsPatchRequest{}
	}
	return s.Body
}

// #region class-body-stableagentcontrollerpatchinstructionsv2request
// #endregion class-body-stableagentcontrollerpatchinstructionsv2request

type StableAgentControllerPatchInstructionsV2Response struct {
	HTTPMeta                          components.HTTPMetadata `json:"-"`
	StableInstructionsPatchResponseV2 *components.StableInstructionsPatchResponseV2
}

func (s StableAgentControllerPatchInstructionsV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAgentControllerPatchInstructionsV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAgentControllerPatchInstructionsV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAgentControllerPatchInstructionsV2Response) GetStableInstructionsPatchResponseV2() *components.StableInstructionsPatchResponseV2 {
	if s == nil {
		return nil
	}
	return s.StableInstructionsPatchResponseV2
}

// #region class-body-stableagentcontrollerpatchinstructionsv2response
// #endregion class-body-stableagentcontrollerpatchinstructionsv2response
