// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableEvaluationControllerCreateRequest struct {
	ProjectID string                                   `queryParam:"style=form,explode=true,name=projectID"`
	Body      components.StableEvaluationCreateRequest `request:"mediaType=application/json"`
}

func (s *StableEvaluationControllerCreateRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableEvaluationControllerCreateRequest) GetBody() components.StableEvaluationCreateRequest {
	if s == nil {
		return components.StableEvaluationCreateRequest{}
	}
	return s.Body
}

func (s *StableEvaluationControllerCreateRequest) GetBodyBoolean() *components.StableEvaluationCreateRequestBoolean {
	return s.GetBody().StableEvaluationCreateRequestBoolean
}

func (s *StableEvaluationControllerCreateRequest) GetBodyNumber() *components.StableEvaluationCreateRequestNumber {
	return s.GetBody().StableEvaluationCreateRequestNumber
}

func (s *StableEvaluationControllerCreateRequest) GetBodyString() *components.StableEvaluationCreateRequestString {
	return s.GetBody().StableEvaluationCreateRequestString
}

func (s *StableEvaluationControllerCreateRequest) GetBodyOptionObj() *components.StableEvaluationCreateRequestOption2 {
	return s.GetBody().StableEvaluationCreateRequestOption2
}

type StableEvaluationControllerCreateResponse struct {
	HTTPMeta                 components.HTTPMetadata `json:"-"`
	StableEvaluationResponse *components.StableEvaluationResponse
}

func (s StableEvaluationControllerCreateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationControllerCreateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationControllerCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableEvaluationControllerCreateResponse) GetStableEvaluationResponse() *components.StableEvaluationResponse {
	if s == nil {
		return nil
	}
	return s.StableEvaluationResponse
}
