// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAPIToolControllerUpdateRequest struct {
	ToolID           string                                `pathParam:"style=simple,explode=false,name=toolID"`
	ProjectID        string                                `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string                                `queryParam:"style=form,explode=true,name=environmentAlias"`
	Body             components.StableAPIToolUpdateRequest `request:"mediaType=application/json"`
}

func (s *StableAPIToolControllerUpdateRequest) GetToolID() string {
	if s == nil {
		return ""
	}
	return s.ToolID
}

func (s *StableAPIToolControllerUpdateRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAPIToolControllerUpdateRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableAPIToolControllerUpdateRequest) GetBody() components.StableAPIToolUpdateRequest {
	if s == nil {
		return components.StableAPIToolUpdateRequest{}
	}
	return s.Body
}

type StableAPIToolControllerUpdateResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	StableUpdateResponse *components.StableUpdateResponse
}

func (s StableAPIToolControllerUpdateResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAPIToolControllerUpdateResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAPIToolControllerUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAPIToolControllerUpdateResponse) GetStableUpdateResponse() *components.StableUpdateResponse {
	if s == nil {
		return nil
	}
	return s.StableUpdateResponse
}
