// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAnalyticsControllerQueryCallCountRequest struct {
	ProjectID string                                          `pathParam:"style=simple,explode=false,name=projectID"`
	Body      components.StableAnalyticsQueryCallCountRequest `request:"mediaType=application/json"`
}

func (s *StableAnalyticsControllerQueryCallCountRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAnalyticsControllerQueryCallCountRequest) GetBody() components.StableAnalyticsQueryCallCountRequest {
	if s == nil {
		return components.StableAnalyticsQueryCallCountRequest{}
	}
	return s.Body
}

type StableAnalyticsControllerQueryCallCountResponse struct {
	HTTPMeta                              components.HTTPMetadata `json:"-"`
	StableAnalyticsQueryCallCountResponse *components.StableAnalyticsQueryCallCountResponse
}

func (s StableAnalyticsControllerQueryCallCountResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAnalyticsControllerQueryCallCountResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAnalyticsControllerQueryCallCountResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAnalyticsControllerQueryCallCountResponse) GetStableAnalyticsQueryCallCountResponse() *components.StableAnalyticsQueryCallCountResponse {
	if s == nil {
		return nil
	}
	return s.StableAnalyticsQueryCallCountResponse
}
