// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 164b2564df33

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAnalyticsControllerQueryInteractionCountByWorkspaceRequest struct {
	WorkspaceID string                                                          `pathParam:"style=simple,explode=false,name=workspaceID"`
	Body        components.StableAnalyticsQueryWorkspaceInteractionCountRequest `request:"mediaType=application/json"`
}

func (s *StableAnalyticsControllerQueryInteractionCountByWorkspaceRequest) GetWorkspaceID() string {
	if s == nil {
		return ""
	}
	return s.WorkspaceID
}

func (s *StableAnalyticsControllerQueryInteractionCountByWorkspaceRequest) GetBody() components.StableAnalyticsQueryWorkspaceInteractionCountRequest {
	if s == nil {
		return components.StableAnalyticsQueryWorkspaceInteractionCountRequest{}
	}
	return s.Body
}

type StableAnalyticsControllerQueryInteractionCountByWorkspaceResponse struct {
	HTTPMeta                                              components.HTTPMetadata `json:"-"`
	StableAnalyticsQueryWorkspaceInteractionCountResponse *components.StableAnalyticsQueryWorkspaceInteractionCountResponse
}

func (s StableAnalyticsControllerQueryInteractionCountByWorkspaceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAnalyticsControllerQueryInteractionCountByWorkspaceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAnalyticsControllerQueryInteractionCountByWorkspaceResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAnalyticsControllerQueryInteractionCountByWorkspaceResponse) GetStableAnalyticsQueryWorkspaceInteractionCountResponse() *components.StableAnalyticsQueryWorkspaceInteractionCountResponse {
	if s == nil {
		return nil
	}
	return s.StableAnalyticsQueryWorkspaceInteractionCountResponse
}
