// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAnalyticsControllerQueryHourlyTokenUsageByProjectRequest struct {
	ProjectID string                                                        `pathParam:"style=simple,explode=false,name=projectID"`
	Body      components.StableAnalyticsQueryProjectHourlyTokenUsageRequest `request:"mediaType=application/json"`
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByProjectRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByProjectRequest) GetBody() components.StableAnalyticsQueryProjectHourlyTokenUsageRequest {
	if s == nil {
		return components.StableAnalyticsQueryProjectHourlyTokenUsageRequest{}
	}
	return s.Body
}

type StableAnalyticsControllerQueryHourlyTokenUsageByProjectResponse struct {
	HTTPMeta                                            components.HTTPMetadata `json:"-"`
	StableAnalyticsQueryProjectHourlyTokenUsageResponse *components.StableAnalyticsQueryProjectHourlyTokenUsageResponse
}

func (s StableAnalyticsControllerQueryHourlyTokenUsageByProjectResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByProjectResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAnalyticsControllerQueryHourlyTokenUsageByProjectResponse) GetStableAnalyticsQueryProjectHourlyTokenUsageResponse() *components.StableAnalyticsQueryProjectHourlyTokenUsageResponse {
	if s == nil {
		return nil
	}
	return s.StableAnalyticsQueryProjectHourlyTokenUsageResponse
}
