// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6dfadf165319

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAgentControllerReadPromptV2Request struct {
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	Offset           *int64 `default:"1" queryParam:"style=form,explode=true,name=offset"`
	Limit            *int64 `default:"400" queryParam:"style=form,explode=true,name=limit"`
}

func (s StableAgentControllerReadPromptV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAgentControllerReadPromptV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAgentControllerReadPromptV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAgentControllerReadPromptV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableAgentControllerReadPromptV2Request) GetOffset() *int64 {
	if s == nil {
		return nil
	}
	return s.Offset
}

func (s *StableAgentControllerReadPromptV2Request) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

// #region class-body-stableagentcontrollerreadpromptv2request
// #endregion class-body-stableagentcontrollerreadpromptv2request

type StableAgentControllerReadPromptV2Response struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	StableInstructionsReadResponse *components.StableInstructionsReadResponse
}

func (s StableAgentControllerReadPromptV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAgentControllerReadPromptV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAgentControllerReadPromptV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAgentControllerReadPromptV2Response) GetStableInstructionsReadResponse() *components.StableInstructionsReadResponse {
	if s == nil {
		return nil
	}
	return s.StableInstructionsReadResponse
}

// #region class-body-stableagentcontrollerreadpromptv2response
// #endregion class-body-stableagentcontrollerreadpromptv2response
