// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7c129f249e5f

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableIntegrationControllerExecuteRequest struct {
	Integration      string                                     `pathParam:"style=simple,explode=false,name=integration"`
	ProjectID        string                                     `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string                                     `queryParam:"style=form,explode=true,name=environmentAlias"`
	Body             components.StableIntegrationExecuteRequest `request:"mediaType=application/json"`
}

func (s *StableIntegrationControllerExecuteRequest) GetIntegration() string {
	if s == nil {
		return ""
	}
	return s.Integration
}

func (s *StableIntegrationControllerExecuteRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableIntegrationControllerExecuteRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableIntegrationControllerExecuteRequest) GetBody() components.StableIntegrationExecuteRequest {
	if s == nil {
		return components.StableIntegrationExecuteRequest{}
	}
	return s.Body
}

type StableIntegrationControllerExecuteResponse struct {
	HTTPMeta                         components.HTTPMetadata `json:"-"`
	StableIntegrationExecuteResponse *components.StableIntegrationExecuteResponse
}

func (s StableIntegrationControllerExecuteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationControllerExecuteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationControllerExecuteResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableIntegrationControllerExecuteResponse) GetStableIntegrationExecuteResponse() *components.StableIntegrationExecuteResponse {
	if s == nil {
		return nil
	}
	return s.StableIntegrationExecuteResponse
}
