// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3c4f8ecc1a28

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableTranscriptPropertyControllerDeleteRequest struct {
	PropertyID string `pathParam:"style=simple,explode=false,name=propertyID"`
	ProjectID  string `queryParam:"style=form,explode=true,name=projectID"`
}

func (s *StableTranscriptPropertyControllerDeleteRequest) GetPropertyID() string {
	if s == nil {
		return ""
	}
	return s.PropertyID
}

func (s *StableTranscriptPropertyControllerDeleteRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

type StableTranscriptPropertyControllerDeleteResponse struct {
	HTTPMeta             components.HTTPMetadata `json:"-"`
	StableDeleteResponse *components.StableDeleteResponse
}

func (s StableTranscriptPropertyControllerDeleteResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTranscriptPropertyControllerDeleteResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTranscriptPropertyControllerDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableTranscriptPropertyControllerDeleteResponse) GetStableDeleteResponse() *components.StableDeleteResponse {
	if s == nil {
		return nil
	}
	return s.StableDeleteResponse
}
