// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1769b4c1b4ec

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAgentControllerPatchPromptRequest struct {
	ProjectID        string                                    `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string                                    `queryParam:"style=form,explode=true,name=environmentAlias"`
	Body             components.StableInstructionsPatchRequest `request:"mediaType=application/json"`
}

func (s *StableAgentControllerPatchPromptRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAgentControllerPatchPromptRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableAgentControllerPatchPromptRequest) GetBody() components.StableInstructionsPatchRequest {
	if s == nil {
		return components.StableInstructionsPatchRequest{}
	}
	return s.Body
}

type StableAgentControllerPatchPromptResponse struct {
	HTTPMeta                        components.HTTPMetadata `json:"-"`
	StableInstructionsPatchResponse *components.StableInstructionsPatchResponse
}

func (s StableAgentControllerPatchPromptResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAgentControllerPatchPromptResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAgentControllerPatchPromptResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAgentControllerPatchPromptResponse) GetStableInstructionsPatchResponse() *components.StableInstructionsPatchResponse {
	if s == nil {
		return nil
	}
	return s.StableInstructionsPatchResponse
}
