// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dff8c8975a11

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableDocumentControllerCreateURLMaxChunkSizeType string

const (
	StableDocumentControllerCreateURLMaxChunkSizeTypeStr    StableDocumentControllerCreateURLMaxChunkSizeType = "str"
	StableDocumentControllerCreateURLMaxChunkSizeTypeNumber StableDocumentControllerCreateURLMaxChunkSizeType = "number"
)

// StableDocumentControllerCreateURLMaxChunkSize - Determines how granularly each document is broken up. Range available is 500-1500 tokens, default is 1000. Smaller chunk size means narrower context, faster response, less tokens consumed, and greater risk of less accurate answers. Max chunk size affects the total amount of chunks parsed from a document - i.e., larger chunks means less chunks retrieved.
type StableDocumentControllerCreateURLMaxChunkSize struct {
	Str    *string  `queryParam:"inline" union:"member"`
	Number *float64 `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLMaxChunkSizeType
}

func CreateStableDocumentControllerCreateURLMaxChunkSizeStr(str string) StableDocumentControllerCreateURLMaxChunkSize {
	typ := StableDocumentControllerCreateURLMaxChunkSizeTypeStr

	return StableDocumentControllerCreateURLMaxChunkSize{
		Str:  &str,
		Type: typ,
	}
}

func CreateStableDocumentControllerCreateURLMaxChunkSizeNumber(number float64) StableDocumentControllerCreateURLMaxChunkSize {
	typ := StableDocumentControllerCreateURLMaxChunkSizeTypeNumber

	return StableDocumentControllerCreateURLMaxChunkSize{
		Number: &number,
		Type:   typ,
	}
}

func (u *StableDocumentControllerCreateURLMaxChunkSize) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLMaxChunkSizeTypeStr,
			Value: &str,
		})
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLMaxChunkSizeTypeNumber,
			Value: &number,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMaxChunkSize", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMaxChunkSize", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLMaxChunkSizeType)
	switch best.Type {
	case StableDocumentControllerCreateURLMaxChunkSizeTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case StableDocumentControllerCreateURLMaxChunkSizeTypeNumber:
		u.Number = best.Value.(*float64)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMaxChunkSize", string(data))
}

func (u StableDocumentControllerCreateURLMaxChunkSize) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLMaxChunkSize: all fields are null")
}

type StableDocumentControllerCreateURLOverwriteEnum string

const (
	StableDocumentControllerCreateURLOverwriteEnumTrue  StableDocumentControllerCreateURLOverwriteEnum = "true"
	StableDocumentControllerCreateURLOverwriteEnumFalse StableDocumentControllerCreateURLOverwriteEnum = "false"
)

func (e StableDocumentControllerCreateURLOverwriteEnum) ToPointer() *StableDocumentControllerCreateURLOverwriteEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLOverwriteEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLOverwriteEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLOverwriteEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLOverwriteUnionType string

const (
	StableDocumentControllerCreateURLOverwriteUnionTypeBoolean                                        StableDocumentControllerCreateURLOverwriteUnionType = "boolean"
	StableDocumentControllerCreateURLOverwriteUnionTypeStableDocumentControllerCreateURLOverwriteEnum StableDocumentControllerCreateURLOverwriteUnionType = "StableDocumentController_createURL_overwrite_enum"
)

// StableDocumentControllerCreateURLOverwriteUnion - If set to true, the existing table with the same name will be overwritten.
type StableDocumentControllerCreateURLOverwriteUnion struct {
	Boolean                                        *bool                                           `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLOverwriteEnum *StableDocumentControllerCreateURLOverwriteEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLOverwriteUnionType
}

func CreateStableDocumentControllerCreateURLOverwriteUnionBoolean(boolean bool) StableDocumentControllerCreateURLOverwriteUnion {
	typ := StableDocumentControllerCreateURLOverwriteUnionTypeBoolean

	return StableDocumentControllerCreateURLOverwriteUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLOverwriteUnionStableDocumentControllerCreateURLOverwriteEnum(stableDocumentControllerCreateURLOverwriteEnum StableDocumentControllerCreateURLOverwriteEnum) StableDocumentControllerCreateURLOverwriteUnion {
	typ := StableDocumentControllerCreateURLOverwriteUnionTypeStableDocumentControllerCreateURLOverwriteEnum

	return StableDocumentControllerCreateURLOverwriteUnion{
		StableDocumentControllerCreateURLOverwriteEnum: &stableDocumentControllerCreateURLOverwriteEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLOverwriteUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLOverwriteUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLOverwriteEnum StableDocumentControllerCreateURLOverwriteEnum = StableDocumentControllerCreateURLOverwriteEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLOverwriteEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLOverwriteUnionTypeStableDocumentControllerCreateURLOverwriteEnum,
			Value: &stableDocumentControllerCreateURLOverwriteEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLOverwriteUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLOverwriteUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLOverwriteUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLOverwriteUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLOverwriteUnionTypeStableDocumentControllerCreateURLOverwriteEnum:
		u.StableDocumentControllerCreateURLOverwriteEnum = best.Value.(*StableDocumentControllerCreateURLOverwriteEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLOverwriteUnion", string(data))
}

func (u StableDocumentControllerCreateURLOverwriteUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLOverwriteEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLOverwriteEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLOverwriteUnion: all fields are null")
}

type StableDocumentControllerCreateURLMarkdownConversionEnum string

const (
	StableDocumentControllerCreateURLMarkdownConversionEnumTrue  StableDocumentControllerCreateURLMarkdownConversionEnum = "true"
	StableDocumentControllerCreateURLMarkdownConversionEnumFalse StableDocumentControllerCreateURLMarkdownConversionEnum = "false"
)

func (e StableDocumentControllerCreateURLMarkdownConversionEnum) ToPointer() *StableDocumentControllerCreateURLMarkdownConversionEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLMarkdownConversionEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLMarkdownConversionEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLMarkdownConversionEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLMarkdownConversionUnionType string

const (
	StableDocumentControllerCreateURLMarkdownConversionUnionTypeBoolean                                                 StableDocumentControllerCreateURLMarkdownConversionUnionType = "boolean"
	StableDocumentControllerCreateURLMarkdownConversionUnionTypeStableDocumentControllerCreateURLMarkdownConversionEnum StableDocumentControllerCreateURLMarkdownConversionUnionType = "StableDocumentController_createURL_markdownConversion_enum"
)

// StableDocumentControllerCreateURLMarkdownConversionUnion - When enabled, HTML is automatically converted to markdown to generate better chunks.
type StableDocumentControllerCreateURLMarkdownConversionUnion struct {
	Boolean                                                 *bool                                                    `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLMarkdownConversionEnum *StableDocumentControllerCreateURLMarkdownConversionEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLMarkdownConversionUnionType
}

func CreateStableDocumentControllerCreateURLMarkdownConversionUnionBoolean(boolean bool) StableDocumentControllerCreateURLMarkdownConversionUnion {
	typ := StableDocumentControllerCreateURLMarkdownConversionUnionTypeBoolean

	return StableDocumentControllerCreateURLMarkdownConversionUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLMarkdownConversionUnionStableDocumentControllerCreateURLMarkdownConversionEnum(stableDocumentControllerCreateURLMarkdownConversionEnum StableDocumentControllerCreateURLMarkdownConversionEnum) StableDocumentControllerCreateURLMarkdownConversionUnion {
	typ := StableDocumentControllerCreateURLMarkdownConversionUnionTypeStableDocumentControllerCreateURLMarkdownConversionEnum

	return StableDocumentControllerCreateURLMarkdownConversionUnion{
		StableDocumentControllerCreateURLMarkdownConversionEnum: &stableDocumentControllerCreateURLMarkdownConversionEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLMarkdownConversionUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLMarkdownConversionUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLMarkdownConversionEnum StableDocumentControllerCreateURLMarkdownConversionEnum = StableDocumentControllerCreateURLMarkdownConversionEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLMarkdownConversionEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLMarkdownConversionUnionTypeStableDocumentControllerCreateURLMarkdownConversionEnum,
			Value: &stableDocumentControllerCreateURLMarkdownConversionEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMarkdownConversionUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMarkdownConversionUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLMarkdownConversionUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLMarkdownConversionUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLMarkdownConversionUnionTypeStableDocumentControllerCreateURLMarkdownConversionEnum:
		u.StableDocumentControllerCreateURLMarkdownConversionEnum = best.Value.(*StableDocumentControllerCreateURLMarkdownConversionEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLMarkdownConversionUnion", string(data))
}

func (u StableDocumentControllerCreateURLMarkdownConversionUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLMarkdownConversionEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLMarkdownConversionEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLMarkdownConversionUnion: all fields are null")
}

type StableDocumentControllerCreateURLLlmBasedChunksEnum string

const (
	StableDocumentControllerCreateURLLlmBasedChunksEnumTrue  StableDocumentControllerCreateURLLlmBasedChunksEnum = "true"
	StableDocumentControllerCreateURLLlmBasedChunksEnumFalse StableDocumentControllerCreateURLLlmBasedChunksEnum = "false"
)

func (e StableDocumentControllerCreateURLLlmBasedChunksEnum) ToPointer() *StableDocumentControllerCreateURLLlmBasedChunksEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLLlmBasedChunksEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLLlmBasedChunksEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLLlmBasedChunksEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLLlmBasedChunksUnionType string

const (
	StableDocumentControllerCreateURLLlmBasedChunksUnionTypeBoolean                                             StableDocumentControllerCreateURLLlmBasedChunksUnionType = "boolean"
	StableDocumentControllerCreateURLLlmBasedChunksUnionTypeStableDocumentControllerCreateURLLlmBasedChunksEnum StableDocumentControllerCreateURLLlmBasedChunksUnionType = "StableDocumentController_createURL_llmBasedChunks_enum"
)

type StableDocumentControllerCreateURLLlmBasedChunksUnion struct {
	Boolean                                             *bool                                                `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLLlmBasedChunksEnum *StableDocumentControllerCreateURLLlmBasedChunksEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLLlmBasedChunksUnionType
}

func CreateStableDocumentControllerCreateURLLlmBasedChunksUnionBoolean(boolean bool) StableDocumentControllerCreateURLLlmBasedChunksUnion {
	typ := StableDocumentControllerCreateURLLlmBasedChunksUnionTypeBoolean

	return StableDocumentControllerCreateURLLlmBasedChunksUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLLlmBasedChunksUnionStableDocumentControllerCreateURLLlmBasedChunksEnum(stableDocumentControllerCreateURLLlmBasedChunksEnum StableDocumentControllerCreateURLLlmBasedChunksEnum) StableDocumentControllerCreateURLLlmBasedChunksUnion {
	typ := StableDocumentControllerCreateURLLlmBasedChunksUnionTypeStableDocumentControllerCreateURLLlmBasedChunksEnum

	return StableDocumentControllerCreateURLLlmBasedChunksUnion{
		StableDocumentControllerCreateURLLlmBasedChunksEnum: &stableDocumentControllerCreateURLLlmBasedChunksEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLLlmBasedChunksUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmBasedChunksUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLLlmBasedChunksEnum StableDocumentControllerCreateURLLlmBasedChunksEnum = StableDocumentControllerCreateURLLlmBasedChunksEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLLlmBasedChunksEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmBasedChunksUnionTypeStableDocumentControllerCreateURLLlmBasedChunksEnum,
			Value: &stableDocumentControllerCreateURLLlmBasedChunksEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmBasedChunksUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmBasedChunksUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLLlmBasedChunksUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLLlmBasedChunksUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLLlmBasedChunksUnionTypeStableDocumentControllerCreateURLLlmBasedChunksEnum:
		u.StableDocumentControllerCreateURLLlmBasedChunksEnum = best.Value.(*StableDocumentControllerCreateURLLlmBasedChunksEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmBasedChunksUnion", string(data))
}

func (u StableDocumentControllerCreateURLLlmBasedChunksUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLLlmBasedChunksEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLLlmBasedChunksEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLLlmBasedChunksUnion: all fields are null")
}

type StableDocumentControllerCreateURLLlmGeneratedQEnum string

const (
	StableDocumentControllerCreateURLLlmGeneratedQEnumTrue  StableDocumentControllerCreateURLLlmGeneratedQEnum = "true"
	StableDocumentControllerCreateURLLlmGeneratedQEnumFalse StableDocumentControllerCreateURLLlmGeneratedQEnum = "false"
)

func (e StableDocumentControllerCreateURLLlmGeneratedQEnum) ToPointer() *StableDocumentControllerCreateURLLlmGeneratedQEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLLlmGeneratedQEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLLlmGeneratedQEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLLlmGeneratedQEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLLlmGeneratedQUnionType string

const (
	StableDocumentControllerCreateURLLlmGeneratedQUnionTypeBoolean                                            StableDocumentControllerCreateURLLlmGeneratedQUnionType = "boolean"
	StableDocumentControllerCreateURLLlmGeneratedQUnionTypeStableDocumentControllerCreateURLLlmGeneratedQEnum StableDocumentControllerCreateURLLlmGeneratedQUnionType = "StableDocumentController_createURL_llmGeneratedQ_enum"
)

// StableDocumentControllerCreateURLLlmGeneratedQUnion - When enabled, an LLM will be used to generate a question based on the document context and specific chunk, then prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries.
type StableDocumentControllerCreateURLLlmGeneratedQUnion struct {
	Boolean                                            *bool                                               `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLLlmGeneratedQEnum *StableDocumentControllerCreateURLLlmGeneratedQEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLLlmGeneratedQUnionType
}

func CreateStableDocumentControllerCreateURLLlmGeneratedQUnionBoolean(boolean bool) StableDocumentControllerCreateURLLlmGeneratedQUnion {
	typ := StableDocumentControllerCreateURLLlmGeneratedQUnionTypeBoolean

	return StableDocumentControllerCreateURLLlmGeneratedQUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLLlmGeneratedQUnionStableDocumentControllerCreateURLLlmGeneratedQEnum(stableDocumentControllerCreateURLLlmGeneratedQEnum StableDocumentControllerCreateURLLlmGeneratedQEnum) StableDocumentControllerCreateURLLlmGeneratedQUnion {
	typ := StableDocumentControllerCreateURLLlmGeneratedQUnionTypeStableDocumentControllerCreateURLLlmGeneratedQEnum

	return StableDocumentControllerCreateURLLlmGeneratedQUnion{
		StableDocumentControllerCreateURLLlmGeneratedQEnum: &stableDocumentControllerCreateURLLlmGeneratedQEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLLlmGeneratedQUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmGeneratedQUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLLlmGeneratedQEnum StableDocumentControllerCreateURLLlmGeneratedQEnum = StableDocumentControllerCreateURLLlmGeneratedQEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLLlmGeneratedQEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmGeneratedQUnionTypeStableDocumentControllerCreateURLLlmGeneratedQEnum,
			Value: &stableDocumentControllerCreateURLLlmGeneratedQEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmGeneratedQUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmGeneratedQUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLLlmGeneratedQUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLLlmGeneratedQUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLLlmGeneratedQUnionTypeStableDocumentControllerCreateURLLlmGeneratedQEnum:
		u.StableDocumentControllerCreateURLLlmGeneratedQEnum = best.Value.(*StableDocumentControllerCreateURLLlmGeneratedQEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmGeneratedQUnion", string(data))
}

func (u StableDocumentControllerCreateURLLlmGeneratedQUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLLlmGeneratedQEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLLlmGeneratedQEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLLlmGeneratedQUnion: all fields are null")
}

type StableDocumentControllerCreateURLLlmContentSummarizationEnum string

const (
	StableDocumentControllerCreateURLLlmContentSummarizationEnumTrue  StableDocumentControllerCreateURLLlmContentSummarizationEnum = "true"
	StableDocumentControllerCreateURLLlmContentSummarizationEnumFalse StableDocumentControllerCreateURLLlmContentSummarizationEnum = "false"
)

func (e StableDocumentControllerCreateURLLlmContentSummarizationEnum) ToPointer() *StableDocumentControllerCreateURLLlmContentSummarizationEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLLlmContentSummarizationEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLLlmContentSummarizationEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLLlmContentSummarizationEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLLlmContentSummarizationUnionType string

const (
	StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeBoolean                                                      StableDocumentControllerCreateURLLlmContentSummarizationUnionType = "boolean"
	StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeStableDocumentControllerCreateURLLlmContentSummarizationEnum StableDocumentControllerCreateURLLlmContentSummarizationUnionType = "StableDocumentController_createURL_llmContentSummarization_enum"
)

// StableDocumentControllerCreateURLLlmContentSummarizationUnion - When enabled, an LLM summarizes and rewrites the content, removing unnecessary information and focusing on important parts to optimize for retrieval. Limited to 15 rows per table upload.
type StableDocumentControllerCreateURLLlmContentSummarizationUnion struct {
	Boolean                                                      *bool                                                         `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLLlmContentSummarizationEnum *StableDocumentControllerCreateURLLlmContentSummarizationEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLLlmContentSummarizationUnionType
}

func CreateStableDocumentControllerCreateURLLlmContentSummarizationUnionBoolean(boolean bool) StableDocumentControllerCreateURLLlmContentSummarizationUnion {
	typ := StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeBoolean

	return StableDocumentControllerCreateURLLlmContentSummarizationUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLLlmContentSummarizationUnionStableDocumentControllerCreateURLLlmContentSummarizationEnum(stableDocumentControllerCreateURLLlmContentSummarizationEnum StableDocumentControllerCreateURLLlmContentSummarizationEnum) StableDocumentControllerCreateURLLlmContentSummarizationUnion {
	typ := StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeStableDocumentControllerCreateURLLlmContentSummarizationEnum

	return StableDocumentControllerCreateURLLlmContentSummarizationUnion{
		StableDocumentControllerCreateURLLlmContentSummarizationEnum: &stableDocumentControllerCreateURLLlmContentSummarizationEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLLlmContentSummarizationUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLLlmContentSummarizationEnum StableDocumentControllerCreateURLLlmContentSummarizationEnum = StableDocumentControllerCreateURLLlmContentSummarizationEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLLlmContentSummarizationEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeStableDocumentControllerCreateURLLlmContentSummarizationEnum,
			Value: &stableDocumentControllerCreateURLLlmContentSummarizationEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmContentSummarizationUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmContentSummarizationUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLLlmContentSummarizationUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLLlmContentSummarizationUnionTypeStableDocumentControllerCreateURLLlmContentSummarizationEnum:
		u.StableDocumentControllerCreateURLLlmContentSummarizationEnum = best.Value.(*StableDocumentControllerCreateURLLlmContentSummarizationEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmContentSummarizationUnion", string(data))
}

func (u StableDocumentControllerCreateURLLlmContentSummarizationUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLLlmContentSummarizationEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLLlmContentSummarizationEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLLlmContentSummarizationUnion: all fields are null")
}

type StableDocumentControllerCreateURLLlmPrependContextEnum string

const (
	StableDocumentControllerCreateURLLlmPrependContextEnumTrue  StableDocumentControllerCreateURLLlmPrependContextEnum = "true"
	StableDocumentControllerCreateURLLlmPrependContextEnumFalse StableDocumentControllerCreateURLLlmPrependContextEnum = "false"
)

func (e StableDocumentControllerCreateURLLlmPrependContextEnum) ToPointer() *StableDocumentControllerCreateURLLlmPrependContextEnum {
	return &e
}
func (e *StableDocumentControllerCreateURLLlmPrependContextEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "true":
		fallthrough
	case "false":
		*e = StableDocumentControllerCreateURLLlmPrependContextEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentControllerCreateURLLlmPrependContextEnum: %v", v)
	}
}

type StableDocumentControllerCreateURLLlmPrependContextUnionType string

const (
	StableDocumentControllerCreateURLLlmPrependContextUnionTypeBoolean                                                StableDocumentControllerCreateURLLlmPrependContextUnionType = "boolean"
	StableDocumentControllerCreateURLLlmPrependContextUnionTypeStableDocumentControllerCreateURLLlmPrependContextEnum StableDocumentControllerCreateURLLlmPrependContextUnionType = "StableDocumentController_createURL_llmPrependContext_enum"
)

// StableDocumentControllerCreateURLLlmPrependContextUnion - When enabled, an LLM generates a context summary based on the document and chunk context, and prepends it to each chunk. This improves retrieval by providing additional context to each chunk. Note: If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied.
type StableDocumentControllerCreateURLLlmPrependContextUnion struct {
	Boolean                                                *bool                                                   `queryParam:"inline" union:"member"`
	StableDocumentControllerCreateURLLlmPrependContextEnum *StableDocumentControllerCreateURLLlmPrependContextEnum `queryParam:"inline" union:"member"`

	Type StableDocumentControllerCreateURLLlmPrependContextUnionType
}

func CreateStableDocumentControllerCreateURLLlmPrependContextUnionBoolean(boolean bool) StableDocumentControllerCreateURLLlmPrependContextUnion {
	typ := StableDocumentControllerCreateURLLlmPrependContextUnionTypeBoolean

	return StableDocumentControllerCreateURLLlmPrependContextUnion{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateStableDocumentControllerCreateURLLlmPrependContextUnionStableDocumentControllerCreateURLLlmPrependContextEnum(stableDocumentControllerCreateURLLlmPrependContextEnum StableDocumentControllerCreateURLLlmPrependContextEnum) StableDocumentControllerCreateURLLlmPrependContextUnion {
	typ := StableDocumentControllerCreateURLLlmPrependContextUnionTypeStableDocumentControllerCreateURLLlmPrependContextEnum

	return StableDocumentControllerCreateURLLlmPrependContextUnion{
		StableDocumentControllerCreateURLLlmPrependContextEnum: &stableDocumentControllerCreateURLLlmPrependContextEnum,
		Type: typ,
	}
}

func (u *StableDocumentControllerCreateURLLlmPrependContextUnion) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmPrependContextUnionTypeBoolean,
			Value: &boolean,
		})
	}

	var stableDocumentControllerCreateURLLlmPrependContextEnum StableDocumentControllerCreateURLLlmPrependContextEnum = StableDocumentControllerCreateURLLlmPrependContextEnum("")
	if err := utils.UnmarshalJSON(data, &stableDocumentControllerCreateURLLlmPrependContextEnum, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableDocumentControllerCreateURLLlmPrependContextUnionTypeStableDocumentControllerCreateURLLlmPrependContextEnum,
			Value: &stableDocumentControllerCreateURLLlmPrependContextEnum,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmPrependContextUnion", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmPrependContextUnion", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableDocumentControllerCreateURLLlmPrependContextUnionType)
	switch best.Type {
	case StableDocumentControllerCreateURLLlmPrependContextUnionTypeBoolean:
		u.Boolean = best.Value.(*bool)
		return nil
	case StableDocumentControllerCreateURLLlmPrependContextUnionTypeStableDocumentControllerCreateURLLlmPrependContextEnum:
		u.StableDocumentControllerCreateURLLlmPrependContextEnum = best.Value.(*StableDocumentControllerCreateURLLlmPrependContextEnum)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableDocumentControllerCreateURLLlmPrependContextUnion", string(data))
}

func (u StableDocumentControllerCreateURLLlmPrependContextUnion) MarshalJSON() ([]byte, error) {
	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.StableDocumentControllerCreateURLLlmPrependContextEnum != nil {
		return utils.MarshalJSON(u.StableDocumentControllerCreateURLLlmPrependContextEnum, "", true)
	}

	return nil, errors.New("could not marshal union type StableDocumentControllerCreateURLLlmPrependContextUnion: all fields are null")
}

type StableDocumentControllerCreateURLRequest struct {
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	// Determines how granularly each document is broken up. Range available is 500-1500 tokens, default is 1000. Smaller chunk size means narrower context, faster response, less tokens consumed, and greater risk of less accurate answers. Max chunk size affects the total amount of chunks parsed from a document - i.e., larger chunks means less chunks retrieved.
	MaxChunkSize *StableDocumentControllerCreateURLMaxChunkSize `queryParam:"style=form,explode=true,name=maxChunkSize"`
	// If set to true, the existing table with the same name will be overwritten.
	Overwrite *StableDocumentControllerCreateURLOverwriteUnion `queryParam:"style=form,explode=true,name=overwrite"`
	// When enabled, HTML is automatically converted to markdown to generate better chunks.
	MarkdownConversion *StableDocumentControllerCreateURLMarkdownConversionUnion `queryParam:"style=form,explode=true,name=markdownConversion"`
	LlmBasedChunks     *StableDocumentControllerCreateURLLlmBasedChunksUnion     `queryParam:"style=form,explode=true,name=llmBasedChunks"`
	// When enabled, an LLM will be used to generate a question based on the document context and specific chunk, then prepend it to the chunk. This enhances retrieval by aligning chunks with potential user queries.
	LlmGeneratedQ *StableDocumentControllerCreateURLLlmGeneratedQUnion `queryParam:"style=form,explode=true,name=llmGeneratedQ"`
	// When enabled, an LLM summarizes and rewrites the content, removing unnecessary information and focusing on important parts to optimize for retrieval. Limited to 15 rows per table upload.
	LlmContentSummarization *StableDocumentControllerCreateURLLlmContentSummarizationUnion `queryParam:"style=form,explode=true,name=llmContentSummarization"`
	// When enabled, an LLM generates a context summary based on the document and chunk context, and prepends it to each chunk. This improves retrieval by providing additional context to each chunk. Note: If both llmGeneratedQ and llmPrependContext are set to true, llmGeneratedQ takes precedence, and the context summarization will not be applied.
	LlmPrependContext *StableDocumentControllerCreateURLLlmPrependContextUnion `queryParam:"style=form,explode=true,name=llmPrependContext"`
	Body              components.StableDocumentCreateURLRequest                `request:"mediaType=application/json"`
}

func (s *StableDocumentControllerCreateURLRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableDocumentControllerCreateURLRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableDocumentControllerCreateURLRequest) GetMaxChunkSize() *StableDocumentControllerCreateURLMaxChunkSize {
	if s == nil {
		return nil
	}
	return s.MaxChunkSize
}

func (s *StableDocumentControllerCreateURLRequest) GetOverwrite() *StableDocumentControllerCreateURLOverwriteUnion {
	if s == nil {
		return nil
	}
	return s.Overwrite
}

func (s *StableDocumentControllerCreateURLRequest) GetMarkdownConversion() *StableDocumentControllerCreateURLMarkdownConversionUnion {
	if s == nil {
		return nil
	}
	return s.MarkdownConversion
}

func (s *StableDocumentControllerCreateURLRequest) GetLlmBasedChunks() *StableDocumentControllerCreateURLLlmBasedChunksUnion {
	if s == nil {
		return nil
	}
	return s.LlmBasedChunks
}

func (s *StableDocumentControllerCreateURLRequest) GetLlmGeneratedQ() *StableDocumentControllerCreateURLLlmGeneratedQUnion {
	if s == nil {
		return nil
	}
	return s.LlmGeneratedQ
}

func (s *StableDocumentControllerCreateURLRequest) GetLlmContentSummarization() *StableDocumentControllerCreateURLLlmContentSummarizationUnion {
	if s == nil {
		return nil
	}
	return s.LlmContentSummarization
}

func (s *StableDocumentControllerCreateURLRequest) GetLlmPrependContext() *StableDocumentControllerCreateURLLlmPrependContextUnion {
	if s == nil {
		return nil
	}
	return s.LlmPrependContext
}

func (s *StableDocumentControllerCreateURLRequest) GetBody() components.StableDocumentCreateURLRequest {
	if s == nil {
		return components.StableDocumentCreateURLRequest{}
	}
	return s.Body
}

type StableDocumentControllerCreateURLResponse struct {
	HTTPMeta               components.HTTPMetadata `json:"-"`
	StableDocumentResponse *components.StableDocumentResponse
}

func (s StableDocumentControllerCreateURLResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableDocumentControllerCreateURLResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableDocumentControllerCreateURLResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableDocumentControllerCreateURLResponse) GetStableDocumentResponse() *components.StableDocumentResponse {
	if s == nil {
		return nil
	}
	return s.StableDocumentResponse
}
