// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 55bd69ed138c

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableAPIToolControllerGetV2Request struct {
	ToolID           string `pathParam:"style=simple,explode=false,name=toolID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
}

func (s *StableAPIToolControllerGetV2Request) GetToolID() string {
	if s == nil {
		return ""
	}
	return s.ToolID
}

func (s *StableAPIToolControllerGetV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableAPIToolControllerGetV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

// #region class-body-stableapitoolcontrollergetv2request
// #endregion class-body-stableapitoolcontrollergetv2request

type StableAPIToolControllerGetV2Response struct {
	HTTPMeta                  components.HTTPMetadata `json:"-"`
	StableAPIToolReadResponse *components.StableAPIToolReadResponse
}

func (s StableAPIToolControllerGetV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableAPIToolControllerGetV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableAPIToolControllerGetV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableAPIToolControllerGetV2Response) GetStableAPIToolReadResponse() *components.StableAPIToolReadResponse {
	if s == nil {
		return nil
	}
	return s.StableAPIToolReadResponse
}

// #region class-body-stableapitoolcontrollergetv2response
// #endregion class-body-stableapitoolcontrollergetv2response
