// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: bbe774b29ebd

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StablePlaybookControllerReadInstructionsRequest struct {
	PlaybookID       string `pathParam:"style=simple,explode=false,name=playbookID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	Offset           *int64 `default:"1" queryParam:"style=form,explode=true,name=offset"`
	Limit            *int64 `default:"400" queryParam:"style=form,explode=true,name=limit"`
}

func (s StablePlaybookControllerReadInstructionsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookControllerReadInstructionsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookControllerReadInstructionsRequest) GetPlaybookID() string {
	if s == nil {
		return ""
	}
	return s.PlaybookID
}

func (s *StablePlaybookControllerReadInstructionsRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StablePlaybookControllerReadInstructionsRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StablePlaybookControllerReadInstructionsRequest) GetOffset() *int64 {
	if s == nil {
		return nil
	}
	return s.Offset
}

func (s *StablePlaybookControllerReadInstructionsRequest) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

type StablePlaybookControllerReadInstructionsResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	StableInstructionsReadResponse *components.StableInstructionsReadResponse
}

func (s StablePlaybookControllerReadInstructionsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookControllerReadInstructionsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookControllerReadInstructionsResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StablePlaybookControllerReadInstructionsResponse) GetStableInstructionsReadResponse() *components.StableInstructionsReadResponse {
	if s == nil {
		return nil
	}
	return s.StableInstructionsReadResponse
}
