// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e584d519dfe8

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// StableWidgetControllerGetSnippetVersion - Pins the embed to one version of the environment: `draft`, the version used when testing, or `published`, the version serving live traffic. Omit it to pin the snippet to `published`.
type StableWidgetControllerGetSnippetVersion string

const (
	StableWidgetControllerGetSnippetVersionDraft     StableWidgetControllerGetSnippetVersion = "draft"
	StableWidgetControllerGetSnippetVersionPublished StableWidgetControllerGetSnippetVersion = "published"
)

func (e StableWidgetControllerGetSnippetVersion) ToPointer() *StableWidgetControllerGetSnippetVersion {
	return &e
}
func (e *StableWidgetControllerGetSnippetVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "published":
		*e = StableWidgetControllerGetSnippetVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableWidgetControllerGetSnippetVersion: %v", v)
	}
}

type StableWidgetControllerGetSnippetRequest struct {
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	// Pins the embed to one version of the environment: `draft`, the version used when testing, or `published`, the version serving live traffic. Omit it to pin the snippet to `published`.
	Version *StableWidgetControllerGetSnippetVersion `default:"published" queryParam:"style=form,explode=true,name=version"`
}

func (s StableWidgetControllerGetSnippetRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableWidgetControllerGetSnippetRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableWidgetControllerGetSnippetRequest) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableWidgetControllerGetSnippetRequest) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StableWidgetControllerGetSnippetRequest) GetVersion() *StableWidgetControllerGetSnippetVersion {
	if s == nil {
		return nil
	}
	return s.Version
}

type StableWidgetControllerGetSnippetResponse struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	StableWidgetGetSnippetResponse *components.StableWidgetGetSnippetResponse
}

func (s StableWidgetControllerGetSnippetResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableWidgetControllerGetSnippetResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableWidgetControllerGetSnippetResponse) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StableWidgetControllerGetSnippetResponse) GetStableWidgetGetSnippetResponse() *components.StableWidgetGetSnippetResponse {
	if s == nil {
		return nil
	}
	return s.StableWidgetGetSnippetResponse
}
