// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: aaeb1e60a151

package operations

import (
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StablePlaybookControllerReadInstructionsV2Request struct {
	PlaybookID       string `pathParam:"style=simple,explode=false,name=playbookID"`
	ProjectID        string `queryParam:"style=form,explode=true,name=projectID"`
	EnvironmentAlias string `queryParam:"style=form,explode=true,name=environmentAlias"`
	Offset           *int64 `default:"1" queryParam:"style=form,explode=true,name=offset"`
	Limit            *int64 `default:"400" queryParam:"style=form,explode=true,name=limit"`
}

func (s StablePlaybookControllerReadInstructionsV2Request) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookControllerReadInstructionsV2Request) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookControllerReadInstructionsV2Request) GetPlaybookID() string {
	if s == nil {
		return ""
	}
	return s.PlaybookID
}

func (s *StablePlaybookControllerReadInstructionsV2Request) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StablePlaybookControllerReadInstructionsV2Request) GetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.EnvironmentAlias
}

func (s *StablePlaybookControllerReadInstructionsV2Request) GetOffset() *int64 {
	if s == nil {
		return nil
	}
	return s.Offset
}

func (s *StablePlaybookControllerReadInstructionsV2Request) GetLimit() *int64 {
	if s == nil {
		return nil
	}
	return s.Limit
}

// #region class-body-stableplaybookcontrollerreadinstructionsv2request
// #endregion class-body-stableplaybookcontrollerreadinstructionsv2request

type StablePlaybookControllerReadInstructionsV2Response struct {
	HTTPMeta                       components.HTTPMetadata `json:"-"`
	StableInstructionsReadResponse *components.StableInstructionsReadResponse
}

func (s StablePlaybookControllerReadInstructionsV2Response) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookControllerReadInstructionsV2Response) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookControllerReadInstructionsV2Response) GetHTTPMeta() components.HTTPMetadata {
	if s == nil {
		return components.HTTPMetadata{}
	}
	return s.HTTPMeta
}

func (s *StablePlaybookControllerReadInstructionsV2Response) GetStableInstructionsReadResponse() *components.StableInstructionsReadResponse {
	if s == nil {
		return nil
	}
	return s.StableInstructionsReadResponse
}

// #region class-body-stableplaybookcontrollerreadinstructionsv2response
// #endregion class-body-stableplaybookcontrollerreadinstructionsv2response
