// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e442deed10be

package integration

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var connectCmdMeta = []flagutil.FlagMeta{
	{FlagName: "integration", Shorthand: "i", FieldPath: "Integration", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Integration", TypeDescription: "JSON value (variants: eleven_labs: { integration: string, credentials: string }, twilio: { integration: string, credentials: object }, ujet: { integration: string, credentials: object }, genesys: { integration: string, credentials: object }, kustomer: { integration: string, credentials: object }, dixa: { integration: string, credentials: object }, sunshine: { integration: string, credentials: object }, zendesk: { integration: string }, salesforce: { integration: string }, shopify: { integration: string }, google_sheets: { integration: string }, google_gmail: { integration: string }, airtable: { integration: string }, make: { integration: string }, hubspot: { integration: string }, example: { integration: string })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "eleven_labs", FlagName: "body-param.eleven-labs", FieldName: "StableIntegrationConnectRequestElevenLabs", CanExpand: true, Description: "StableIntegrationConnectRequest_ElevenLabs variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.eleven-labs.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "twilio", FlagName: "body-param.twilio", FieldName: "StableIntegrationConnectRequestTwilio", CanExpand: true, Description: "StableIntegrationConnectRequest_Twilio variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.twilio.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "ujet", FlagName: "body-param.ujet", FieldName: "StableIntegrationConnectRequestUjet", CanExpand: true, Description: "StableIntegrationConnectRequest_Ujet variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.ujet.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "genesys", FlagName: "body-param.genesys", FieldName: "StableIntegrationConnectRequestGenesys", CanExpand: true, Description: "StableIntegrationConnectRequest_Genesys variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.genesys.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "kustomer", FlagName: "body-param.kustomer", FieldName: "StableIntegrationConnectRequestKustomer", CanExpand: true, Description: "StableIntegrationConnectRequest_Kustomer variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.kustomer.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "dixa", FlagName: "body-param.dixa", FieldName: "StableIntegrationConnectRequestDixa", CanExpand: true, Description: "StableIntegrationConnectRequest_Dixa variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.dixa.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "sunshine", FlagName: "body-param.sunshine", FieldName: "StableIntegrationConnectRequestSunshine", CanExpand: true, Description: "StableIntegrationConnectRequest_Sunshine variant as JSON", Fields: []flagutil.FlagMeta{
			{FlagName: "body-param.sunshine.credentials", FieldPath: "Credentials", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
		}},
		{DiscriminatorValue: "zendesk", FlagName: "body-param.zendesk", FieldName: "StableIntegrationConnectRequestZendesk", CanExpand: true, Description: "StableIntegrationConnectRequest_Zendesk variant as JSON"},
		{DiscriminatorValue: "salesforce", FlagName: "body-param.salesforce", FieldName: "StableIntegrationConnectRequestSalesforce", CanExpand: true, Description: "StableIntegrationConnectRequest_Salesforce variant as JSON"},
		{DiscriminatorValue: "shopify", FlagName: "body-param.shopify", FieldName: "StableIntegrationConnectRequestShopify", CanExpand: true, Description: "StableIntegrationConnectRequest_Shopify variant as JSON"},
		{DiscriminatorValue: "google_sheets", FlagName: "body-param.google-sheets", FieldName: "StableIntegrationConnectRequestGoogleSheets", CanExpand: true, Description: "StableIntegrationConnectRequest_GoogleSheets variant as JSON"},
		{DiscriminatorValue: "google_gmail", FlagName: "body-param.google-gmail", FieldName: "StableIntegrationConnectRequestGoogleGmail", CanExpand: true, Description: "StableIntegrationConnectRequest_GoogleGmail variant as JSON"},
		{DiscriminatorValue: "airtable", FlagName: "body-param.airtable", FieldName: "StableIntegrationConnectRequestAirtable", CanExpand: true, Description: "StableIntegrationConnectRequest_Airtable variant as JSON"},
		{DiscriminatorValue: "make", FlagName: "body-param.make", FieldName: "StableIntegrationConnectRequestMake", CanExpand: true, Description: "StableIntegrationConnectRequest_Make variant as JSON"},
		{DiscriminatorValue: "hubspot", FlagName: "body-param.hubspot", FieldName: "StableIntegrationConnectRequestHubspot", CanExpand: true, Description: "StableIntegrationConnectRequest_Hubspot variant as JSON"},
		{DiscriminatorValue: "example", FlagName: "body-param.example", FieldName: "StableIntegrationConnectRequestExample", CanExpand: true, Description: "StableIntegrationConnectRequest_Example variant as JSON"},
	}}},
}

// initConnectCmd initializes the connect command.
func initConnectCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "connect",
		Short:   "Connect integration",
		Long:    "Store credentials for an api-key integration on this project.",
		Example: "  vf integration connect --integration <value> --project-id <id>",
		RunE:    runConnectCmd,
	}
	flagutil.RegisterFlags(cmd, connectCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableIntegrationControllerConnectRequest](connectCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for connect: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runConnectCmd executes the connect command.
func runConnectCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, connectCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, connectCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableIntegrationControllerConnectRequest](cmd, connectCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Integration.Connect(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
