// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e822a7285aea

package tool

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-alias", Shorthand: "e", FieldPath: "EnvironmentAlias", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Type", TypeDescription: "JSON value (variants: api: { description: string, target: object, messages: object, captureInputVariables: object, ... }, function: { description: string, target: object, messages: object, captureInputVariables: object, ... }, mcp: { description: string, target: object, messages: object, captureInputVariables: object, ... }, integration: { description: string, target: object, messages: object, captureInputVariables: object, ... })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "api", FlagName: "body-param.api", FieldName: "StableToolCreateRequestAPI", CanExpand: false, Description: "StableToolCreateRequest_API variant as JSON"},
		{DiscriminatorValue: "function", FlagName: "body-param.function", FieldName: "StableToolCreateRequestFunction", CanExpand: false, Description: "StableToolCreateRequest_Function variant as JSON"},
		{DiscriminatorValue: "mcp", FlagName: "body-param.mcp", FieldName: "StableToolCreateRequestMcp", CanExpand: false, Description: "StableToolCreateRequest_Mcp variant as JSON"},
		{DiscriminatorValue: "integration", FlagName: "body-param.integration", FieldName: "StableToolCreateRequestIntegration", CanExpand: false, Description: "StableToolCreateRequest_Integration variant as JSON"},
	}}},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create tool",
		Long:    "Create a new tool.",
		Example: "  vf tool create --project-id <id> --environment-alias <value>",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableToolControllerCreateRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableToolControllerCreateRequest](cmd, createCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Tool.Create(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
