// Tests for `vf context`: one call that summarizes a project for an AI coding
// agent — what the agent is, what changed recently, the latest conversations,
// and the rules for working on it.
//
// Every case runs the real binary in a linked temporary directory with an
// isolated HOME, against a mock server on loopback that answers the eleven
// reads `vf context` makes. Nothing here reaches the network.
// Requires: go build -o vf ./cmd/vf

import { execa } from 'execa';
import * as fs from 'node:fs';
import * as http from 'node:http';
import type { AddressInfo } from 'node:net';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

const VF = path.resolve(__dirname, '..', 'vf');

// Every variable that puts the CLI into agent mode; see flag-errors.test.ts.
const AGENT_ENV_VARS = [
  'CLAUDECODE', 'CLAUDE_CODE', 'CURSOR_AGENT', 'CODEX', 'AIDER', 'CLINE',
  'WINDSURF_AGENT', 'GITHUB_COPILOT', 'AMAZON_Q', 'GEMINI_CODE_ASSIST',
  'SRC_CODY', 'FORCE_AGENT_MODE',
];

const PROJECT_ID = '0123456789abcdef01234567';
const minutesAgo = (m: number) => new Date(Date.UTC(2026, 8, 29, 12, 0, 0) - m * 60_000).toISOString();

/** The reads `vf context` makes, keyed by path; each returns a fixture. */
const FIXTURES: Record<string, object> = {
  [`/v1/stable/project/${PROJECT_ID}`]: {
    project: { id: PROJECT_ID, name: 'Returns bot', image: null, createdAt: minutesAgo(9000), updatedAt: minutesAgo(10), workspaceID: 'VzElNm0wjL', description: null },
  },
  '/v2/stable/agent': {
    agent: {
      llm: { defaults: { model: 'voiceflow-core-4.1' } },
      prompt: 'You are Nova, the returns assistant for Lumen.',
      includeGuidelines: false,
      instructions: 'Route refund questions to Refunds.',
      promptLineCount: 12,
      instructionsLineCount: 30,
      playbooks: [{ playbookID: 'pb-refunds', description: 'Use when the customer asks for a refund.' }],
      workflows: [],
      pathToolOrder: [],
      knowledgeBaseTool: { enabled: true, description: '' },
      endTool: { enabled: false, description: '' },
    },
  },
  '/v1/stable/environment/main': {
    environment: { name: 'Main', alias: 'main', isMain: true, trafficPercentage: 100, createdAt: minutesAgo(9000), releases: [{ name: 'V1.2', backupID: 1, createdAt: minutesAgo(600), description: null, autogenerated: false }] },
  },
  '/v2/stable/playbook': {
    playbooks: [{ id: 'pb-refunds', name: 'Refunds', settings: {}, createdAt: minutesAgo(9000), updatedAt: minutesAgo(3), description: 'Handles refunds.', pathToolOrder: [], instructionsLineCount: 40 }],
  },
  '/v1/stable/function': {
    functions: [{ id: 'fn-order', name: 'lookupOrder', code: 'export default async function main() {}', image: null, createdAt: minutesAgo(9000), updatedAt: minutesAgo(30), pathOrder: [], description: 'Finds an order.' }],
  },
  '/v2/stable/tool': {
    tools: [{ type: 'function', id: 'tool-1', functionID: 'fn-order', description: '', createdAt: minutesAgo(9000), updatedAt: minutesAgo(1), asyncExecution: false, inputVariables: {}, captureResponse: {}, captureInputVariables: {}, messages: null }],
  },
  '/v2/stable/variable': {
    variables: [
      { id: 'v1', name: 'order_id', color: '#000', isSystem: false, createdAt: minutesAgo(9000), updatedAt: minutesAgo(45), description: null, defaultValue: null },
      { id: 'v2', name: 'sessions', color: '#000', isSystem: true, createdAt: minutesAgo(9000), updatedAt: minutesAgo(0), description: null, defaultValue: null },
    ],
  },
  '/v1/stable/document': {
    documents: [
      { id: 'd1', data: { type: 'url', name: 'FAQ', url: 'https://example.com/faq' }, status: { type: 'SUCCESS' } },
      { id: 'd2', data: { type: 'pdf', name: 'Returns policy', url: null }, status: { type: 'SUCCESS' } },
    ],
  },
  '/v2/stable/mcp-server': { mcpServers: [] },
  '/v1/stable/test': { tests: [] },
  '/v1/stable/transcript/search': {
    transcripts: [
      { id: 't-new', userID: 'u1', projectID: PROJECT_ID, sessionID: 's1', createdAt: minutesAgo(5), updatedAt: minutesAgo(4), endedAt: minutesAgo(4), properties: [], evaluations: [] },
    ],
  },
};

let server: http.Server;
let serverURL: string;
let requests: { method: string; url: URL; body: string }[] = [];
let failures: Record<string, number> = {};
let home: string;
let cwd: string;

beforeAll(async () => {
  home = fs.mkdtempSync(path.join(os.tmpdir(), 'vf-context-home-'));
  server = http.createServer((req, res) => {
    let body = '';
    req.on('data', (chunk) => (body += chunk));
    req.on('end', () => {
      const url = new URL(req.url ?? '/', 'http://mock');
      requests.push({ method: req.method ?? '', url, body });
      const reply = (status: number, payload: object) => {
        res.writeHead(status, { 'content-type': 'application/json' });
        res.end(JSON.stringify(payload));
      };
      const failure = failures[url.pathname];
      if (failure) return reply(failure, { statusCode: failure, message: 'nope' });
      const fixture = FIXTURES[url.pathname];
      return fixture ? reply(200, fixture) : reply(404, { statusCode: 404, message: 'Not found' });
    });
  });
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  serverURL = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
});

afterAll(async () => {
  await new Promise<void>((resolve) => server.close(() => resolve()));
  fs.rmSync(home, { recursive: true, force: true });
});

beforeEach(() => {
  requests = [];
  failures = {};
  cwd = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'vf-context-cwd-')));
  fs.mkdirSync(path.join(cwd, '.voiceflow'));
  fs.writeFileSync(path.join(cwd, '.voiceflow', 'project.json'), JSON.stringify({ projectID: PROJECT_ID, environmentAlias: 'main' }));
});

function run(args: string[], opts: { dir?: string } = {}) {
  const env: Record<string, string | undefined> = Object.fromEntries(AGENT_ENV_VARS.map((name) => [name, undefined]));
  Object.assign(env, { HOME: home, CI: '', VF_TOKEN: 'vfp_test', CLAUDECODE: '1' });
  return execa({ reject: false, timeout: 30_000, stdin: 'ignore', env, extendEnv: true, cwd: opts.dir ?? cwd })(VF, [...args, '--server-url', serverURL]);
}

describe('vf context', () => {
  it('summarizes the linked project in one call', async () => {
    const result = await run(['context', '--output-format', 'json']);
    expect(result.exitCode, result.stderr).toBe(0);
    const outline = JSON.parse(result.stdout);

    expect(outline.project).toEqual({ id: PROJECT_ID, name: 'Returns bot', workspaceID: 'VzElNm0wjL' });
    expect(outline.environment).toMatchObject({ alias: 'main', isMain: true, lastRelease: { name: 'V1.2' } });
    expect(outline.agent).toMatchObject({
      model: 'voiceflow-core-4.1',
      globalPrompt: { lines: 12, preview: 'You are Nova, the returns assistant for Lumen.' },
      systemTools: ['knowledgeBase'],
    });
    expect(outline.playbooks).toEqual([
      expect.objectContaining({ name: 'Refunds', routed: true, summary: 'Use when the customer asks for a refund.' }),
    ]);
    expect(outline.counts).toEqual({ playbooks: 1, workflows: 0, functions: 1, agentTools: 1, variables: 1, documents: 2, mcpServers: 0, tests: 0 });
    expect(outline.agentToolsByType).toEqual({ function: 1 });
    expect(outline.knowledgeBase).toEqual({ documents: 2, byType: { url: 1, pdf: 1 }, examples: ['FAQ', 'Returns policy'] });
    expect(outline.variables).toEqual(['order_id']);
    expect(outline.recentChanges.map((c: { type: string; name: string }) => `${c.type}:${c.name}`)).toEqual([
      'function tool:lookupOrder',
      'playbook:Refunds',
      'function:lookupOrder',
      'variable:order_id',
    ]);
    expect(outline.recentConversations).toEqual([expect.objectContaining({ id: 't-new', ended: true })]);
    expect(outline.rules.join(' ')).toContain('vf environment compile');
    expect(outline.warnings).toEqual([]);

    // Eleven reads, all for the linked project; the agent's tools are asked for explicitly.
    expect(requests).toHaveLength(11);
    for (const r of requests) {
      expect(r.url.pathname.includes(PROJECT_ID) || r.url.searchParams.get('projectID') === PROJECT_ID, r.url.href).toBe(true);
    }
    expect(requests.find((r) => r.url.pathname === '/v2/stable/tool')?.url.searchParams.get('global')).toBe('true');
    const search = requests.find((r) => r.url.pathname === '/v1/stable/transcript/search');
    expect(search?.method).toBe('POST');
    expect(JSON.parse(search!.body)).toMatchObject({ take: 5, environmentAlias: 'main' });
  });

  it('prints TOON in agent mode with plain keys, well under the size budget', async () => {
    const result = await run(['context']);
    expect(result.exitCode, result.stderr).toBe(0);
    expect(result.stdout).toContain('project:');
    expect(result.stdout).not.toContain(',omit');
    expect(Buffer.byteLength(result.stdout)).toBeLessThan(20 * 1024);
  });

  it('still prints when a part cannot be read, and says what is missing', async () => {
    failures['/v1/stable/document'] = 403;

    const result = await run(['context', '--output-format', 'json']);
    expect(result.exitCode, result.stderr).toBe(0);
    const outline = JSON.parse(result.stdout);
    expect(outline.warnings).toEqual(['knowledge base could not be read: HTTP 403']);
    expect(outline.counts.documents).toBeNull();
    expect(outline.project.name).toBe('Returns bot');
  });

  it('fails when the agent itself cannot be read', async () => {
    failures['/v2/stable/agent'] = 404;

    const result = await run(['context']);
    expect(result.exitCode).toBe(1);
    expect(JSON.parse(result.stderr).error_type).toBe('not_found');
  });

  it('names the fix when no project is linked or given', async () => {
    const bare = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'vf-context-bare-')));

    const result = await run(['context'], { dir: bare });
    expect(result.exitCode).toBe(1);
    const envelope = JSON.parse(result.stderr);
    expect(envelope.error_type).toBe('no_project');
    expect(JSON.stringify(envelope.hints)).toContain('vf link');
    expect(requests).toEqual([]);
  });

  it('sends nothing on --dry-run', async () => {
    const result = await run(['context', '--dry-run']);
    expect(result.exitCode, result.stderr).toBe(0);
    expect(result.stderr.match(/\[DRY-RUN\] Would send/g)).toHaveLength(11);
    expect(requests).toEqual([]);
  });
});
