// This file is not generated by Speakeasy — it gives flag-parsing failures a
// typed shape so they can be rendered with the same care as API errors.
//
// The problem it solves: errors produced while interpreting a flag value never
// reach output.Error. They are returned raw from the generated RunE, and because
// the root command sets SilenceErrors, cmd/vf/main.go prints them with a bare
// Fprintln. So an agent that mistypes a flag gets one unstructured line, while
// an agent that gets a 401 back from the API gets a structured envelope with
// hints and a docs URL. That is backwards: mistyped flags are the more common
// failure, and they are the one the caller can actually act on.
//
// flagutil cannot import output — output already imports flagutil, so that
// direction is an import cycle. This type is therefore pure data. It is carried
// up to cli.Execute, which has both the *cobra.Command and permission to import
// output, and is rendered there.

package flagutil

import (
	"fmt"
	"strings"
)

// FlagValueError reports a flag whose value could not be interpreted.
//
// It follows the house style already used for date parsing in this package —
// state the expectation, show a worked example, echo what was actually passed —
// so the reader can see the difference between what they wrote and what was
// wanted without consulting documentation.
type FlagValueError struct {
	Flag     string   // flag name, without leading dashes
	Value    string   // what the user actually passed
	Expected string   // one line: what the flag wanted instead
	Hints    []string // concrete next actions, most likely fix first
	Cause    error    // underlying parse error, preserved for errors.Is/As
}

func (e *FlagValueError) Error() string {
	var b strings.Builder
	fmt.Fprintf(&b, "invalid value for --%s: %s", e.Flag, e.Expected)
	if e.Value != "" {
		fmt.Fprintf(&b, "\n  you passed: %s", truncateForError(e.Value))
	}
	for _, h := range e.Hints {
		fmt.Fprintf(&b, "\n  %s", h)
	}
	return b.String()
}

func (e *FlagValueError) Unwrap() error { return e.Cause }

// truncateForError keeps a long value from burying the explanation. Instructions
// and prompts are routinely thousands of characters; echoing one in full pushes
// the hints off the reader's screen, which defeats the point of the hints.
func truncateForError(s string) string {
	const max = 120
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) <= max {
		return s
	}
	return s[:max] + "… (" + fmt.Sprint(len(s)) + " chars)"
}
