// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apitool

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "tool-id", Shorthand: "t", FieldPath: "ToolID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-alias", Shorthand: "e", FieldPath: "EnvironmentAlias", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "url", Shorthand: "u", FieldPath: "Body.URL", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"url,omitempty"`, Description: "list of values"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "body-param", Shorthand: "b", FieldPath: "Body.Body", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: true, DiscriminatorKey: "Type", Optional: true, TypeDescription: "JSON value (variants: raw-input: { type: string, contentType: string, content: value[] }, form-data: { type: string, formData: object[] }, url-encoded: { type: string, params: object[] })", Variants: []flagutil.UnionVariantMeta{
		{DiscriminatorValue: "raw-input", FlagName: "body-param.raw-input", FieldName: "StableAPIToolUpdateRequestAPIToolRawBody", CanExpand: false, Description: "StableAPIToolUpdateRequest_APIToolRawBody variant as JSON"},
		{DiscriminatorValue: "form-data", FlagName: "body-param.form-data", FieldName: "StableAPIToolUpdateRequestAPIToolFormDataBody", CanExpand: false, Description: "StableAPIToolUpdateRequest_APIToolFormDataBody variant as JSON"},
		{DiscriminatorValue: "url-encoded", FlagName: "body-param.url-encoded", FieldName: "StableAPIToolUpdateRequestAPIToolURLEncodedBody", CanExpand: false, Description: "StableAPIToolUpdateRequest_APIToolURLEncodedBody variant as JSON"},
	}}},
	{FlagName: "headers", FieldPath: "Body.Headers", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"headers,omitempty"`, Description: "list of values"},
	{FlagName: "settings", Shorthand: "s", FieldPath: "Body.Settings", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"settings,omitempty"`, Description: "JSON object"},
	{FlagName: "http-method", FieldPath: "Body.HTTPMethod", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"get", "put", "post", "patch", "delete"}, Description: "options: get, put, post, patch, delete"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "A description of what the API tool does, used by the agent to decide when to call it."},
	{FlagName: "query-parameters", FieldPath: "Body.QueryParameters", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"queryParameters,omitempty"`, Description: "list of values"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update API tool",
		Long:    "Update an API tool by ID.",
		Example: "  vf api-tool update --tool-id <id> --project-id <id> --environment-alias <value>",
		RunE:    runUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableAPIToolControllerUpdateRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableAPIToolControllerUpdateRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.APITool.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
