// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package document

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var createTextCmdMeta = []flagutil.FlagMeta{
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-alias", Shorthand: "e", FieldPath: "EnvironmentAlias", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "max-chunk-size", FieldPath: "MaxChunkSize", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: string | number)"}},
	{FlagName: "overwrite", FieldPath: "Overwrite", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_overwrite_enum)"}},
	{FlagName: "markdown-conversion", FieldPath: "MarkdownConversion", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_markdownConversion_enum)"}},
	{FlagName: "llm-based-chunks", FieldPath: "LlmBasedChunks", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_llmBasedChunks_enum)"}},
	{FlagName: "llm-generated-q", FieldPath: "LlmGeneratedQ", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_llmGeneratedQ_enum)"}},
	{FlagName: "llm-content-summarization", FieldPath: "LlmContentSummarization", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_llmContentSummarization_enum)"}},
	{FlagName: "llm-prepend-context", FieldPath: "LlmPrependContext", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, Optional: true, TypeDescription: "JSON value (one of: boolean | StableDocumentController_createText_llmPrependContext_enum)"}},
	{FlagName: "url", Shorthand: "u", FieldPath: "Body.URL", Kind: flagutil.FlagKindString, Optional: true, Description: "An optional source URL to associate with the uploaded document."},
	{FlagName: "can-edit", Shorthand: "c", FieldPath: "Body.CanEdit", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "If true, the document content can be edited in the Creator after upload."},
	{FlagName: "metadata", FieldPath: "Body.Metadata", Kind: flagutil.FlagKindString, Optional: true, Description: "A JSON-encoded array of `{ key, values }` metadata tags attached to the document, used to filter knowledge base retrieval at runtime."},
}

// initCreateTextCmd initializes the create-text command.
func initCreateTextCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-text",
		Short:   "Create text document",
		Long:    "Create a new document from raw text.",
		Example: "  vf document create-text --project-id <id> --environment-alias <value>",
		RunE:    runCreateTextCmd,
		Aliases: []string{"cte"},
	}
	flagutil.RegisterFlags(cmd, createTextCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableDocumentControllerCreateTextRequest](createTextCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-text: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runCreateTextCmd executes the create-text command.
func runCreateTextCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createTextCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createTextCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableDocumentControllerCreateTextRequest](cmd, createTextCmdMeta, "Body", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Document.CreateText(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
