// This file is not generated by Speakeasy. It adds `vf link` and `vf unlink`,
// which pin a project and environment to a directory, and the hook that fills
// --project-id, --environment-alias and --workspace-id from that link for
// every other command. See internal/link.

package cli

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/link"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/sdk/models/sdkerrors"
)

// initLinkCmd registers `vf link` and `vf unlink`.
func initLinkCmd(parent *cobra.Command) {
	linkCmd := &cobra.Command{
		Use:   "link <project-id>",
		Short: "Pin a project and environment to this directory",
		Long: `Pin a Voiceflow project and environment to the current directory.

Every vf command run here, or in any directory below, then uses them by
default, so --project-id and --environment-alias can be left out. An explicit
flag always wins. Deleting a project, environment or workspace always needs
its flag: a link never fills in what a delete destroys.

The link is .voiceflow/project.json. It holds ids, the project name and the
environment alias — nothing secret. Remove it with 'vf unlink'.

The project id is in Creator under the agent's Settings → General (Metadata).
A Creator page URL will not do: the id in it is a version id.`,
		Example: `  vf link 6a67842584dac97c7626ebaa
  vf link 6a67842584dac97c7626ebaa --environment-alias dev`,
		Args: cobra.ExactArgs(1),
		// vf link decides the defaults; it must not receive the old ones.
		Annotations: map[string]string{link.SkipDefaultsAnnotation: "true"},
		RunE:        runLinkCmd,
	}
	linkCmd.Flags().StringP("environment-alias", "e", link.DefaultEnvironmentAlias, "Environment to link")
	parent.AddCommand(linkCmd)

	parent.AddCommand(&cobra.Command{
		Use:   "unlink",
		Short: "Remove the project link that applies to this directory",
		Long: `Remove the .voiceflow/project.json that applies to the current directory —
the one here, or the nearest one above. Commands then need --project-id and
--environment-alias again.`,
		Args: cobra.NoArgs,
		RunE: runUnlinkCmd,
	})
}

// linkResult wraps the summary for output.Result, which renders the first
// field of the value it is given.
type linkResult struct {
	Link linkSummary `json:"link"`
}

type linkSummary struct {
	ProjectID         string `json:"projectID"`
	ProjectName       string `json:"projectName"`
	WorkspaceID       string `json:"workspaceID"`
	EnvironmentAlias  string `json:"environmentAlias"`
	File              string `json:"file"`
	ReplacedProjectID string `json:"replacedProjectID,omitempty"`
	AgentInstructions string `json:"agentInstructions"`
}

func runLinkCmd(cmd *cobra.Command, args []string) error {
	projectID, err := link.ParseProjectID(args[0])
	if err != nil {
		return linkError(cmd, "invalid_project_id", err.Error(),
			"Copy the Project ID from the agent's Settings → General (Metadata) in Creator",
			"Or list the projects in a workspace: vf project list --workspace-id <id>")
	}
	alias, _ := cmd.Flags().GetString("environment-alias")
	alias = strings.TrimSpace(alias)
	if alias == "" {
		alias = link.DefaultEnvironmentAlias
	}

	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	dryRun := client.IsDryRun(cmd)
	if dryRun {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}

	projectRes, err := s.Project.Get(cmd.Context(), operations.StableProjectControllerGetRequest{ProjectID: projectID}, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}
	_, err = s.Environment.Get(cmd.Context(), operations.StableEnvironmentControllerGetRequest{
		EnvironmentAlias: alias,
		ProjectID:        projectID,
	}, sdkOpts...)
	if err != nil {
		if statusCode(err) == http.StatusNotFound {
			return environmentNotFound(cmd, s.Environment, projectID, alias, sdkOpts)
		}
		return output.Error(cmd, err)
	}

	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("find the current directory: %w", err)
	}
	linkPath := filepath.Join(cwd, link.DirName, link.FileName)
	if dryRun {
		fmt.Fprintf(cmd.ErrOrStderr(), "[DRY-RUN] Would write %s\n", linkPath)
		return nil
	}
	if projectRes == nil || projectRes.StableProjectResponse == nil {
		return errors.New("the project lookup returned no project")
	}
	project := projectRes.StableProjectResponse.Project

	// Only a link in this very directory is replaced; one further up is
	// merely shadowed, and stays in force for its other subdirectories.
	var replaced string
	if previous, err := link.Read(linkPath); err == nil && previous.ProjectID != project.ID {
		replaced = previous.ProjectID
	}

	saved := link.Link{
		ProjectID:        project.ID,
		ProjectName:      project.Name,
		WorkspaceID:      project.WorkspaceID,
		EnvironmentAlias: alias,
		LinkedAt:         time.Now().UTC().Truncate(time.Second),
	}
	path, err := link.Save(cwd, saved)
	if err != nil {
		return err
	}

	summary := linkSummary{
		ProjectID:         saved.ProjectID,
		ProjectName:       saved.ProjectName,
		WorkspaceID:       saved.WorkspaceID,
		EnvironmentAlias:  saved.EnvironmentAlias,
		File:              path,
		ReplacedProjectID: replaced,
		AgentInstructions: agentInstructions(saved),
	}
	if !wantsPlainText(cmd) {
		return output.Result(cmd, linkResult{Link: summary})
	}

	out := cmd.OutOrStdout()
	fmt.Fprintf(out, "Linked this directory to %q (%s), environment %q.\n", saved.ProjectName, saved.ProjectID, saved.EnvironmentAlias)
	if replaced != "" {
		fmt.Fprintf(out, "This replaces the link to project %s.\n", replaced)
	}
	fmt.Fprintln(out, "vf commands run here, or in any directory below, now use it by default.")
	fmt.Fprintf(out, "Link file: %s   (undo: vf unlink)\n\n", path)
	fmt.Fprintln(out, "For AI coding agents, add this to your agent instructions file (CLAUDE.md, AGENTS.md):")
	fmt.Fprintln(out)
	for _, line := range strings.Split(summary.AgentInstructions, "\n") {
		fmt.Fprintf(out, "  %s\n", line)
	}
	return nil
}

// agentInstructions is the snippet `vf link` prints for an agent's
// instructions file: what is linked, and the two rules agents otherwise learn
// by getting them wrong.
func agentInstructions(l link.Link) string {
	return fmt.Sprintf(`This directory is linked to the Voiceflow project %q (%s), environment %q. vf commands run here use them by default, so leave out --project-id and --environment-alias.
- Changes take effect only after 'vf environment compile'. Test the draft with --version-param draft.
- Publishing ('vf environment publish') ships to real users. Ask before running it.`,
		l.ProjectName, l.ProjectID, l.EnvironmentAlias)
}

// environmentNotFound turns a 404 on the environment into an error that
// lists the aliases the project does have.
func environmentNotFound(cmd *cobra.Command, envs *sdk.Environment, projectID, alias string, sdkOpts []operations.Option) error {
	hint := "List them with: vf environment list --project-id " + projectID
	if res, err := envs.List(cmd.Context(), operations.StableEnvironmentControllerListRequest{ProjectID: projectID}, sdkOpts...); err == nil &&
		res != nil && res.StableEnvironmentListResponse != nil {
		var aliases []string
		for _, env := range res.StableEnvironmentListResponse.Environments {
			aliases = append(aliases, env.Alias)
		}
		if len(aliases) > 0 {
			hint = "This project's environments: " + strings.Join(aliases, ", ")
		}
	}
	return linkError(cmd, "environment_not_found",
		fmt.Sprintf("project %s has no environment %q", projectID, alias),
		hint, "Pick one with: vf link "+projectID+" --environment-alias <alias>")
}

func runUnlinkCmd(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("find the current directory: %w", err)
	}
	path, err := link.Locate(cwd)
	if err != nil {
		return err
	}
	if path == "" {
		if !wantsPlainText(cmd) {
			return output.Result(cmd, unlinkResult{Unlink: unlinkSummary{}})
		}
		fmt.Fprintln(cmd.OutOrStdout(), "Nothing to unlink: no .voiceflow/project.json here or in any directory above.")
		return nil
	}

	// Read what is being removed for the message; a damaged link is still removed.
	previous, _ := link.Read(path)
	if err := link.Remove(path); err != nil {
		return err
	}

	summary := unlinkSummary{Removed: true, File: path}
	if previous != nil {
		summary.ProjectID, summary.ProjectName = previous.ProjectID, previous.ProjectName
	}
	if !wantsPlainText(cmd) {
		return output.Result(cmd, unlinkResult{Unlink: summary})
	}
	if previous != nil {
		fmt.Fprintf(cmd.OutOrStdout(), "Unlinked %q (%s). Removed %s\n", previous.ProjectName, previous.ProjectID, path)
	} else {
		fmt.Fprintf(cmd.OutOrStdout(), "Removed %s\n", path)
	}
	return nil
}

type unlinkResult struct {
	Unlink unlinkSummary `json:"unlink"`
}

type unlinkSummary struct {
	Removed     bool   `json:"removed"`
	ProjectID   string `json:"projectID,omitempty"`
	ProjectName string `json:"projectName,omitempty"`
	File        string `json:"file,omitempty"`
}

// applyLinkDefaults fills --project-id, --environment-alias and
// --workspace-id from the link that applies to the working directory, for
// every command that takes them and was not given them.
func applyLinkDefaults(cmd *cobra.Command) error {
	cwd, err := os.Getwd()
	if err != nil {
		// No working directory means no link; commands behave as they always have.
		return nil
	}
	found, err := link.ApplyDefaults(cmd, cwd)
	if err != nil {
		return linkError(cmd, "invalid_link", err.Error(),
			"Fix the file, or remove it with: vf unlink",
			"Or pass --project-id and --environment-alias explicitly")
	}
	if found != nil {
		if debug, _ := flagutil.GetBoolFlag(cmd, "debug"); debug {
			fmt.Fprintf(cmd.ErrOrStderr(), "[DEBUG] Linked project %s, environment %q (from %s)\n",
				found.ProjectID, found.EnvironmentAlias, found.Path)
		}
	}
	return nil
}

// writeLinkStatus prints the link block of 'vf whoami'.
func writeLinkStatus(w io.Writer) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Linked project:")
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(w, "  unknown (the current directory cannot be read)")
		return
	}
	path, err := link.Locate(cwd)
	if err != nil {
		fmt.Fprintf(w, "  unknown (%v)\n", err)
		return
	}
	if path == "" {
		fmt.Fprintln(w, "  none (run 'vf link <project-id>')")
		return
	}
	l, err := link.Read(path)
	if err != nil {
		fmt.Fprintf(w, "  unreadable: %v\n", err)
		return
	}
	fmt.Fprintf(w, "  %-12s %s (%s)\n", "project", l.ProjectName, l.ProjectID)
	fmt.Fprintf(w, "  %-12s %s\n", "environment", l.EnvironmentAlias)
	if l.WorkspaceID != "" {
		fmt.Fprintf(w, "  %-12s %s\n", "workspace", l.WorkspaceID)
	}
	fmt.Fprintf(w, "  %-12s %s\n", "file", path)
}

// wantsPlainText reports whether a hand-written command should print its own
// human-readable text rather than a structured result.
func wantsPlainText(cmd *cobra.Command) bool {
	if jq, _ := flagutil.GetStringFlag(cmd, "jq"); jq != "" {
		return false
	}
	return output.Format(cmd) == "pretty"
}

// linkError reports a failure the way the rest of the CLI does: a structured
// envelope in agent mode, and the message plus its fixes otherwise.
func linkError(cmd *cobra.Command, errorType, message string, hints ...string) error {
	if output.IsAgentMode() {
		return output.AgentModeError(cmd, errorType, message, hints)
	}
	var b strings.Builder
	b.WriteString(message)
	for _, h := range hints {
		b.WriteString("\n  → ")
		b.WriteString(h)
	}
	return errors.New(b.String())
}

// statusCode extracts the HTTP status from an SDK error, or 0.
func statusCode(err error) int {
	var apiErr *sdkerrors.SDKDefaultError
	if errors.As(err, &apiErr) {
		return apiErr.StatusCode
	}
	return 0
}
