// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 59fda2adb131

package project

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/components"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "name", Shorthand: "n", FieldPath: "Name", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "workspace-id", Shorthand: "w", FieldPath: "WorkspaceID", Kind: flagutil.FlagKindString, Required: true, Description: "The ID of the workspace the project belongs to. [required]"},
	{FlagName: "type", Shorthand: "t", FieldPath: "Type", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"webchat", "phone-call"}, Description: "The channel type of the project to create. (options: webchat, phone-call) [required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create project",
		Long:    "Create a new project.",
		Example: "  vf project create --name <value> --workspace-id <id> --type phone-call",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[components.StableProjectCreateRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.StableProjectCreateRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Project.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
