// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3deebed82876

package query

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var objectiveMetricsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "end-date", FieldPath: "Body.EndDate", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "start-date", Shorthand: "s", FieldPath: "Body.StartDate", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "timezone", Shorthand: "t", FieldPath: "Body.Timezone", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "interfaces", Shorthand: "i", FieldPath: "Body.Interfaces", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "The channels to filter results by. Defaults to all channels."},
	{FlagName: "environment-alias", FieldPath: "Body.EnvironmentAlias", Kind: flagutil.FlagKindString, Optional: true, Description: "The ID or alias of the environment to filter results by. Defaults to all environments."},
}

// initObjectiveMetricsCmd initializes the objective-metrics command.
func initObjectiveMetricsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "objective-metrics",
		Short:   "Query objective metrics",
		Long:    "Query the metric for the assistant's configured objective over a date range.",
		Example: "  vf query objective-metrics --project-id <id> --end-date <value> --start-date <value>",
		RunE:    runObjectiveMetricsCmd,
		Aliases: []string{"om"},
	}
	flagutil.RegisterFlags(cmd, objectiveMetricsCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableAnalyticsControllerQueryObjectiveMetricsRequest](objectiveMetricsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for objective-metrics: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runObjectiveMetricsCmd executes the objective-metrics command.
func runObjectiveMetricsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, objectiveMetricsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, objectiveMetricsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableAnalyticsControllerQueryObjectiveMetricsRequest](cmd, objectiveMetricsCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Analytics.Query.ObjectiveMetrics(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
