// This file is not generated by Speakeasy — it stops errors that have already
// been written to stderr from being written to stderr a second time.
//
// The problem it solves: every error printer in this package prints AND returns
// the error, and cmd/vf/main.go then prints whatever Execute returns. So a
// single failure reaches stderr twice:
//
//	CLAUDECODE=1 vf configure
//	{ "error": "…", "error_type": "configure_blocked", "hints": [ … ] }
//	the 'configure' command is interactive and cannot be used in agent mode
//
// AgentModeError's own documentation states the contract this violates —
// "outputs structured JSON exactly once to stderr… Callers must NOT print the
// error again" — but main.go is generated and prints unconditionally, so the
// contract was never actually kept.
//
// This matters most in agent mode, where the envelope is the machine-readable
// product. A trailing non-JSON line after a JSON object is exactly what breaks
// a naive parser, and this CLI's whole purpose is being driven by agents.
//
// Human (pretty) output is deliberately left alone. There the trailing line is
// the readable one-line summary that follows a raw API body, so suppressing it
// would remove the most useful part of the message rather than a duplicate.

package output

// alreadyReported marks an error whose message has been written to stderr by
// the code that produced it.
//
// Error returns the empty string, which is what actually suppresses the second
// print: main.go skips errors with an empty message. The alternative — exporting
// a predicate for main.go to call — does not work, because main.go imports only
// internal/cli and cannot see this package.
//
// The wrapped error is preserved through Unwrap, so errors.Is and errors.As
// continue to work on anything a caller wants to inspect.
//
// The cost of this design, stated plainly: any future code that formats one of
// these errors with %v or err.Error() renders nothing. That is contained today
// because exactly one place formats them — main.go — and it is guarded. Anything
// that needs the text must call Unwrap first.
type alreadyReported struct{ err error }

func (e alreadyReported) Error() string { return "" }
func (e alreadyReported) Unwrap() error { return e.err }

// AlreadyReported marks err as having been printed, so the process exits
// non-zero without repeating the message. Returns nil for nil so it is safe to
// wrap a return value directly.
func AlreadyReported(err error) error {
	if err == nil {
		return nil
	}
	return alreadyReported{err: err}
}
