workflowVersion: 1.0.0
speakeasyVersion: 1.796.2
sources:
    Voiceflow:
        inputs:
            - location: ./openapi.stable.json
        transformations:
            - filterOperations:
                operations: StableEnvironmentController_export
                exclude: true
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/voiceflow/engineering/cli
targets:
    voiceflow-sdk:
        target: cli
        source: Voiceflow
