// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package analytics

import (
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/usage"
)

func InitAnalyticsRoot(parent *cobra.Command) error {
	var AnalyticsCmd = &cobra.Command{
		Use:   "analytics",
		Short: "Operations for analytics",
		Long:  "Operations for analytics",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initQueryCallCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryCallDurationCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryWorkspaceTranscriptCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryProjectTranscriptCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryProjectTranscriptCostCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryWorkspaceInteractionCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryProjectInteractionCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryOrganizationTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryWorkspaceTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryProjectTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryHourlyOrganizationTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryHourlyProjectTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryDailyTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryEntityTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryCategoryTokenUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryPlaybookUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryWorkflowUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryPromptUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryIntentUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryFunctionUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryApiToolUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryMcpToolUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryKnowledgeBaseDocumentUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryIntegrationUsageCmd(AnalyticsCmd); err != nil {
		return err
	}

	if err := initQueryUniqueUserCountCmd(AnalyticsCmd); err != nil {
		return err
	}

	parent.AddCommand(AnalyticsCmd)
	return nil
}
