// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package agent

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "project-id", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-alias", FieldPath: "EnvironmentAlias", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "prompt", FieldPath: "Body.Prompt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"prompt,omitempty"`, Description: "list of values"},
	{FlagName: "end-tool", FieldPath: "Body.EndTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"endTool,omitempty"`, Description: "JSON object"},
	{FlagName: "card-tool", FieldPath: "Body.CardTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"cardTool,omitempty"`, Description: "JSON object"},
	{FlagName: "playbooks", FieldPath: "Body.Playbooks", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"playbooks,omitempty"`, Description: "Playbooks available for the agent to invoke."},
	{FlagName: "workflows", FieldPath: "Body.Workflows", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"workflows,omitempty"`, Description: "Workflows available for the agent to invoke."},
	{FlagName: "button-tool", Shorthand: "b", FieldPath: "Body.ButtonTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"buttonTool,omitempty"`, Description: "JSON object"},
	{FlagName: "carousel-tool", FieldPath: "Body.CarouselTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"carouselTool,omitempty"`, Description: "JSON object"},
	{FlagName: "instructions", FieldPath: "Body.Instructions", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"instructions,omitempty"`, Description: "list of values"},
	{FlagName: "skip-turn-tool", Shorthand: "s", FieldPath: "Body.SkipTurnTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"skipTurnTool,omitempty"`, Description: "JSON object"},
	{FlagName: "path-tool-order", FieldPath: "Body.PathToolOrder", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "The ordered list of path tool IDs that controls the order of the agent exit paths."},
	{FlagName: "web-search-tool", FieldPath: "Body.WebSearchTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"webSearchTool,omitempty"`, Description: "JSON object"},
	{FlagName: "call-forward-tool", FieldPath: "Body.CallForwardTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"callForwardTool,omitempty"`, Description: "JSON object"},
	{FlagName: "knowledge-base-tool", Shorthand: "k", FieldPath: "Body.KnowledgeBaseTool", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"knowledgeBaseTool,omitempty"`, Description: "JSON object"},
	{FlagName: "include-guidelines", FieldPath: "Body.IncludeGuidelines", Kind: flagutil.FlagKindBool, Optional: true, Description: "Whether to append the default prompting guidelines to the global prompt."},
	{FlagName: "llm", Shorthand: "l", FieldPath: "Body.Llm", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"llm,omitempty"`, Description: "JSON object"},
	{FlagName: "voice", Shorthand: "v", FieldPath: "Body.Voice", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"voice,omitempty"`, Description: "JSON object"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update agent",
		Long:    "Update agent configuration.",
		Example: "  vf agent update --project-id <id> --environment-alias <value>",
		RunE:    runUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableAgentControllerUpdateRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableAgentControllerUpdateRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Agent.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
