// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package mcpserver

import (
	"fmt"
	"github.com/spf13/cobra"
	"github.com/voiceflow/cli/internal/client"
	"github.com/voiceflow/cli/internal/flagutil"
	"github.com/voiceflow/cli/internal/interactive"
	"github.com/voiceflow/cli/internal/output"
	"github.com/voiceflow/cli/internal/sdk"
	"github.com/voiceflow/cli/internal/sdk/models/operations"
	"github.com/voiceflow/cli/internal/usage"
)

var syncCmdMeta = []flagutil.FlagMeta{
	{FlagName: "server-id", Shorthand: "s", FieldPath: "ServerID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "project-id", Shorthand: "p", FieldPath: "ProjectID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "environment-alias", Shorthand: "e", FieldPath: "EnvironmentAlias", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initSyncCmd initializes the sync command.
func initSyncCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "sync",
		Short:   "Sync MCP server",
		Long:    "Sync tool changes for an MCP server by ID.",
		Example: "  vf mcp-server sync --server-id <id> --project-id <id> --environment-alias <value>",
		RunE:    runSyncCmd,
	}
	flagutil.RegisterFlags(cmd, syncCmdMeta)
	if err := flagutil.ValidateMeta[operations.StableMCPServerControllerSyncRequest](syncCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for sync: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runSyncCmd executes the sync command.
func runSyncCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, syncCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, syncCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.StableMCPServerControllerSyncRequest](cmd, syncCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.McpServer.Sync(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
