// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type AssemblyAISTTSettingsProvider string

const (
	AssemblyAISTTSettingsProviderAssemblyai AssemblyAISTTSettingsProvider = "assemblyai"
)

func (e AssemblyAISTTSettingsProvider) ToPointer() *AssemblyAISTTSettingsProvider {
	return &e
}
func (e *AssemblyAISTTSettingsProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "assemblyai":
		*e = AssemblyAISTTSettingsProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AssemblyAISTTSettingsProvider: %v", v)
	}
}

type AssemblyAISTTSettings struct {
	Provider            AssemblyAISTTSettingsProvider `json:"provider"`
	Model               *AssemblyAISTTModel           `json:"model,omitzero"`
	Mode                *AssemblyAISTTMode            `json:"mode,omitzero"`
	Language            *AssemblyAISTTLanguage        `json:"language,omitzero"`
	Keyterms            *string                       `json:"keyterms,omitzero"`
	ConfidenceThreshold *float64                      `default:"0.7" json:"confidenceThreshold"`
	MaxTurnSilence      *float64                      `default:"2400" json:"maxTurnSilence"`
	MinTurnSilence      *float64                      `default:"160" json:"minTurnSilence"`
}

func (a AssemblyAISTTSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AssemblyAISTTSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AssemblyAISTTSettings) GetProvider() AssemblyAISTTSettingsProvider {
	if a == nil {
		return AssemblyAISTTSettingsProvider("")
	}
	return a.Provider
}

func (a *AssemblyAISTTSettings) GetModel() *AssemblyAISTTModel {
	if a == nil {
		return nil
	}
	return a.Model
}

func (a *AssemblyAISTTSettings) GetMode() *AssemblyAISTTMode {
	if a == nil {
		return nil
	}
	return a.Mode
}

func (a *AssemblyAISTTSettings) GetLanguage() *AssemblyAISTTLanguage {
	if a == nil {
		return nil
	}
	return a.Language
}

func (a *AssemblyAISTTSettings) GetKeyterms() *string {
	if a == nil {
		return nil
	}
	return a.Keyterms
}

func (a *AssemblyAISTTSettings) GetConfidenceThreshold() *float64 {
	if a == nil {
		return nil
	}
	return a.ConfidenceThreshold
}

func (a *AssemblyAISTTSettings) GetMaxTurnSilence() *float64 {
	if a == nil {
		return nil
	}
	return a.MaxTurnSilence
}

func (a *AssemblyAISTTSettings) GetMinTurnSilence() *float64 {
	if a == nil {
		return nil
	}
	return a.MinTurnSilence
}
