// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0b81fc71c7a0

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type AudioTraceType string

const (
	AudioTraceTypeAudio AudioTraceType = "audio"
)

func (e AudioTraceType) ToPointer() *AudioTraceType {
	return &e
}
func (e *AudioTraceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "audio":
		*e = AudioTraceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AudioTraceType: %v", v)
	}
}

type AudioTraceStateEnd string

const (
	AudioTraceStateEndEnd AudioTraceStateEnd = "end"
)

func (e AudioTraceStateEnd) ToPointer() *AudioTraceStateEnd {
	return &e
}
func (e *AudioTraceStateEnd) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "end":
		*e = AudioTraceStateEnd(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AudioTraceStateEnd: %v", v)
	}
}

type AudioTracePayloadEnd struct {
	State AudioTraceStateEnd `json:"state"`
}

func (a AudioTracePayloadEnd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioTracePayloadEnd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudioTracePayloadEnd) GetState() AudioTraceStateEnd {
	if a == nil {
		return AudioTraceStateEnd("")
	}
	return a.State
}

type AudioTraceStateContent string

const (
	AudioTraceStateContentContent AudioTraceStateContent = "content"
)

func (e AudioTraceStateContent) ToPointer() *AudioTraceStateContent {
	return &e
}
func (e *AudioTraceStateContent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "content":
		*e = AudioTraceStateContent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AudioTraceStateContent: %v", v)
	}
}

type AudioTracePayloadContent struct {
	State    AudioTraceStateContent `json:"state"`
	Content  string                 `json:"content"`
	Encoding AudioEncoding          `json:"encoding"`
	Duration *float64               `json:"duration,omitzero"`
}

func (a AudioTracePayloadContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioTracePayloadContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudioTracePayloadContent) GetState() AudioTraceStateContent {
	if a == nil {
		return AudioTraceStateContent("")
	}
	return a.State
}

func (a *AudioTracePayloadContent) GetContent() string {
	if a == nil {
		return ""
	}
	return a.Content
}

func (a *AudioTracePayloadContent) GetEncoding() AudioEncoding {
	if a == nil {
		return AudioEncoding("")
	}
	return a.Encoding
}

func (a *AudioTracePayloadContent) GetDuration() *float64 {
	if a == nil {
		return nil
	}
	return a.Duration
}

type AudioTraceStateStart string

const (
	AudioTraceStateStartStart AudioTraceStateStart = "start"
)

func (e AudioTraceStateStart) ToPointer() *AudioTraceStateStart {
	return &e
}
func (e *AudioTraceStateStart) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start":
		*e = AudioTraceStateStart(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AudioTraceStateStart: %v", v)
	}
}

type AudioTracePayloadStart struct {
	State     AudioTraceStateStart `json:"state"`
	MessageID string               `json:"messageID"`
	Delay     *float64             `json:"delay,omitzero"`
}

func (a AudioTracePayloadStart) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioTracePayloadStart) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudioTracePayloadStart) GetState() AudioTraceStateStart {
	if a == nil {
		return AudioTraceStateStart("")
	}
	return a.State
}

func (a *AudioTracePayloadStart) GetMessageID() string {
	if a == nil {
		return ""
	}
	return a.MessageID
}

func (a *AudioTracePayloadStart) GetDelay() *float64 {
	if a == nil {
		return nil
	}
	return a.Delay
}

type AudioTracePayloadUnionType string

const (
	AudioTracePayloadUnionTypeStart   AudioTracePayloadUnionType = "start"
	AudioTracePayloadUnionTypeContent AudioTracePayloadUnionType = "content"
	AudioTracePayloadUnionTypeEnd     AudioTracePayloadUnionType = "end"
	AudioTracePayloadUnionTypeUnknown AudioTracePayloadUnionType = "UNKNOWN"
)

type AudioTracePayloadUnion struct {
	AudioTracePayloadStart   *AudioTracePayloadStart   `queryParam:"inline" union:"member"`
	AudioTracePayloadContent *AudioTracePayloadContent `queryParam:"inline" union:"member"`
	AudioTracePayloadEnd     *AudioTracePayloadEnd     `queryParam:"inline" union:"member"`
	UnknownRaw               json.RawMessage           `json:"-" union:"unknown"`

	Type AudioTracePayloadUnionType
}

func CreateAudioTracePayloadUnionStart(start AudioTracePayloadStart) AudioTracePayloadUnion {
	typ := AudioTracePayloadUnionTypeStart

	typStr := AudioTraceStateStart(typ)
	start.State = typStr

	return AudioTracePayloadUnion{
		AudioTracePayloadStart: &start,
		Type:                   typ,
	}
}

func CreateAudioTracePayloadUnionContent(content AudioTracePayloadContent) AudioTracePayloadUnion {
	typ := AudioTracePayloadUnionTypeContent

	typStr := AudioTraceStateContent(typ)
	content.State = typStr

	return AudioTracePayloadUnion{
		AudioTracePayloadContent: &content,
		Type:                     typ,
	}
}

func CreateAudioTracePayloadUnionEnd(end AudioTracePayloadEnd) AudioTracePayloadUnion {
	typ := AudioTracePayloadUnionTypeEnd

	typStr := AudioTraceStateEnd(typ)
	end.State = typStr

	return AudioTracePayloadUnion{
		AudioTracePayloadEnd: &end,
		Type:                 typ,
	}
}

func CreateAudioTracePayloadUnionUnknown(raw json.RawMessage) AudioTracePayloadUnion {
	return AudioTracePayloadUnion{
		UnknownRaw: raw,
		Type:       AudioTracePayloadUnionTypeUnknown,
	}
}

func (u AudioTracePayloadUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u AudioTracePayloadUnion) IsUnknown() bool {
	return u.Type == AudioTracePayloadUnionTypeUnknown
}

func (u *AudioTracePayloadUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		State string `json:"state"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AudioTracePayloadUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AudioTracePayloadUnionTypeUnknown
		return nil
	}

	switch dis.State {
	case "start":
		audioTracePayloadStart := new(AudioTracePayloadStart)
		if err := utils.UnmarshalJSON(data, &audioTracePayloadStart, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == start) type AudioTracePayloadStart within AudioTracePayloadUnion: %w", string(data), err)
		}

		u.AudioTracePayloadStart = audioTracePayloadStart
		u.Type = AudioTracePayloadUnionTypeStart
		return nil
	case "content":
		audioTracePayloadContent := new(AudioTracePayloadContent)
		if err := utils.UnmarshalJSON(data, &audioTracePayloadContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == content) type AudioTracePayloadContent within AudioTracePayloadUnion: %w", string(data), err)
		}

		u.AudioTracePayloadContent = audioTracePayloadContent
		u.Type = AudioTracePayloadUnionTypeContent
		return nil
	case "end":
		audioTracePayloadEnd := new(AudioTracePayloadEnd)
		if err := utils.UnmarshalJSON(data, &audioTracePayloadEnd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == end) type AudioTracePayloadEnd within AudioTracePayloadUnion: %w", string(data), err)
		}

		u.AudioTracePayloadEnd = audioTracePayloadEnd
		u.Type = AudioTracePayloadUnionTypeEnd
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = AudioTracePayloadUnionTypeUnknown
		return nil
	}

}

func (u AudioTracePayloadUnion) MarshalJSON() ([]byte, error) {
	if u.AudioTracePayloadStart != nil {
		return utils.MarshalJSON(u.AudioTracePayloadStart, "", true)
	}

	if u.AudioTracePayloadContent != nil {
		return utils.MarshalJSON(u.AudioTracePayloadContent, "", true)
	}

	if u.AudioTracePayloadEnd != nil {
		return utils.MarshalJSON(u.AudioTracePayloadEnd, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type AudioTracePayloadUnion: all fields are null")
}

type AudioTrace struct {
	Type        AudioTraceType         `json:"type"`
	Paths       []TracePath            `json:"paths,omitzero"`
	DefaultPath *float64               `json:"defaultPath,omitzero"`
	Time        *float64               `json:"time,omitzero"`
	TurnID      *string                `json:"turnID,omitzero"`
	HandleID    *string                `json:"handleID,omitzero"`
	Payload     AudioTracePayloadUnion `json:"payload"`
}

func (a AudioTrace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AudioTrace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AudioTrace) GetType() AudioTraceType {
	if a == nil {
		return AudioTraceType("")
	}
	return a.Type
}

func (a *AudioTrace) GetPaths() []TracePath {
	if a == nil {
		return nil
	}
	return a.Paths
}

func (a *AudioTrace) GetDefaultPath() *float64 {
	if a == nil {
		return nil
	}
	return a.DefaultPath
}

func (a *AudioTrace) GetTime() *float64 {
	if a == nil {
		return nil
	}
	return a.Time
}

func (a *AudioTrace) GetTurnID() *string {
	if a == nil {
		return nil
	}
	return a.TurnID
}

func (a *AudioTrace) GetHandleID() *string {
	if a == nil {
		return nil
	}
	return a.HandleID
}

func (a *AudioTrace) GetPayload() AudioTracePayloadUnion {
	if a == nil {
		return AudioTracePayloadUnion{}
	}
	return a.Payload
}

func (a *AudioTrace) GetPayloadStart() *AudioTracePayloadStart {
	return a.GetPayload().AudioTracePayloadStart
}

func (a *AudioTrace) GetPayloadContent() *AudioTracePayloadContent {
	return a.GetPayload().AudioTracePayloadContent
}

func (a *AudioTrace) GetPayloadEnd() *AudioTracePayloadEnd {
	return a.GetPayload().AudioTracePayloadEnd
}
