// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 330c883a40f8

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type CallForwardSIPAddressType string

const (
	CallForwardSIPAddressTypeSip CallForwardSIPAddressType = "sip"
)

func (e CallForwardSIPAddressType) ToPointer() *CallForwardSIPAddressType {
	return &e
}
func (e *CallForwardSIPAddressType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sip":
		*e = CallForwardSIPAddressType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CallForwardSIPAddressType: %v", v)
	}
}

type CallForwardSIP struct {
	AddressType CallForwardSIPAddressType `json:"addressType"`
	Address     string                    `json:"address"`
}

func (c CallForwardSIP) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CallForwardSIP) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CallForwardSIP) GetAddressType() CallForwardSIPAddressType {
	if c == nil {
		return CallForwardSIPAddressType("")
	}
	return c.AddressType
}

func (c *CallForwardSIP) GetAddress() string {
	if c == nil {
		return ""
	}
	return c.Address
}
