// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5f01b28d6f35

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type DebugTraceMcpIntegrationToolRefType string

const (
	DebugTraceMcpIntegrationToolRefTypeMcpIntegrationTool DebugTraceMcpIntegrationToolRefType = "mcp-integration-tool"
)

func (e DebugTraceMcpIntegrationToolRefType) ToPointer() *DebugTraceMcpIntegrationToolRefType {
	return &e
}
func (e *DebugTraceMcpIntegrationToolRefType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "mcp-integration-tool":
		*e = DebugTraceMcpIntegrationToolRefType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DebugTraceMcpIntegrationToolRefType: %v", v)
	}
}

type DebugTraceMcpIntegrationToolRef struct {
	Type        DebugTraceMcpIntegrationToolRefType `json:"type"`
	NodeID      string                              `json:"nodeID"`
	DiagramID   string                              `json:"diagramID"`
	McpToolName string                              `json:"mcpToolName"`
	DiagramName *string                             `json:"diagramName,omitzero"`
}

func (d DebugTraceMcpIntegrationToolRef) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DebugTraceMcpIntegrationToolRef) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DebugTraceMcpIntegrationToolRef) GetType() DebugTraceMcpIntegrationToolRefType {
	if d == nil {
		return DebugTraceMcpIntegrationToolRefType("")
	}
	return d.Type
}

func (d *DebugTraceMcpIntegrationToolRef) GetNodeID() string {
	if d == nil {
		return ""
	}
	return d.NodeID
}

func (d *DebugTraceMcpIntegrationToolRef) GetDiagramID() string {
	if d == nil {
		return ""
	}
	return d.DiagramID
}

func (d *DebugTraceMcpIntegrationToolRef) GetMcpToolName() string {
	if d == nil {
		return ""
	}
	return d.McpToolName
}

func (d *DebugTraceMcpIntegrationToolRef) GetDiagramName() *string {
	if d == nil {
		return nil
	}
	return d.DiagramName
}
