// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/optionalnullable"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type KBDocumentDocxDataType string

const (
	KBDocumentDocxDataTypeDocx KBDocumentDocxDataType = "docx"
)

func (e KBDocumentDocxDataType) ToPointer() *KBDocumentDocxDataType {
	return &e
}
func (e *KBDocumentDocxDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "docx":
		*e = KBDocumentDocxDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KBDocumentDocxDataType: %v", v)
	}
}

type KBDocumentDocxData struct {
	Type KBDocumentDocxDataType                    `json:"type"`
	Name string                                    `json:"name"`
	URL  optionalnullable.OptionalNullable[string] `json:"url,omitzero"`
}

func (k KBDocumentDocxData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KBDocumentDocxData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KBDocumentDocxData) GetType() KBDocumentDocxDataType {
	if k == nil {
		return KBDocumentDocxDataType("")
	}
	return k.Type
}

func (k *KBDocumentDocxData) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KBDocumentDocxData) GetURL() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.URL
}
