// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/optionalnullable"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type KBDocumentTextDataType string

const (
	KBDocumentTextDataTypeText KBDocumentTextDataType = "text"
)

func (e KBDocumentTextDataType) ToPointer() *KBDocumentTextDataType {
	return &e
}
func (e *KBDocumentTextDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		*e = KBDocumentTextDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KBDocumentTextDataType: %v", v)
	}
}

type KBDocumentTextData struct {
	Type    KBDocumentTextDataType                    `json:"type"`
	Name    string                                    `json:"name"`
	CanEdit *bool                                     `json:"canEdit,omitzero"`
	URL     optionalnullable.OptionalNullable[string] `json:"url,omitzero"`
}

func (k KBDocumentTextData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KBDocumentTextData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (k *KBDocumentTextData) GetType() KBDocumentTextDataType {
	if k == nil {
		return KBDocumentTextDataType("")
	}
	return k.Type
}

func (k *KBDocumentTextData) GetName() string {
	if k == nil {
		return ""
	}
	return k.Name
}

func (k *KBDocumentTextData) GetCanEdit() *bool {
	if k == nil {
		return nil
	}
	return k.CanEdit
}

func (k *KBDocumentTextData) GetURL() optionalnullable.OptionalNullable[string] {
	if k == nil {
		return nil
	}
	return k.URL
}
