// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 750537eaf4e2

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// ObjectiveMetricsInterval - The bucket size of every `buckets` entry, derived from the requested range: hour up to a day, day up to 31 days, week up to 56 days, month beyond that.
type ObjectiveMetricsInterval string

const (
	ObjectiveMetricsIntervalHour  ObjectiveMetricsInterval = "hour"
	ObjectiveMetricsIntervalDay   ObjectiveMetricsInterval = "day"
	ObjectiveMetricsIntervalWeek  ObjectiveMetricsInterval = "week"
	ObjectiveMetricsIntervalMonth ObjectiveMetricsInterval = "month"
)

func (e ObjectiveMetricsInterval) ToPointer() *ObjectiveMetricsInterval {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ObjectiveMetricsInterval) IsExact() bool {
	if e != nil {
		switch *e {
		case "hour", "day", "week", "month":
			return true
		}
	}
	return false
}

type Bucket struct {
	Date              time.Time `json:"date"`
	MatchedSessions   float64   `json:"matchedSessions"`
	EvaluatedSessions float64   `json:"evaluatedSessions"`
}

func (b Bucket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(b, "", false)
}

func (b *Bucket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &b, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (b *Bucket) GetDate() time.Time {
	if b == nil {
		return time.Time{}
	}
	return b.Date
}

func (b *Bucket) GetMatchedSessions() float64 {
	if b == nil {
		return 0.0
	}
	return b.MatchedSessions
}

func (b *Bucket) GetEvaluatedSessions() float64 {
	if b == nil {
		return 0.0
	}
	return b.EvaluatedSessions
}

type ObjectiveMetrics struct {
	// Percentage (0-100) of evaluated sessions that met the objective, rounded to one decimal. Null when no session was evaluated; never report a null as 0%.
	Rate *float64 `json:"rate"`
	// Sessions that met the objective. The numerator of the rate.
	MatchedSessions float64 `json:"matchedSessions"`
	// Sessions evaluated against the objective. The denominator of the rate.
	EvaluatedSessions float64 `json:"evaluatedSessions"`
	// The bucket size of every `buckets` entry, derived from the requested range: hour up to a day, day up to 31 days, week up to 56 days, month beyond that.
	Interval ObjectiveMetricsInterval `json:"interval"`
	// Counts per `interval` bucket, not percentages. `date` is the start of the bucket. Divide within a bucket to get that bucket's rate.
	Buckets []Bucket `json:"buckets"`
}

func (o *ObjectiveMetrics) GetRate() *float64 {
	if o == nil {
		return nil
	}
	return o.Rate
}

func (o *ObjectiveMetrics) GetMatchedSessions() float64 {
	if o == nil {
		return 0.0
	}
	return o.MatchedSessions
}

func (o *ObjectiveMetrics) GetEvaluatedSessions() float64 {
	if o == nil {
		return 0.0
	}
	return o.EvaluatedSessions
}

func (o *ObjectiveMetrics) GetInterval() ObjectiveMetricsInterval {
	if o == nil {
		return ObjectiveMetricsInterval("")
	}
	return o.Interval
}

func (o *ObjectiveMetrics) GetBuckets() []Bucket {
	if o == nil {
		return []Bucket{}
	}
	return o.Buckets
}
