// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type ReasoningTraceType string

const (
	ReasoningTraceTypeReasoning ReasoningTraceType = "reasoning"
)

func (e ReasoningTraceType) ToPointer() *ReasoningTraceType {
	return &e
}
func (e *ReasoningTraceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "reasoning":
		*e = ReasoningTraceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningTraceType: %v", v)
	}
}

type StateFinal string

const (
	StateFinalFinal StateFinal = "final"
)

func (e StateFinal) ToPointer() *StateFinal {
	return &e
}
func (e *StateFinal) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "final":
		*e = StateFinal(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StateFinal: %v", v)
	}
}

type PayloadFinal struct {
	State   StateFinal `json:"state"`
	Message string     `json:"message"`
}

func (p PayloadFinal) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PayloadFinal) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (p *PayloadFinal) GetState() StateFinal {
	if p == nil {
		return StateFinal("")
	}
	return p.State
}

func (p *PayloadFinal) GetMessage() string {
	if p == nil {
		return ""
	}
	return p.Message
}

type ReasoningTraceStateEnd string

const (
	ReasoningTraceStateEndEnd ReasoningTraceStateEnd = "end"
)

func (e ReasoningTraceStateEnd) ToPointer() *ReasoningTraceStateEnd {
	return &e
}
func (e *ReasoningTraceStateEnd) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "end":
		*e = ReasoningTraceStateEnd(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningTraceStateEnd: %v", v)
	}
}

type ReasoningTracePayloadEnd struct {
	State ReasoningTraceStateEnd `json:"state"`
}

func (r ReasoningTracePayloadEnd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningTracePayloadEnd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningTracePayloadEnd) GetState() ReasoningTraceStateEnd {
	if r == nil {
		return ReasoningTraceStateEnd("")
	}
	return r.State
}

type ReasoningTraceStateContent string

const (
	ReasoningTraceStateContentContent ReasoningTraceStateContent = "content"
)

func (e ReasoningTraceStateContent) ToPointer() *ReasoningTraceStateContent {
	return &e
}
func (e *ReasoningTraceStateContent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "content":
		*e = ReasoningTraceStateContent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningTraceStateContent: %v", v)
	}
}

type ReasoningTracePayloadContent struct {
	State   ReasoningTraceStateContent `json:"state"`
	Content string                     `json:"content"`
}

func (r ReasoningTracePayloadContent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningTracePayloadContent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningTracePayloadContent) GetState() ReasoningTraceStateContent {
	if r == nil {
		return ReasoningTraceStateContent("")
	}
	return r.State
}

func (r *ReasoningTracePayloadContent) GetContent() string {
	if r == nil {
		return ""
	}
	return r.Content
}

type ReasoningTraceStateStart string

const (
	ReasoningTraceStateStartStart ReasoningTraceStateStart = "start"
)

func (e ReasoningTraceStateStart) ToPointer() *ReasoningTraceStateStart {
	return &e
}
func (e *ReasoningTraceStateStart) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start":
		*e = ReasoningTraceStateStart(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ReasoningTraceStateStart: %v", v)
	}
}

type ReasoningTracePayloadStart struct {
	State ReasoningTraceStateStart `json:"state"`
}

func (r ReasoningTracePayloadStart) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningTracePayloadStart) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningTracePayloadStart) GetState() ReasoningTraceStateStart {
	if r == nil {
		return ReasoningTraceStateStart("")
	}
	return r.State
}

type ReasoningTracePayloadUnionType string

const (
	ReasoningTracePayloadUnionTypeStart   ReasoningTracePayloadUnionType = "start"
	ReasoningTracePayloadUnionTypeContent ReasoningTracePayloadUnionType = "content"
	ReasoningTracePayloadUnionTypeEnd     ReasoningTracePayloadUnionType = "end"
	ReasoningTracePayloadUnionTypeFinal   ReasoningTracePayloadUnionType = "final"
	ReasoningTracePayloadUnionTypeUnknown ReasoningTracePayloadUnionType = "UNKNOWN"
)

type ReasoningTracePayloadUnion struct {
	ReasoningTracePayloadStart   *ReasoningTracePayloadStart   `queryParam:"inline" union:"member"`
	ReasoningTracePayloadContent *ReasoningTracePayloadContent `queryParam:"inline" union:"member"`
	ReasoningTracePayloadEnd     *ReasoningTracePayloadEnd     `queryParam:"inline" union:"member"`
	PayloadFinal                 *PayloadFinal                 `queryParam:"inline" union:"member"`
	UnknownRaw                   json.RawMessage               `json:"-" union:"unknown"`

	Type ReasoningTracePayloadUnionType
}

func CreateReasoningTracePayloadUnionStart(start ReasoningTracePayloadStart) ReasoningTracePayloadUnion {
	typ := ReasoningTracePayloadUnionTypeStart

	typStr := ReasoningTraceStateStart(typ)
	start.State = typStr

	return ReasoningTracePayloadUnion{
		ReasoningTracePayloadStart: &start,
		Type:                       typ,
	}
}

func CreateReasoningTracePayloadUnionContent(content ReasoningTracePayloadContent) ReasoningTracePayloadUnion {
	typ := ReasoningTracePayloadUnionTypeContent

	typStr := ReasoningTraceStateContent(typ)
	content.State = typStr

	return ReasoningTracePayloadUnion{
		ReasoningTracePayloadContent: &content,
		Type:                         typ,
	}
}

func CreateReasoningTracePayloadUnionEnd(end ReasoningTracePayloadEnd) ReasoningTracePayloadUnion {
	typ := ReasoningTracePayloadUnionTypeEnd

	typStr := ReasoningTraceStateEnd(typ)
	end.State = typStr

	return ReasoningTracePayloadUnion{
		ReasoningTracePayloadEnd: &end,
		Type:                     typ,
	}
}

func CreateReasoningTracePayloadUnionFinal(final PayloadFinal) ReasoningTracePayloadUnion {
	typ := ReasoningTracePayloadUnionTypeFinal

	typStr := StateFinal(typ)
	final.State = typStr

	return ReasoningTracePayloadUnion{
		PayloadFinal: &final,
		Type:         typ,
	}
}

func CreateReasoningTracePayloadUnionUnknown(raw json.RawMessage) ReasoningTracePayloadUnion {
	return ReasoningTracePayloadUnion{
		UnknownRaw: raw,
		Type:       ReasoningTracePayloadUnionTypeUnknown,
	}
}

func (u ReasoningTracePayloadUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ReasoningTracePayloadUnion) IsUnknown() bool {
	return u.Type == ReasoningTracePayloadUnionTypeUnknown
}

func (u *ReasoningTracePayloadUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		State string `json:"state"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ReasoningTracePayloadUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ReasoningTracePayloadUnionTypeUnknown
		return nil
	}

	switch dis.State {
	case "start":
		reasoningTracePayloadStart := new(ReasoningTracePayloadStart)
		if err := utils.UnmarshalJSON(data, &reasoningTracePayloadStart, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == start) type ReasoningTracePayloadStart within ReasoningTracePayloadUnion: %w", string(data), err)
		}

		u.ReasoningTracePayloadStart = reasoningTracePayloadStart
		u.Type = ReasoningTracePayloadUnionTypeStart
		return nil
	case "content":
		reasoningTracePayloadContent := new(ReasoningTracePayloadContent)
		if err := utils.UnmarshalJSON(data, &reasoningTracePayloadContent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == content) type ReasoningTracePayloadContent within ReasoningTracePayloadUnion: %w", string(data), err)
		}

		u.ReasoningTracePayloadContent = reasoningTracePayloadContent
		u.Type = ReasoningTracePayloadUnionTypeContent
		return nil
	case "end":
		reasoningTracePayloadEnd := new(ReasoningTracePayloadEnd)
		if err := utils.UnmarshalJSON(data, &reasoningTracePayloadEnd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == end) type ReasoningTracePayloadEnd within ReasoningTracePayloadUnion: %w", string(data), err)
		}

		u.ReasoningTracePayloadEnd = reasoningTracePayloadEnd
		u.Type = ReasoningTracePayloadUnionTypeEnd
		return nil
	case "final":
		payloadFinal := new(PayloadFinal)
		if err := utils.UnmarshalJSON(data, &payloadFinal, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == final) type PayloadFinal within ReasoningTracePayloadUnion: %w", string(data), err)
		}

		u.PayloadFinal = payloadFinal
		u.Type = ReasoningTracePayloadUnionTypeFinal
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ReasoningTracePayloadUnionTypeUnknown
		return nil
	}

}

func (u ReasoningTracePayloadUnion) MarshalJSON() ([]byte, error) {
	if u.ReasoningTracePayloadStart != nil {
		return utils.MarshalJSON(u.ReasoningTracePayloadStart, "", true)
	}

	if u.ReasoningTracePayloadContent != nil {
		return utils.MarshalJSON(u.ReasoningTracePayloadContent, "", true)
	}

	if u.ReasoningTracePayloadEnd != nil {
		return utils.MarshalJSON(u.ReasoningTracePayloadEnd, "", true)
	}

	if u.PayloadFinal != nil {
		return utils.MarshalJSON(u.PayloadFinal, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ReasoningTracePayloadUnion: all fields are null")
}

type ReasoningTrace struct {
	Type        ReasoningTraceType         `json:"type"`
	Paths       []TracePath                `json:"paths,omitzero"`
	DefaultPath *float64                   `json:"defaultPath,omitzero"`
	Time        *float64                   `json:"time,omitzero"`
	TurnID      *string                    `json:"turnID,omitzero"`
	HandleID    *string                    `json:"handleID,omitzero"`
	Payload     ReasoningTracePayloadUnion `json:"payload"`
}

func (r ReasoningTrace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReasoningTrace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReasoningTrace) GetType() ReasoningTraceType {
	if r == nil {
		return ReasoningTraceType("")
	}
	return r.Type
}

func (r *ReasoningTrace) GetPaths() []TracePath {
	if r == nil {
		return nil
	}
	return r.Paths
}

func (r *ReasoningTrace) GetDefaultPath() *float64 {
	if r == nil {
		return nil
	}
	return r.DefaultPath
}

func (r *ReasoningTrace) GetTime() *float64 {
	if r == nil {
		return nil
	}
	return r.Time
}

func (r *ReasoningTrace) GetTurnID() *string {
	if r == nil {
		return nil
	}
	return r.TurnID
}

func (r *ReasoningTrace) GetHandleID() *string {
	if r == nil {
		return nil
	}
	return r.HandleID
}

func (r *ReasoningTrace) GetPayload() ReasoningTracePayloadUnion {
	if r == nil {
		return ReasoningTracePayloadUnion{}
	}
	return r.Payload
}

func (r *ReasoningTrace) GetPayloadStart() *ReasoningTracePayloadStart {
	return r.GetPayload().ReasoningTracePayloadStart
}

func (r *ReasoningTrace) GetPayloadContent() *ReasoningTracePayloadContent {
	return r.GetPayload().ReasoningTracePayloadContent
}

func (r *ReasoningTrace) GetPayloadEnd() *ReasoningTracePayloadEnd {
	return r.GetPayload().ReasoningTracePayloadEnd
}

func (r *ReasoningTrace) GetPayloadFinal() *PayloadFinal {
	return r.GetPayload().PayloadFinal
}
