// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type SonioxSTTSettingsProvider string

const (
	SonioxSTTSettingsProviderSoniox SonioxSTTSettingsProvider = "soniox"
)

func (e SonioxSTTSettingsProvider) ToPointer() *SonioxSTTSettingsProvider {
	return &e
}
func (e *SonioxSTTSettingsProvider) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "soniox":
		*e = SonioxSTTSettingsProvider(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SonioxSTTSettingsProvider: %v", v)
	}
}

type SonioxSTTSettings struct {
	Provider            SonioxSTTSettingsProvider `json:"provider"`
	Model               SonioxSTTModel            `json:"model"`
	MaxEndpointDelayMS  *int64                    `json:"maxEndpointDelayMS,omitzero"`
	EndpointSensitivity *float64                  `json:"endpointSensitivity,omitzero"`
	Languages           []SonioxSTTLanguage       `json:"languages"`
}

func (s SonioxSTTSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SonioxSTTSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *SonioxSTTSettings) GetProvider() SonioxSTTSettingsProvider {
	if s == nil {
		return SonioxSTTSettingsProvider("")
	}
	return s.Provider
}

func (s *SonioxSTTSettings) GetModel() SonioxSTTModel {
	if s == nil {
		return SonioxSTTModel("")
	}
	return s.Model
}

func (s *SonioxSTTSettings) GetMaxEndpointDelayMS() *int64 {
	if s == nil {
		return nil
	}
	return s.MaxEndpointDelayMS
}

func (s *SonioxSTTSettings) GetEndpointSensitivity() *float64 {
	if s == nil {
		return nil
	}
	return s.EndpointSensitivity
}

func (s *SonioxSTTSettings) GetLanguages() []SonioxSTTLanguage {
	if s == nil {
		return []SonioxSTTLanguage{}
	}
	return s.Languages
}
