// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e828f8cdc76b

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/optionalnullable"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StablePlaybookCreateRequestV2EndToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2EndToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2EndToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2EndToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2EndToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2EndToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2EndToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2endtoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2endtoolgenerative

type StablePlaybookCreateRequestV2EndToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2EndToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                         `json:"delayMessageID"`
	FailureMessageID    *string                                         `json:"failureMessageID"`
	ExecutionMessageID  *string                                         `json:"executionMessageID"`
	CompletionMessageID *string                                         `json:"completionMessageID"`
	DelayMessageSeconds *float64                                        `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2EndToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetGenerative() *StablePlaybookCreateRequestV2EndToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2EndToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2endtoolmessages
// #endregion class-body-stableplaybookcreaterequestv2endtoolmessages

type StablePlaybookCreateRequestV2EndToolToolSound struct {
	Ref    *string  `json:"ref"`
	Volume *float64 `default:"0.75" json:"volume"`
}

func (s StablePlaybookCreateRequestV2EndToolToolSound) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2EndToolToolSound) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2EndToolToolSound) GetRef() *string {
	if s == nil {
		return nil
	}
	return s.Ref
}

func (s *StablePlaybookCreateRequestV2EndToolToolSound) GetVolume() *float64 {
	if s == nil {
		return nil
	}
	return s.Volume
}

// #region class-body-stableplaybookcreaterequestv2endtooltoolsound
// #endregion class-body-stableplaybookcreaterequestv2endtooltoolsound

type StablePlaybookCreateRequestV2EndTool struct {
	Enabled     bool                                                                             `json:"enabled"`
	Messages    optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndToolMessages]  `json:"messages,omitzero"`
	ToolSound   optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndToolToolSound] `json:"toolSound,omitzero"`
	Description string                                                                           `json:"description"`
}

func (s StablePlaybookCreateRequestV2EndTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2EndTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2EndTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2EndTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2EndTool) GetToolSound() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndToolToolSound] {
	if s == nil {
		return nil
	}
	return s.ToolSound
}

func (s *StablePlaybookCreateRequestV2EndTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

// #region class-body-stableplaybookcreaterequestv2endtool
// #endregion class-body-stableplaybookcreaterequestv2endtool

type StablePlaybookCreateRequestV2CardToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2CardToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CardToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CardToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2CardToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2CardToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2CardToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2cardtoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2cardtoolgenerative

type StablePlaybookCreateRequestV2CardToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2CardToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                          `json:"delayMessageID"`
	FailureMessageID    *string                                          `json:"failureMessageID"`
	ExecutionMessageID  *string                                          `json:"executionMessageID"`
	CompletionMessageID *string                                          `json:"completionMessageID"`
	DelayMessageSeconds *float64                                         `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2CardToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetGenerative() *StablePlaybookCreateRequestV2CardToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2CardToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2cardtoolmessages
// #endregion class-body-stableplaybookcreaterequestv2cardtoolmessages

type StablePlaybookCreateRequestV2CardTool struct {
	Enabled     bool                                                                             `json:"enabled"`
	Messages    optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CardToolMessages] `json:"messages,omitzero"`
	Description string                                                                           `json:"description"`
}

func (s StablePlaybookCreateRequestV2CardTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CardTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CardTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2CardTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CardToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2CardTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

// #region class-body-stableplaybookcreaterequestv2cardtool
// #endregion class-body-stableplaybookcreaterequestv2cardtool

type StablePlaybookCreateRequestV2ButtonToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2ButtonToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2ButtonToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2ButtonToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2ButtonToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2ButtonToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2ButtonToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2buttontoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2buttontoolgenerative

type StablePlaybookCreateRequestV2ButtonToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2ButtonToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                            `json:"delayMessageID"`
	FailureMessageID    *string                                            `json:"failureMessageID"`
	ExecutionMessageID  *string                                            `json:"executionMessageID"`
	CompletionMessageID *string                                            `json:"completionMessageID"`
	DelayMessageSeconds *float64                                           `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2ButtonToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetGenerative() *StablePlaybookCreateRequestV2ButtonToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2ButtonToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2buttontoolmessages
// #endregion class-body-stableplaybookcreaterequestv2buttontoolmessages

type StablePlaybookCreateRequestV2ButtonTool struct {
	Enabled     bool                                                                               `json:"enabled"`
	Messages    optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ButtonToolMessages] `json:"messages,omitzero"`
	Description string                                                                             `json:"description"`
}

func (s StablePlaybookCreateRequestV2ButtonTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2ButtonTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2ButtonTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2ButtonTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ButtonToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2ButtonTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

// #region class-body-stableplaybookcreaterequestv2buttontool
// #endregion class-body-stableplaybookcreaterequestv2buttontool

type StablePlaybookCreateRequestV2CarouselToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2CarouselToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CarouselToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CarouselToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2CarouselToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2CarouselToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2CarouselToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2carouseltoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2carouseltoolgenerative

type StablePlaybookCreateRequestV2CarouselToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2CarouselToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                              `json:"delayMessageID"`
	FailureMessageID    *string                                              `json:"failureMessageID"`
	ExecutionMessageID  *string                                              `json:"executionMessageID"`
	CompletionMessageID *string                                              `json:"completionMessageID"`
	DelayMessageSeconds *float64                                             `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2CarouselToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetGenerative() *StablePlaybookCreateRequestV2CarouselToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2CarouselToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2carouseltoolmessages
// #endregion class-body-stableplaybookcreaterequestv2carouseltoolmessages

type StablePlaybookCreateRequestV2CarouselTool struct {
	Enabled     bool                                                                                 `json:"enabled"`
	Messages    optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CarouselToolMessages] `json:"messages,omitzero"`
	Description string                                                                               `json:"description"`
}

func (s StablePlaybookCreateRequestV2CarouselTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CarouselTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CarouselTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2CarouselTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CarouselToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2CarouselTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

// #region class-body-stableplaybookcreaterequestv2carouseltool
// #endregion class-body-stableplaybookcreaterequestv2carouseltool

type StablePlaybookCreateRequestV2SkipTurnTool struct {
	Enabled     bool   `json:"enabled"`
	Description string `json:"description"`
}

func (s *StablePlaybookCreateRequestV2SkipTurnTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2SkipTurnTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

// #region class-body-stableplaybookcreaterequestv2skipturntool
// #endregion class-body-stableplaybookcreaterequestv2skipturntool

type StablePlaybookCreateRequestV2WebSearchToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2WebSearchToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2WebSearchToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2WebSearchToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2WebSearchToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2WebSearchToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2WebSearchToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2websearchtoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2websearchtoolgenerative

type StablePlaybookCreateRequestV2WebSearchToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2WebSearchToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                               `json:"delayMessageID"`
	FailureMessageID    *string                                               `json:"failureMessageID"`
	ExecutionMessageID  *string                                               `json:"executionMessageID"`
	CompletionMessageID *string                                               `json:"completionMessageID"`
	DelayMessageSeconds *float64                                              `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2WebSearchToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetGenerative() *StablePlaybookCreateRequestV2WebSearchToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2WebSearchToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2websearchtoolmessages
// #endregion class-body-stableplaybookcreaterequestv2websearchtoolmessages

type StablePlaybookCreateRequestV2WebSearchToolToolSound struct {
	Ref    *string  `json:"ref"`
	Volume *float64 `default:"0.75" json:"volume"`
}

func (s StablePlaybookCreateRequestV2WebSearchToolToolSound) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2WebSearchToolToolSound) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2WebSearchToolToolSound) GetRef() *string {
	if s == nil {
		return nil
	}
	return s.Ref
}

func (s *StablePlaybookCreateRequestV2WebSearchToolToolSound) GetVolume() *float64 {
	if s == nil {
		return nil
	}
	return s.Volume
}

// #region class-body-stableplaybookcreaterequestv2websearchtooltoolsound
// #endregion class-body-stableplaybookcreaterequestv2websearchtooltoolsound

type StablePlaybookCreateRequestV2WebSearchTool struct {
	Enabled         bool                                                                                   `json:"enabled"`
	Messages        optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchToolMessages]  `json:"messages,omitzero"`
	ToolSound       optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchToolToolSound] `json:"toolSound,omitzero"`
	Description     *string                                                                                `json:"description,omitzero"`
	AllowedDomains  optionalnullable.OptionalNullable[[]string]                                            `json:"allowedDomains,omitzero"`
	SourceUrlsCount optionalnullable.OptionalNullable[float64]                                             `json:"sourceUrlsCount,omitzero"`
}

func (s StablePlaybookCreateRequestV2WebSearchTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetToolSound() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchToolToolSound] {
	if s == nil {
		return nil
	}
	return s.ToolSound
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetAllowedDomains() optionalnullable.OptionalNullable[[]string] {
	if s == nil {
		return nil
	}
	return s.AllowedDomains
}

func (s *StablePlaybookCreateRequestV2WebSearchTool) GetSourceUrlsCount() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.SourceUrlsCount
}

// #region class-body-stableplaybookcreaterequestv2websearchtool
// #endregion class-body-stableplaybookcreaterequestv2websearchtool

type StablePlaybookCreateRequestV2CallForwardToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2CallForwardToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CallForwardToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CallForwardToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2CallForwardToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2CallForwardToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2CallForwardToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2callforwardtoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2callforwardtoolgenerative

type StablePlaybookCreateRequestV2CallForwardToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2CallForwardToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                                 `json:"delayMessageID"`
	FailureMessageID    *string                                                 `json:"failureMessageID"`
	ExecutionMessageID  *string                                                 `json:"executionMessageID"`
	CompletionMessageID *string                                                 `json:"completionMessageID"`
	DelayMessageSeconds *float64                                                `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2CallForwardToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetGenerative() *StablePlaybookCreateRequestV2CallForwardToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2CallForwardToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2callforwardtoolmessages
// #endregion class-body-stableplaybookcreaterequestv2callforwardtoolmessages

type StablePlaybookCreateRequestV2CallForwardToolToolSound struct {
	Ref    *string  `json:"ref"`
	Volume *float64 `default:"0.75" json:"volume"`
}

func (s StablePlaybookCreateRequestV2CallForwardToolToolSound) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CallForwardToolToolSound) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CallForwardToolToolSound) GetRef() *string {
	if s == nil {
		return nil
	}
	return s.Ref
}

func (s *StablePlaybookCreateRequestV2CallForwardToolToolSound) GetVolume() *float64 {
	if s == nil {
		return nil
	}
	return s.Volume
}

// #region class-body-stableplaybookcreaterequestv2callforwardtooltoolsound
// #endregion class-body-stableplaybookcreaterequestv2callforwardtooltoolsound

type StablePlaybookCreateRequestV2CallForwardTool struct {
	Enabled bool `json:"enabled"`
	// Plain text; markdown is not interpreted. {variable_name} inserts a variable or entity, {variable_name.path} a field of a variable. Escape a literal { or \ with a backslash. A name matching neither is stored as literal text and reported in unresolvedReferences; secrets are not available here.
	Address             string                                                                                   `json:"address"`
	Messages            optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardToolMessages]  `json:"messages,omitzero"`
	Extension           *string                                                                                  `json:"extension,omitzero"`
	ToolSound           optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardToolToolSound] `json:"toolSound,omitzero"`
	Description         string                                                                                   `json:"description"`
	AddressType         CallForwardAddressType                                                                   `json:"addressType"`
	CallerIDPassthrough *bool                                                                                    `json:"callerIDPassthrough,omitzero"`
}

func (s StablePlaybookCreateRequestV2CallForwardTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetAddress() string {
	if s == nil {
		return ""
	}
	return s.Address
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetExtension() *string {
	if s == nil {
		return nil
	}
	return s.Extension
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetToolSound() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardToolToolSound] {
	if s == nil {
		return nil
	}
	return s.ToolSound
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetAddressType() CallForwardAddressType {
	if s == nil {
		return CallForwardAddressType("")
	}
	return s.AddressType
}

func (s *StablePlaybookCreateRequestV2CallForwardTool) GetCallerIDPassthrough() *bool {
	if s == nil {
		return nil
	}
	return s.CallerIDPassthrough
}

// #region class-body-stableplaybookcreaterequestv2callforwardtool
// #endregion class-body-stableplaybookcreaterequestv2callforwardtool

type StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative struct {
	Execution  *StableToolMessageGenerative `json:"execution,omitzero"`
	Failure    *StableToolMessageGenerative `json:"failure,omitzero"`
	Delay      *StableToolMessageGenerative `json:"delay,omitzero"`
	Completion *StableToolMessageGenerative `json:"completion,omitzero"`
}

func (s StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) GetExecution() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Execution
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) GetFailure() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Failure
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) GetDelay() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Delay
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative) GetCompletion() *StableToolMessageGenerative {
	if s == nil {
		return nil
	}
	return s.Completion
}

// #region class-body-stableplaybookcreaterequestv2knowledgebasetoolgenerative
// #endregion class-body-stableplaybookcreaterequestv2knowledgebasetoolgenerative

type StablePlaybookCreateRequestV2KnowledgeBaseToolMessages struct {
	Generative          *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative `json:"generative,omitzero"`
	DelayMessageID      *string                                                   `json:"delayMessageID"`
	FailureMessageID    *string                                                   `json:"failureMessageID"`
	ExecutionMessageID  *string                                                   `json:"executionMessageID"`
	CompletionMessageID *string                                                   `json:"completionMessageID"`
	DelayMessageSeconds *float64                                                  `json:"delayMessageSeconds"`
}

func (s StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetGenerative() *StablePlaybookCreateRequestV2KnowledgeBaseToolGenerative {
	if s == nil {
		return nil
	}
	return s.Generative
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetDelayMessageID() *string {
	if s == nil {
		return nil
	}
	return s.DelayMessageID
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetFailureMessageID() *string {
	if s == nil {
		return nil
	}
	return s.FailureMessageID
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetExecutionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.ExecutionMessageID
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetCompletionMessageID() *string {
	if s == nil {
		return nil
	}
	return s.CompletionMessageID
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolMessages) GetDelayMessageSeconds() *float64 {
	if s == nil {
		return nil
	}
	return s.DelayMessageSeconds
}

// #region class-body-stableplaybookcreaterequestv2knowledgebasetoolmessages
// #endregion class-body-stableplaybookcreaterequestv2knowledgebasetoolmessages

type StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound struct {
	Ref    *string  `json:"ref"`
	Volume *float64 `default:"0.75" json:"volume"`
}

func (s StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound) GetRef() *string {
	if s == nil {
		return nil
	}
	return s.Ref
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound) GetVolume() *float64 {
	if s == nil {
		return nil
	}
	return s.Volume
}

// #region class-body-stableplaybookcreaterequestv2knowledgebasetooltoolsound
// #endregion class-body-stableplaybookcreaterequestv2knowledgebasetooltoolsound

type StablePlaybookCreateRequestV2KnowledgeBaseTool struct {
	Query           optionalnullable.OptionalNullable[string]                                                  `json:"query,omitzero"`
	Enabled         bool                                                                                       `json:"enabled"`
	Filters         []StableKBFilter                                                                           `json:"filters,omitzero"`
	Messages        optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseToolMessages]  `json:"messages,omitzero"`
	ToolSound       optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound] `json:"toolSound,omitzero"`
	ChunkLimit      optionalnullable.OptionalNullable[float64]                                                 `json:"chunkLimit,omitzero"`
	Description     string                                                                                     `json:"description"`
	QueryMode       *AgentKnowledgeBaseToolQueryMode                                                           `json:"queryMode,omitzero"`
	SourceUrlsCount optionalnullable.OptionalNullable[float64]                                                 `json:"sourceUrlsCount,omitzero"`
}

func (s StablePlaybookCreateRequestV2KnowledgeBaseTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetQuery() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Query
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetFilters() []StableKBFilter {
	if s == nil {
		return nil
	}
	return s.Filters
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetMessages() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseToolMessages] {
	if s == nil {
		return nil
	}
	return s.Messages
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetToolSound() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseToolToolSound] {
	if s == nil {
		return nil
	}
	return s.ToolSound
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetChunkLimit() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.ChunkLimit
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetDescription() string {
	if s == nil {
		return ""
	}
	return s.Description
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetQueryMode() *AgentKnowledgeBaseToolQueryMode {
	if s == nil {
		return nil
	}
	return s.QueryMode
}

func (s *StablePlaybookCreateRequestV2KnowledgeBaseTool) GetSourceUrlsCount() optionalnullable.OptionalNullable[float64] {
	if s == nil {
		return nil
	}
	return s.SourceUrlsCount
}

// #region class-body-stableplaybookcreaterequestv2knowledgebasetool
// #endregion class-body-stableplaybookcreaterequestv2knowledgebasetool

type StablePlaybookCreateRequestV2Realtime struct {
	Voice     *string `json:"voice,omitzero"`
	Eagerness *string `json:"eagerness,omitzero"`
}

func (s *StablePlaybookCreateRequestV2Realtime) GetVoice() *string {
	if s == nil {
		return nil
	}
	return s.Voice
}

func (s *StablePlaybookCreateRequestV2Realtime) GetEagerness() *string {
	if s == nil {
		return nil
	}
	return s.Eagerness
}

// #region class-body-stableplaybookcreaterequestv2realtime
// #endregion class-body-stableplaybookcreaterequestv2realtime

type StablePlaybookCreateRequestV2ReasoningEffort string

const (
	StablePlaybookCreateRequestV2ReasoningEffortOff      StablePlaybookCreateRequestV2ReasoningEffort = "off"
	StablePlaybookCreateRequestV2ReasoningEffortAdaptive StablePlaybookCreateRequestV2ReasoningEffort = "adaptive"
	StablePlaybookCreateRequestV2ReasoningEffortMinimal  StablePlaybookCreateRequestV2ReasoningEffort = "minimal"
	StablePlaybookCreateRequestV2ReasoningEffortLow      StablePlaybookCreateRequestV2ReasoningEffort = "low"
	StablePlaybookCreateRequestV2ReasoningEffortMedium   StablePlaybookCreateRequestV2ReasoningEffort = "medium"
	StablePlaybookCreateRequestV2ReasoningEffortHigh     StablePlaybookCreateRequestV2ReasoningEffort = "high"
)

func (e StablePlaybookCreateRequestV2ReasoningEffort) ToPointer() *StablePlaybookCreateRequestV2ReasoningEffort {
	return &e
}
func (e *StablePlaybookCreateRequestV2ReasoningEffort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "off":
		fallthrough
	case "adaptive":
		fallthrough
	case "minimal":
		fallthrough
	case "low":
		fallthrough
	case "medium":
		fallthrough
	case "high":
		*e = StablePlaybookCreateRequestV2ReasoningEffort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StablePlaybookCreateRequestV2ReasoningEffort: %v", v)
	}
}

type StablePlaybookCreateRequestV2Settings struct {
	Model           *AIModel                                                                        `json:"model,omitzero"`
	Realtime        *StablePlaybookCreateRequestV2Realtime                                          `json:"realtime,omitzero"`
	MaxTokens       *float64                                                                        `json:"maxTokens,omitzero"`
	Temperature     *float64                                                                        `json:"temperature,omitzero"`
	ReasoningEffort optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ReasoningEffort] `json:"reasoningEffort,omitzero"`
}

func (s StablePlaybookCreateRequestV2Settings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2Settings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2Settings) GetModel() *AIModel {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StablePlaybookCreateRequestV2Settings) GetRealtime() *StablePlaybookCreateRequestV2Realtime {
	if s == nil {
		return nil
	}
	return s.Realtime
}

func (s *StablePlaybookCreateRequestV2Settings) GetMaxTokens() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxTokens
}

func (s *StablePlaybookCreateRequestV2Settings) GetTemperature() *float64 {
	if s == nil {
		return nil
	}
	return s.Temperature
}

func (s *StablePlaybookCreateRequestV2Settings) GetReasoningEffort() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ReasoningEffort] {
	if s == nil {
		return nil
	}
	return s.ReasoningEffort
}

// #region class-body-stableplaybookcreaterequestv2settings
// #endregion class-body-stableplaybookcreaterequestv2settings

type StablePlaybookCreateRequestV2 struct {
	Name string `json:"name"`
	// A human-readable description of what the playbook does.
	Description       optionalnullable.OptionalNullable[string]                                         `json:"description,omitzero"`
	Instructions      optionalnullable.OptionalNullable[string]                                         `json:"instructions,omitzero"`
	EndTool           optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndTool]           `json:"endTool,omitzero"`
	CardTool          optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CardTool]          `json:"cardTool,omitzero"`
	ButtonTool        optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ButtonTool]        `json:"buttonTool,omitzero"`
	CarouselTool      optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CarouselTool]      `json:"carouselTool,omitzero"`
	SkipTurnTool      optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2SkipTurnTool]      `json:"skipTurnTool,omitzero"`
	WebSearchTool     optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchTool]     `json:"webSearchTool,omitzero"`
	CallForwardTool   optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardTool]   `json:"callForwardTool,omitzero"`
	KnowledgeBaseTool optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseTool] `json:"knowledgeBaseTool,omitzero"`
	Settings          *StablePlaybookCreateRequestV2Settings                                            `json:"settings,omitzero"`
}

func (s StablePlaybookCreateRequestV2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StablePlaybookCreateRequestV2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StablePlaybookCreateRequestV2) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StablePlaybookCreateRequestV2) GetDescription() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *StablePlaybookCreateRequestV2) GetInstructions() optionalnullable.OptionalNullable[string] {
	if s == nil {
		return nil
	}
	return s.Instructions
}

func (s *StablePlaybookCreateRequestV2) GetEndTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2EndTool] {
	if s == nil {
		return nil
	}
	return s.EndTool
}

func (s *StablePlaybookCreateRequestV2) GetCardTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CardTool] {
	if s == nil {
		return nil
	}
	return s.CardTool
}

func (s *StablePlaybookCreateRequestV2) GetButtonTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2ButtonTool] {
	if s == nil {
		return nil
	}
	return s.ButtonTool
}

func (s *StablePlaybookCreateRequestV2) GetCarouselTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CarouselTool] {
	if s == nil {
		return nil
	}
	return s.CarouselTool
}

func (s *StablePlaybookCreateRequestV2) GetSkipTurnTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2SkipTurnTool] {
	if s == nil {
		return nil
	}
	return s.SkipTurnTool
}

func (s *StablePlaybookCreateRequestV2) GetWebSearchTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2WebSearchTool] {
	if s == nil {
		return nil
	}
	return s.WebSearchTool
}

func (s *StablePlaybookCreateRequestV2) GetCallForwardTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2CallForwardTool] {
	if s == nil {
		return nil
	}
	return s.CallForwardTool
}

func (s *StablePlaybookCreateRequestV2) GetKnowledgeBaseTool() optionalnullable.OptionalNullable[StablePlaybookCreateRequestV2KnowledgeBaseTool] {
	if s == nil {
		return nil
	}
	return s.KnowledgeBaseTool
}

func (s *StablePlaybookCreateRequestV2) GetSettings() *StablePlaybookCreateRequestV2Settings {
	if s == nil {
		return nil
	}
	return s.Settings
}

// #region class-body-stableplaybookcreaterequestv2
// #endregion class-body-stableplaybookcreaterequestv2
