// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StableFunctionVariableListResponse struct {
	Variables []StableFunctionVariable `json:"variables"`
}

func (s *StableFunctionVariableListResponse) GetVariables() []StableFunctionVariable {
	if s == nil {
		return []StableFunctionVariable{}
	}
	return s.Variables
}
