// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ad8816ae2cce

package components

type StableTestRunCreateRequest struct {
	// The ID of the test to run.
	TestID string `json:"testID"`
}

func (s *StableTestRunCreateRequest) GetTestID() string {
	if s == nil {
		return ""
	}
	return s.TestID
}
