// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 761af050bea2

package components

import (
	"encoding/json"
	"fmt"
)

type StableAnalyticsQueryUniqueUserCountRequestInterval string

const (
	StableAnalyticsQueryUniqueUserCountRequestIntervalHour  StableAnalyticsQueryUniqueUserCountRequestInterval = "hour"
	StableAnalyticsQueryUniqueUserCountRequestIntervalDay   StableAnalyticsQueryUniqueUserCountRequestInterval = "day"
	StableAnalyticsQueryUniqueUserCountRequestIntervalWeek  StableAnalyticsQueryUniqueUserCountRequestInterval = "week"
	StableAnalyticsQueryUniqueUserCountRequestIntervalMonth StableAnalyticsQueryUniqueUserCountRequestInterval = "month"
)

func (e StableAnalyticsQueryUniqueUserCountRequestInterval) ToPointer() *StableAnalyticsQueryUniqueUserCountRequestInterval {
	return &e
}
func (e *StableAnalyticsQueryUniqueUserCountRequestInterval) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "hour":
		fallthrough
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		*e = StableAnalyticsQueryUniqueUserCountRequestInterval(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableAnalyticsQueryUniqueUserCountRequestInterval: %v", v)
	}
}

// StableAnalyticsQueryUniqueUserCountRequestVersion - Filters results to the draft or published version of the environment. Defaults to both.
type StableAnalyticsQueryUniqueUserCountRequestVersion string

const (
	StableAnalyticsQueryUniqueUserCountRequestVersionDraft     StableAnalyticsQueryUniqueUserCountRequestVersion = "draft"
	StableAnalyticsQueryUniqueUserCountRequestVersionPublished StableAnalyticsQueryUniqueUserCountRequestVersion = "published"
)

func (e StableAnalyticsQueryUniqueUserCountRequestVersion) ToPointer() *StableAnalyticsQueryUniqueUserCountRequestVersion {
	return &e
}
func (e *StableAnalyticsQueryUniqueUserCountRequestVersion) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "draft":
		fallthrough
	case "published":
		*e = StableAnalyticsQueryUniqueUserCountRequestVersion(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableAnalyticsQueryUniqueUserCountRequestVersion: %v", v)
	}
}

type StableAnalyticsQueryUniqueUserCountRequest struct {
	EndDate   string                                             `json:"endDate"`
	StartDate string                                             `json:"startDate"`
	Timezone  *string                                            `json:"timezone,omitzero"`
	Interval  StableAnalyticsQueryUniqueUserCountRequestInterval `json:"interval"`
	// Filters results to the draft or published version of the environment. Defaults to both.
	Version *StableAnalyticsQueryUniqueUserCountRequestVersion `json:"version,omitzero"`
	// The ID or alias of the environment to filter results by. Defaults to all environments.
	EnvironmentAlias *string `json:"environmentAlias,omitzero"`
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetEndDate() string {
	if s == nil {
		return ""
	}
	return s.EndDate
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetStartDate() string {
	if s == nil {
		return ""
	}
	return s.StartDate
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetTimezone() *string {
	if s == nil {
		return nil
	}
	return s.Timezone
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetInterval() StableAnalyticsQueryUniqueUserCountRequestInterval {
	if s == nil {
		return StableAnalyticsQueryUniqueUserCountRequestInterval("")
	}
	return s.Interval
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetVersion() *StableAnalyticsQueryUniqueUserCountRequestVersion {
	if s == nil {
		return nil
	}
	return s.Version
}

func (s *StableAnalyticsQueryUniqueUserCountRequest) GetEnvironmentAlias() *string {
	if s == nil {
		return nil
	}
	return s.EnvironmentAlias
}
