// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1af9f179dcc1

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableConversationSendConfig struct {
	// Trace types to drop from the response. Opt-in — when omitted, every trace is returned.
	ExcludeTypes []TraceType `json:"excludeTypes,omitzero"`
}

func (s StableConversationSendConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableConversationSendConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableConversationSendConfig) GetExcludeTypes() []TraceType {
	if s == nil {
		return nil
	}
	return s.ExcludeTypes
}
