// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 482ae588fc6c

package components

type StableAnalyticsQueryDailyTokenUsageResponseRow struct {
	IntervalStartDate string  `json:"intervalStartDate"`
	UsageClass        *string `json:"usageClass"`
	UsageCategory     *string `json:"usageCategory"`
	Model             *string `json:"model"`
	Misclassified     bool    `json:"misclassified"`
	Count             float64 `json:"count"`
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetIntervalStartDate() string {
	if s == nil {
		return ""
	}
	return s.IntervalStartDate
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetUsageClass() *string {
	if s == nil {
		return nil
	}
	return s.UsageClass
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetUsageCategory() *string {
	if s == nil {
		return nil
	}
	return s.UsageCategory
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetModel() *string {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetMisclassified() bool {
	if s == nil {
		return false
	}
	return s.Misclassified
}

func (s *StableAnalyticsQueryDailyTokenUsageResponseRow) GetCount() float64 {
	if s == nil {
		return 0.0
	}
	return s.Count
}

type StableAnalyticsQueryDailyTokenUsageResponse struct {
	Rows []StableAnalyticsQueryDailyTokenUsageResponseRow `json:"rows"`
}

func (s *StableAnalyticsQueryDailyTokenUsageResponse) GetRows() []StableAnalyticsQueryDailyTokenUsageResponseRow {
	if s == nil {
		return []StableAnalyticsQueryDailyTokenUsageResponseRow{}
	}
	return s.Rows
}
