// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c40e4f984ec4

package components

type StableEvaluationRunResponse struct {
	Result StableEvaluationResult `json:"result"`
}

func (s *StableEvaluationRunResponse) GetResult() StableEvaluationResult {
	if s == nil {
		return StableEvaluationResult{}
	}
	return s.Result
}
