// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6ef53ca360d8

package components

type StableVariableResponseV2 struct {
	Variable StableVariableV2 `json:"variable"`
}

func (s *StableVariableResponseV2) GetVariable() StableVariableV2 {
	if s == nil {
		return StableVariableV2{}
	}
	return s.Variable
}

// #region class-body-stablevariableresponsev2
// #endregion class-body-stablevariableresponsev2
