// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StableToolListResponse struct {
	Tools []StableTool `json:"tools"`
}

func (s *StableToolListResponse) GetTools() []StableTool {
	if s == nil {
		return []StableTool{}
	}
	return s.Tools
}
