// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableEnvironmentMergeRequest struct {
	// The alias of the environment whose changes are merged.
	SourceEnvironmentAlias string `json:"sourceEnvironmentAlias"`
	// The alias of the environment that receives the merged changes.
	TargetEnvironmentAlias string `json:"targetEnvironmentAlias"`
	// If true, the source environment is deleted after the merge.
	RemoveSourceEnvironment *bool `default:"false" json:"removeSourceEnvironment"`
}

func (s StableEnvironmentMergeRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEnvironmentMergeRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEnvironmentMergeRequest) GetSourceEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.SourceEnvironmentAlias
}

func (s *StableEnvironmentMergeRequest) GetTargetEnvironmentAlias() string {
	if s == nil {
		return ""
	}
	return s.TargetEnvironmentAlias
}

func (s *StableEnvironmentMergeRequest) GetRemoveSourceEnvironment() *bool {
	if s == nil {
		return nil
	}
	return s.RemoveSourceEnvironment
}
