// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StableProjectListResponse struct {
	Projects []StableProject `json:"projects"`
}

func (s *StableProjectListResponse) GetProjects() []StableProject {
	if s == nil {
		return []StableProject{}
	}
	return s.Projects
}
