// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cd7b0c251b71

package components

type StableAPIToolVariableListResponse struct {
	Variables []StableAPIToolVariable `json:"variables"`
}

func (s *StableAPIToolVariableListResponse) GetVariables() []StableAPIToolVariable {
	if s == nil {
		return []StableAPIToolVariable{}
	}
	return s.Variables
}
