// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 13caeec59173

package components

type StableAnalyticsQueryProjectTranscriptCostResponseRow struct {
	IntervalStartDate string  `json:"intervalStartDate"`
	TranscriptCount   float64 `json:"transcriptCount"`
	// The total cost incurred by transcripts for this row.
	Cost float64 `json:"cost"`
}

func (s *StableAnalyticsQueryProjectTranscriptCostResponseRow) GetIntervalStartDate() string {
	if s == nil {
		return ""
	}
	return s.IntervalStartDate
}

func (s *StableAnalyticsQueryProjectTranscriptCostResponseRow) GetTranscriptCount() float64 {
	if s == nil {
		return 0.0
	}
	return s.TranscriptCount
}

func (s *StableAnalyticsQueryProjectTranscriptCostResponseRow) GetCost() float64 {
	if s == nil {
		return 0.0
	}
	return s.Cost
}

type StableAnalyticsQueryProjectTranscriptCostResponse struct {
	Rows []StableAnalyticsQueryProjectTranscriptCostResponseRow `json:"rows"`
}

func (s *StableAnalyticsQueryProjectTranscriptCostResponse) GetRows() []StableAnalyticsQueryProjectTranscriptCostResponseRow {
	if s == nil {
		return []StableAnalyticsQueryProjectTranscriptCostResponseRow{}
	}
	return s.Rows
}
