// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 76257e90daf0

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// StableTestTurnCreateRequestTypeSimulation - Identifies a turn that hands off to an LLM-driven persona conversation.
type StableTestTurnCreateRequestTypeSimulation string

const (
	StableTestTurnCreateRequestTypeSimulationSimulation StableTestTurnCreateRequestTypeSimulation = "simulation"
)

func (e StableTestTurnCreateRequestTypeSimulation) ToPointer() *StableTestTurnCreateRequestTypeSimulation {
	return &e
}
func (e *StableTestTurnCreateRequestTypeSimulation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "simulation":
		*e = StableTestTurnCreateRequestTypeSimulation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestTurnCreateRequestTypeSimulation: %v", v)
	}
}

type StableTestTurnCreateRequestVariableStates2Type string

const (
	StableTestTurnCreateRequestVariableStates2TypeStr                StableTestTurnCreateRequestVariableStates2Type = "str"
	StableTestTurnCreateRequestVariableStates2TypeArrayOfPersonaItem StableTestTurnCreateRequestVariableStates2Type = "arrayOfPersonaItem"
)

type StableTestTurnCreateRequestVariableStates2 struct {
	Str                *string       `queryParam:"inline" union:"member"`
	ArrayOfPersonaItem []PersonaItem `queryParam:"inline" union:"member"`

	Type StableTestTurnCreateRequestVariableStates2Type
}

func CreateStableTestTurnCreateRequestVariableStates2Str(str string) StableTestTurnCreateRequestVariableStates2 {
	typ := StableTestTurnCreateRequestVariableStates2TypeStr

	return StableTestTurnCreateRequestVariableStates2{
		Str:  &str,
		Type: typ,
	}
}

func CreateStableTestTurnCreateRequestVariableStates2ArrayOfPersonaItem(arrayOfPersonaItem []PersonaItem) StableTestTurnCreateRequestVariableStates2 {
	typ := StableTestTurnCreateRequestVariableStates2TypeArrayOfPersonaItem

	return StableTestTurnCreateRequestVariableStates2{
		ArrayOfPersonaItem: arrayOfPersonaItem,
		Type:               typ,
	}
}

func (u *StableTestTurnCreateRequestVariableStates2) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableTestTurnCreateRequestVariableStates2TypeStr,
			Value: &str,
		})
	}

	var arrayOfPersonaItem []PersonaItem = []PersonaItem{}
	if err := utils.UnmarshalJSON(data, &arrayOfPersonaItem, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableTestTurnCreateRequestVariableStates2TypeArrayOfPersonaItem,
			Value: arrayOfPersonaItem,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates2", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates2", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableTestTurnCreateRequestVariableStates2Type)
	switch best.Type {
	case StableTestTurnCreateRequestVariableStates2TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case StableTestTurnCreateRequestVariableStates2TypeArrayOfPersonaItem:
		u.ArrayOfPersonaItem = best.Value.([]PersonaItem)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates2", string(data))
}

func (u StableTestTurnCreateRequestVariableStates2) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfPersonaItem != nil {
		return utils.MarshalJSON(u.ArrayOfPersonaItem, "", true)
	}

	return nil, errors.New("could not marshal union type StableTestTurnCreateRequestVariableStates2: all fields are null")
}

type StableTestTurnCreateRequestPayload3 struct {
	Scenario        string                                     `json:"scenario"`
	MaxTurns        float64                                    `json:"maxTurns"`
	VariableStates  StableTestTurnCreateRequestVariableStates2 `json:"variableStates"`
	SuccessCriteria string                                     `json:"successCriteria"`
}

func (s StableTestTurnCreateRequestPayload3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestPayload3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestPayload3) GetScenario() string {
	if s == nil {
		return ""
	}
	return s.Scenario
}

func (s *StableTestTurnCreateRequestPayload3) GetMaxTurns() float64 {
	if s == nil {
		return 0.0
	}
	return s.MaxTurns
}

func (s *StableTestTurnCreateRequestPayload3) GetVariableStates() StableTestTurnCreateRequestVariableStates2 {
	if s == nil {
		return StableTestTurnCreateRequestVariableStates2{}
	}
	return s.VariableStates
}

func (s *StableTestTurnCreateRequestPayload3) GetSuccessCriteria() string {
	if s == nil {
		return ""
	}
	return s.SuccessCriteria
}

// #region class-body-stabletestturncreaterequestpayload3
// #endregion class-body-stabletestturncreaterequestpayload3

type StableTestTurnCreateRequestSimulation struct {
	// Identifies a turn that hands off to an LLM-driven persona conversation.
	Type StableTestTurnCreateRequestTypeSimulation `json:"type"`
	// The ID of the test this turn belongs to.
	TestID  string                              `json:"testID"`
	Payload StableTestTurnCreateRequestPayload3 `json:"payload"`
}

func (s StableTestTurnCreateRequestSimulation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestSimulation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestSimulation) GetType() StableTestTurnCreateRequestTypeSimulation {
	if s == nil {
		return StableTestTurnCreateRequestTypeSimulation("")
	}
	return s.Type
}

func (s *StableTestTurnCreateRequestSimulation) GetTestID() string {
	if s == nil {
		return ""
	}
	return s.TestID
}

func (s *StableTestTurnCreateRequestSimulation) GetPayload() StableTestTurnCreateRequestPayload3 {
	if s == nil {
		return StableTestTurnCreateRequestPayload3{}
	}
	return s.Payload
}

// StableTestTurnCreateRequestTypeAgent - Identifies a turn that asserts on the agent's behavior via its attached checks.
type StableTestTurnCreateRequestTypeAgent string

const (
	StableTestTurnCreateRequestTypeAgentAgent StableTestTurnCreateRequestTypeAgent = "agent"
)

func (e StableTestTurnCreateRequestTypeAgent) ToPointer() *StableTestTurnCreateRequestTypeAgent {
	return &e
}
func (e *StableTestTurnCreateRequestTypeAgent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "agent":
		*e = StableTestTurnCreateRequestTypeAgent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestTurnCreateRequestTypeAgent: %v", v)
	}
}

type StableTestTurnCreateRequestPayload2 struct {
	// Whether the checks must pass in checkOrder rather than in any order.
	Sequential bool `json:"sequential"`
}

func (s StableTestTurnCreateRequestPayload2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestPayload2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestPayload2) GetSequential() bool {
	if s == nil {
		return false
	}
	return s.Sequential
}

// #region class-body-stabletestturncreaterequestpayload2
// #endregion class-body-stabletestturncreaterequestpayload2

type StableTestTurnCreateRequestAgent struct {
	// Identifies a turn that asserts on the agent's behavior via its attached checks.
	Type StableTestTurnCreateRequestTypeAgent `json:"type"`
	// The ID of the test this turn belongs to.
	TestID  string                              `json:"testID"`
	Payload StableTestTurnCreateRequestPayload2 `json:"payload"`
}

func (s StableTestTurnCreateRequestAgent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestAgent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestAgent) GetType() StableTestTurnCreateRequestTypeAgent {
	if s == nil {
		return StableTestTurnCreateRequestTypeAgent("")
	}
	return s.Type
}

func (s *StableTestTurnCreateRequestAgent) GetTestID() string {
	if s == nil {
		return ""
	}
	return s.TestID
}

func (s *StableTestTurnCreateRequestAgent) GetPayload() StableTestTurnCreateRequestPayload2 {
	if s == nil {
		return StableTestTurnCreateRequestPayload2{}
	}
	return s.Payload
}

// StableTestTurnCreateRequestTypeUser - Identifies a turn that sends a scripted user message.
type StableTestTurnCreateRequestTypeUser string

const (
	StableTestTurnCreateRequestTypeUserUser StableTestTurnCreateRequestTypeUser = "user"
)

func (e StableTestTurnCreateRequestTypeUser) ToPointer() *StableTestTurnCreateRequestTypeUser {
	return &e
}
func (e *StableTestTurnCreateRequestTypeUser) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		*e = StableTestTurnCreateRequestTypeUser(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestTurnCreateRequestTypeUser: %v", v)
	}
}

type StableTestTurnCreateRequestVariableStates1Type string

const (
	StableTestTurnCreateRequestVariableStates1TypeStr                StableTestTurnCreateRequestVariableStates1Type = "str"
	StableTestTurnCreateRequestVariableStates1TypeArrayOfPersonaItem StableTestTurnCreateRequestVariableStates1Type = "arrayOfPersonaItem"
)

type StableTestTurnCreateRequestVariableStates1 struct {
	Str                *string       `queryParam:"inline" union:"member"`
	ArrayOfPersonaItem []PersonaItem `queryParam:"inline" union:"member"`

	Type StableTestTurnCreateRequestVariableStates1Type
}

func CreateStableTestTurnCreateRequestVariableStates1Str(str string) StableTestTurnCreateRequestVariableStates1 {
	typ := StableTestTurnCreateRequestVariableStates1TypeStr

	return StableTestTurnCreateRequestVariableStates1{
		Str:  &str,
		Type: typ,
	}
}

func CreateStableTestTurnCreateRequestVariableStates1ArrayOfPersonaItem(arrayOfPersonaItem []PersonaItem) StableTestTurnCreateRequestVariableStates1 {
	typ := StableTestTurnCreateRequestVariableStates1TypeArrayOfPersonaItem

	return StableTestTurnCreateRequestVariableStates1{
		ArrayOfPersonaItem: arrayOfPersonaItem,
		Type:               typ,
	}
}

func (u *StableTestTurnCreateRequestVariableStates1) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableTestTurnCreateRequestVariableStates1TypeStr,
			Value: &str,
		})
	}

	var arrayOfPersonaItem []PersonaItem = []PersonaItem{}
	if err := utils.UnmarshalJSON(data, &arrayOfPersonaItem, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  StableTestTurnCreateRequestVariableStates1TypeArrayOfPersonaItem,
			Value: arrayOfPersonaItem,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates1", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates1", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(StableTestTurnCreateRequestVariableStates1Type)
	switch best.Type {
	case StableTestTurnCreateRequestVariableStates1TypeStr:
		u.Str = best.Value.(*string)
		return nil
	case StableTestTurnCreateRequestVariableStates1TypeArrayOfPersonaItem:
		u.ArrayOfPersonaItem = best.Value.([]PersonaItem)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequestVariableStates1", string(data))
}

func (u StableTestTurnCreateRequestVariableStates1) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfPersonaItem != nil {
		return utils.MarshalJSON(u.ArrayOfPersonaItem, "", true)
	}

	return nil, errors.New("could not marshal union type StableTestTurnCreateRequestVariableStates1: all fields are null")
}

type StableTestTurnCreateRequestPayload1 struct {
	Response       string                                     `json:"response"`
	VariableStates StableTestTurnCreateRequestVariableStates1 `json:"variableStates"`
}

func (s StableTestTurnCreateRequestPayload1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestPayload1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestPayload1) GetResponse() string {
	if s == nil {
		return ""
	}
	return s.Response
}

func (s *StableTestTurnCreateRequestPayload1) GetVariableStates() StableTestTurnCreateRequestVariableStates1 {
	if s == nil {
		return StableTestTurnCreateRequestVariableStates1{}
	}
	return s.VariableStates
}

// #region class-body-stabletestturncreaterequestpayload1
// #endregion class-body-stabletestturncreaterequestpayload1

type StableTestTurnCreateRequestUser struct {
	// Identifies a turn that sends a scripted user message.
	Type StableTestTurnCreateRequestTypeUser `json:"type"`
	// The ID of the test this turn belongs to.
	TestID  string                              `json:"testID"`
	Payload StableTestTurnCreateRequestPayload1 `json:"payload"`
}

func (s StableTestTurnCreateRequestUser) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestTurnCreateRequestUser) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestTurnCreateRequestUser) GetType() StableTestTurnCreateRequestTypeUser {
	if s == nil {
		return StableTestTurnCreateRequestTypeUser("")
	}
	return s.Type
}

func (s *StableTestTurnCreateRequestUser) GetTestID() string {
	if s == nil {
		return ""
	}
	return s.TestID
}

func (s *StableTestTurnCreateRequestUser) GetPayload() StableTestTurnCreateRequestPayload1 {
	if s == nil {
		return StableTestTurnCreateRequestPayload1{}
	}
	return s.Payload
}

type StableTestTurnCreateRequestType string

const (
	StableTestTurnCreateRequestTypeUserValue       StableTestTurnCreateRequestType = "user"
	StableTestTurnCreateRequestTypeAgentValue      StableTestTurnCreateRequestType = "agent"
	StableTestTurnCreateRequestTypeSimulationValue StableTestTurnCreateRequestType = "simulation"
)

type StableTestTurnCreateRequest struct {
	StableTestTurnCreateRequestUser       *StableTestTurnCreateRequestUser       `queryParam:"inline" union:"member"`
	StableTestTurnCreateRequestAgent      *StableTestTurnCreateRequestAgent      `queryParam:"inline" union:"member"`
	StableTestTurnCreateRequestSimulation *StableTestTurnCreateRequestSimulation `queryParam:"inline" union:"member"`

	Type StableTestTurnCreateRequestType
}

func CreateStableTestTurnCreateRequestUser(user StableTestTurnCreateRequestUser) StableTestTurnCreateRequest {
	typ := StableTestTurnCreateRequestTypeUserValue

	typStr := StableTestTurnCreateRequestTypeUser(typ)
	user.Type = typStr

	return StableTestTurnCreateRequest{
		StableTestTurnCreateRequestUser: &user,
		Type:                            typ,
	}
}

func CreateStableTestTurnCreateRequestAgent(agent StableTestTurnCreateRequestAgent) StableTestTurnCreateRequest {
	typ := StableTestTurnCreateRequestTypeAgentValue

	typStr := StableTestTurnCreateRequestTypeAgent(typ)
	agent.Type = typStr

	return StableTestTurnCreateRequest{
		StableTestTurnCreateRequestAgent: &agent,
		Type:                             typ,
	}
}

func CreateStableTestTurnCreateRequestSimulation(simulation StableTestTurnCreateRequestSimulation) StableTestTurnCreateRequest {
	typ := StableTestTurnCreateRequestTypeSimulationValue

	typStr := StableTestTurnCreateRequestTypeSimulation(typ)
	simulation.Type = typStr

	return StableTestTurnCreateRequest{
		StableTestTurnCreateRequestSimulation: &simulation,
		Type:                                  typ,
	}
}

func (u *StableTestTurnCreateRequest) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "user":
		stableTestTurnCreateRequestUser := new(StableTestTurnCreateRequestUser)
		if err := utils.UnmarshalJSON(data, &stableTestTurnCreateRequestUser, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == user) type StableTestTurnCreateRequestUser within StableTestTurnCreateRequest: %w", string(data), err)
		}

		u.StableTestTurnCreateRequestUser = stableTestTurnCreateRequestUser
		u.Type = StableTestTurnCreateRequestTypeUserValue
		return nil
	case "agent":
		stableTestTurnCreateRequestAgent := new(StableTestTurnCreateRequestAgent)
		if err := utils.UnmarshalJSON(data, &stableTestTurnCreateRequestAgent, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == agent) type StableTestTurnCreateRequestAgent within StableTestTurnCreateRequest: %w", string(data), err)
		}

		u.StableTestTurnCreateRequestAgent = stableTestTurnCreateRequestAgent
		u.Type = StableTestTurnCreateRequestTypeAgentValue
		return nil
	case "simulation":
		stableTestTurnCreateRequestSimulation := new(StableTestTurnCreateRequestSimulation)
		if err := utils.UnmarshalJSON(data, &stableTestTurnCreateRequestSimulation, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == simulation) type StableTestTurnCreateRequestSimulation within StableTestTurnCreateRequest: %w", string(data), err)
		}

		u.StableTestTurnCreateRequestSimulation = stableTestTurnCreateRequestSimulation
		u.Type = StableTestTurnCreateRequestTypeSimulationValue
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestTurnCreateRequest", string(data))
}

func (u StableTestTurnCreateRequest) MarshalJSON() ([]byte, error) {
	if u.StableTestTurnCreateRequestUser != nil {
		return utils.MarshalJSON(u.StableTestTurnCreateRequestUser, "", true)
	}

	if u.StableTestTurnCreateRequestAgent != nil {
		return utils.MarshalJSON(u.StableTestTurnCreateRequestAgent, "", true)
	}

	if u.StableTestTurnCreateRequestSimulation != nil {
		return utils.MarshalJSON(u.StableTestTurnCreateRequestSimulation, "", true)
	}

	return nil, errors.New("could not marshal union type StableTestTurnCreateRequest: all fields are null")
}
