// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c994a0a3aa2d

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type IntegrationExample string

const (
	IntegrationExampleExample IntegrationExample = "example"
)

func (e IntegrationExample) ToPointer() *IntegrationExample {
	return &e
}
func (e *IntegrationExample) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "example":
		*e = IntegrationExample(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationExample: %v", v)
	}
}

type StableIntegrationConnectRequestExample struct {
	Integration IntegrationExample `json:"integration"`
}

func (s StableIntegrationConnectRequestExample) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestExample) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestExample) GetIntegration() IntegrationExample {
	if s == nil {
		return IntegrationExample("")
	}
	return s.Integration
}

type IntegrationHubspot string

const (
	IntegrationHubspotHubspot IntegrationHubspot = "hubspot"
)

func (e IntegrationHubspot) ToPointer() *IntegrationHubspot {
	return &e
}
func (e *IntegrationHubspot) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "hubspot":
		*e = IntegrationHubspot(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationHubspot: %v", v)
	}
}

type StableIntegrationConnectRequestHubspot struct {
	Integration IntegrationHubspot `json:"integration"`
}

func (s StableIntegrationConnectRequestHubspot) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestHubspot) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestHubspot) GetIntegration() IntegrationHubspot {
	if s == nil {
		return IntegrationHubspot("")
	}
	return s.Integration
}

type IntegrationMake string

const (
	IntegrationMakeMake IntegrationMake = "make"
)

func (e IntegrationMake) ToPointer() *IntegrationMake {
	return &e
}
func (e *IntegrationMake) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "make":
		*e = IntegrationMake(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationMake: %v", v)
	}
}

type StableIntegrationConnectRequestMake struct {
	Integration IntegrationMake `json:"integration"`
}

func (s StableIntegrationConnectRequestMake) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestMake) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestMake) GetIntegration() IntegrationMake {
	if s == nil {
		return IntegrationMake("")
	}
	return s.Integration
}

type IntegrationAirtable string

const (
	IntegrationAirtableAirtable IntegrationAirtable = "airtable"
)

func (e IntegrationAirtable) ToPointer() *IntegrationAirtable {
	return &e
}
func (e *IntegrationAirtable) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "airtable":
		*e = IntegrationAirtable(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationAirtable: %v", v)
	}
}

type StableIntegrationConnectRequestAirtable struct {
	Integration IntegrationAirtable `json:"integration"`
}

func (s StableIntegrationConnectRequestAirtable) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestAirtable) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestAirtable) GetIntegration() IntegrationAirtable {
	if s == nil {
		return IntegrationAirtable("")
	}
	return s.Integration
}

type IntegrationGoogleGmail string

const (
	IntegrationGoogleGmailGoogleGmail IntegrationGoogleGmail = "google_gmail"
)

func (e IntegrationGoogleGmail) ToPointer() *IntegrationGoogleGmail {
	return &e
}
func (e *IntegrationGoogleGmail) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "google_gmail":
		*e = IntegrationGoogleGmail(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationGoogleGmail: %v", v)
	}
}

type StableIntegrationConnectRequestGoogleGmail struct {
	Integration IntegrationGoogleGmail `json:"integration"`
}

func (s StableIntegrationConnectRequestGoogleGmail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestGoogleGmail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestGoogleGmail) GetIntegration() IntegrationGoogleGmail {
	if s == nil {
		return IntegrationGoogleGmail("")
	}
	return s.Integration
}

type IntegrationGoogleSheets string

const (
	IntegrationGoogleSheetsGoogleSheets IntegrationGoogleSheets = "google_sheets"
)

func (e IntegrationGoogleSheets) ToPointer() *IntegrationGoogleSheets {
	return &e
}
func (e *IntegrationGoogleSheets) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "google_sheets":
		*e = IntegrationGoogleSheets(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationGoogleSheets: %v", v)
	}
}

type StableIntegrationConnectRequestGoogleSheets struct {
	Integration IntegrationGoogleSheets `json:"integration"`
}

func (s StableIntegrationConnectRequestGoogleSheets) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestGoogleSheets) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestGoogleSheets) GetIntegration() IntegrationGoogleSheets {
	if s == nil {
		return IntegrationGoogleSheets("")
	}
	return s.Integration
}

type IntegrationShopify string

const (
	IntegrationShopifyShopify IntegrationShopify = "shopify"
)

func (e IntegrationShopify) ToPointer() *IntegrationShopify {
	return &e
}
func (e *IntegrationShopify) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "shopify":
		*e = IntegrationShopify(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationShopify: %v", v)
	}
}

type StableIntegrationConnectRequestShopify struct {
	Integration IntegrationShopify `json:"integration"`
}

func (s StableIntegrationConnectRequestShopify) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestShopify) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestShopify) GetIntegration() IntegrationShopify {
	if s == nil {
		return IntegrationShopify("")
	}
	return s.Integration
}

type IntegrationSalesforce string

const (
	IntegrationSalesforceSalesforce IntegrationSalesforce = "salesforce"
)

func (e IntegrationSalesforce) ToPointer() *IntegrationSalesforce {
	return &e
}
func (e *IntegrationSalesforce) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "salesforce":
		*e = IntegrationSalesforce(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationSalesforce: %v", v)
	}
}

type StableIntegrationConnectRequestSalesforce struct {
	Integration IntegrationSalesforce `json:"integration"`
}

func (s StableIntegrationConnectRequestSalesforce) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestSalesforce) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestSalesforce) GetIntegration() IntegrationSalesforce {
	if s == nil {
		return IntegrationSalesforce("")
	}
	return s.Integration
}

type IntegrationZendesk string

const (
	IntegrationZendeskZendesk IntegrationZendesk = "zendesk"
)

func (e IntegrationZendesk) ToPointer() *IntegrationZendesk {
	return &e
}
func (e *IntegrationZendesk) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "zendesk":
		*e = IntegrationZendesk(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationZendesk: %v", v)
	}
}

type StableIntegrationConnectRequestZendesk struct {
	Integration IntegrationZendesk `json:"integration"`
}

func (s StableIntegrationConnectRequestZendesk) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestZendesk) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestZendesk) GetIntegration() IntegrationZendesk {
	if s == nil {
		return IntegrationZendesk("")
	}
	return s.Integration
}

type IntegrationSunshine string

const (
	IntegrationSunshineSunshine IntegrationSunshine = "sunshine"
)

func (e IntegrationSunshine) ToPointer() *IntegrationSunshine {
	return &e
}
func (e *IntegrationSunshine) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sunshine":
		*e = IntegrationSunshine(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationSunshine: %v", v)
	}
}

type StableIntegrationConnectRequestSunshine struct {
	Integration IntegrationSunshine                 `json:"integration"`
	Credentials SunshineIntegrationCredentialsValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestSunshine) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestSunshine) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestSunshine) GetIntegration() IntegrationSunshine {
	if s == nil {
		return IntegrationSunshine("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestSunshine) GetCredentials() SunshineIntegrationCredentialsValue {
	if s == nil {
		return SunshineIntegrationCredentialsValue{}
	}
	return s.Credentials
}

type IntegrationDixa string

const (
	IntegrationDixaDixa IntegrationDixa = "dixa"
)

func (e IntegrationDixa) ToPointer() *IntegrationDixa {
	return &e
}
func (e *IntegrationDixa) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dixa":
		*e = IntegrationDixa(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationDixa: %v", v)
	}
}

type StableIntegrationConnectRequestDixa struct {
	Integration IntegrationDixa                 `json:"integration"`
	Credentials DixaIntegrationCredentialsValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestDixa) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestDixa) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestDixa) GetIntegration() IntegrationDixa {
	if s == nil {
		return IntegrationDixa("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestDixa) GetCredentials() DixaIntegrationCredentialsValue {
	if s == nil {
		return DixaIntegrationCredentialsValue{}
	}
	return s.Credentials
}

type IntegrationKustomer string

const (
	IntegrationKustomerKustomer IntegrationKustomer = "kustomer"
)

func (e IntegrationKustomer) ToPointer() *IntegrationKustomer {
	return &e
}
func (e *IntegrationKustomer) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "kustomer":
		*e = IntegrationKustomer(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationKustomer: %v", v)
	}
}

type StableIntegrationConnectRequestKustomer struct {
	Integration IntegrationKustomer                 `json:"integration"`
	Credentials KustomerIntegrationCredentialsValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestKustomer) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestKustomer) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestKustomer) GetIntegration() IntegrationKustomer {
	if s == nil {
		return IntegrationKustomer("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestKustomer) GetCredentials() KustomerIntegrationCredentialsValue {
	if s == nil {
		return KustomerIntegrationCredentialsValue{}
	}
	return s.Credentials
}

type IntegrationGenesys string

const (
	IntegrationGenesysGenesys IntegrationGenesys = "genesys"
)

func (e IntegrationGenesys) ToPointer() *IntegrationGenesys {
	return &e
}
func (e *IntegrationGenesys) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "genesys":
		*e = IntegrationGenesys(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationGenesys: %v", v)
	}
}

type StableIntegrationConnectRequestGenesys struct {
	Integration IntegrationGenesys                 `json:"integration"`
	Credentials GenesysIntegrationCredentialsValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestGenesys) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestGenesys) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestGenesys) GetIntegration() IntegrationGenesys {
	if s == nil {
		return IntegrationGenesys("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestGenesys) GetCredentials() GenesysIntegrationCredentialsValue {
	if s == nil {
		return GenesysIntegrationCredentialsValue{}
	}
	return s.Credentials
}

type IntegrationUjet string

const (
	IntegrationUjetUjet IntegrationUjet = "ujet"
)

func (e IntegrationUjet) ToPointer() *IntegrationUjet {
	return &e
}
func (e *IntegrationUjet) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ujet":
		*e = IntegrationUjet(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationUjet: %v", v)
	}
}

type StableIntegrationConnectRequestUjet struct {
	Integration IntegrationUjet                 `json:"integration"`
	Credentials UjetIntegrationCredentialsValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestUjet) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestUjet) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestUjet) GetIntegration() IntegrationUjet {
	if s == nil {
		return IntegrationUjet("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestUjet) GetCredentials() UjetIntegrationCredentialsValue {
	if s == nil {
		return UjetIntegrationCredentialsValue{}
	}
	return s.Credentials
}

type IntegrationTwilio string

const (
	IntegrationTwilioTwilio IntegrationTwilio = "twilio"
)

func (e IntegrationTwilio) ToPointer() *IntegrationTwilio {
	return &e
}
func (e *IntegrationTwilio) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "twilio":
		*e = IntegrationTwilio(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationTwilio: %v", v)
	}
}

type StableIntegrationConnectRequestTwilio struct {
	Integration IntegrationTwilio            `json:"integration"`
	Credentials TwilioIntegrationAPIKeyValue `json:"credentials"`
}

func (s StableIntegrationConnectRequestTwilio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestTwilio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestTwilio) GetIntegration() IntegrationTwilio {
	if s == nil {
		return IntegrationTwilio("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestTwilio) GetCredentials() TwilioIntegrationAPIKeyValue {
	if s == nil {
		return TwilioIntegrationAPIKeyValue{}
	}
	return s.Credentials
}

type IntegrationElevenLabs string

const (
	IntegrationElevenLabsElevenLabs IntegrationElevenLabs = "eleven_labs"
)

func (e IntegrationElevenLabs) ToPointer() *IntegrationElevenLabs {
	return &e
}
func (e *IntegrationElevenLabs) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "eleven_labs":
		*e = IntegrationElevenLabs(v)
		return nil
	default:
		return fmt.Errorf("invalid value for IntegrationElevenLabs: %v", v)
	}
}

type StableIntegrationConnectRequestElevenLabs struct {
	Integration IntegrationElevenLabs `json:"integration"`
	Credentials string                `json:"credentials"`
}

func (s StableIntegrationConnectRequestElevenLabs) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableIntegrationConnectRequestElevenLabs) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableIntegrationConnectRequestElevenLabs) GetIntegration() IntegrationElevenLabs {
	if s == nil {
		return IntegrationElevenLabs("")
	}
	return s.Integration
}

func (s *StableIntegrationConnectRequestElevenLabs) GetCredentials() string {
	if s == nil {
		return ""
	}
	return s.Credentials
}

type StableIntegrationConnectRequestType string

const (
	StableIntegrationConnectRequestTypeElevenLabs   StableIntegrationConnectRequestType = "eleven_labs"
	StableIntegrationConnectRequestTypeTwilio       StableIntegrationConnectRequestType = "twilio"
	StableIntegrationConnectRequestTypeUjet         StableIntegrationConnectRequestType = "ujet"
	StableIntegrationConnectRequestTypeGenesys      StableIntegrationConnectRequestType = "genesys"
	StableIntegrationConnectRequestTypeKustomer     StableIntegrationConnectRequestType = "kustomer"
	StableIntegrationConnectRequestTypeDixa         StableIntegrationConnectRequestType = "dixa"
	StableIntegrationConnectRequestTypeSunshine     StableIntegrationConnectRequestType = "sunshine"
	StableIntegrationConnectRequestTypeZendesk      StableIntegrationConnectRequestType = "zendesk"
	StableIntegrationConnectRequestTypeSalesforce   StableIntegrationConnectRequestType = "salesforce"
	StableIntegrationConnectRequestTypeShopify      StableIntegrationConnectRequestType = "shopify"
	StableIntegrationConnectRequestTypeGoogleSheets StableIntegrationConnectRequestType = "google_sheets"
	StableIntegrationConnectRequestTypeGoogleGmail  StableIntegrationConnectRequestType = "google_gmail"
	StableIntegrationConnectRequestTypeAirtable     StableIntegrationConnectRequestType = "airtable"
	StableIntegrationConnectRequestTypeMake         StableIntegrationConnectRequestType = "make"
	StableIntegrationConnectRequestTypeHubspot      StableIntegrationConnectRequestType = "hubspot"
	StableIntegrationConnectRequestTypeExample      StableIntegrationConnectRequestType = "example"
)

type StableIntegrationConnectRequest struct {
	StableIntegrationConnectRequestElevenLabs   *StableIntegrationConnectRequestElevenLabs   `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestTwilio       *StableIntegrationConnectRequestTwilio       `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestUjet         *StableIntegrationConnectRequestUjet         `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestGenesys      *StableIntegrationConnectRequestGenesys      `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestKustomer     *StableIntegrationConnectRequestKustomer     `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestDixa         *StableIntegrationConnectRequestDixa         `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestSunshine     *StableIntegrationConnectRequestSunshine     `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestZendesk      *StableIntegrationConnectRequestZendesk      `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestSalesforce   *StableIntegrationConnectRequestSalesforce   `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestShopify      *StableIntegrationConnectRequestShopify      `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestGoogleSheets *StableIntegrationConnectRequestGoogleSheets `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestGoogleGmail  *StableIntegrationConnectRequestGoogleGmail  `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestAirtable     *StableIntegrationConnectRequestAirtable     `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestMake         *StableIntegrationConnectRequestMake         `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestHubspot      *StableIntegrationConnectRequestHubspot      `queryParam:"inline" union:"member"`
	StableIntegrationConnectRequestExample      *StableIntegrationConnectRequestExample      `queryParam:"inline" union:"member"`

	Type StableIntegrationConnectRequestType
}

func CreateStableIntegrationConnectRequestElevenLabs(elevenLabs StableIntegrationConnectRequestElevenLabs) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeElevenLabs

	typStr := IntegrationElevenLabs(typ)
	elevenLabs.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestElevenLabs: &elevenLabs,
		Type: typ,
	}
}

func CreateStableIntegrationConnectRequestTwilio(twilio StableIntegrationConnectRequestTwilio) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeTwilio

	typStr := IntegrationTwilio(typ)
	twilio.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestTwilio: &twilio,
		Type:                                  typ,
	}
}

func CreateStableIntegrationConnectRequestUjet(ujet StableIntegrationConnectRequestUjet) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeUjet

	typStr := IntegrationUjet(typ)
	ujet.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestUjet: &ujet,
		Type:                                typ,
	}
}

func CreateStableIntegrationConnectRequestGenesys(genesys StableIntegrationConnectRequestGenesys) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeGenesys

	typStr := IntegrationGenesys(typ)
	genesys.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestGenesys: &genesys,
		Type:                                   typ,
	}
}

func CreateStableIntegrationConnectRequestKustomer(kustomer StableIntegrationConnectRequestKustomer) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeKustomer

	typStr := IntegrationKustomer(typ)
	kustomer.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestKustomer: &kustomer,
		Type:                                    typ,
	}
}

func CreateStableIntegrationConnectRequestDixa(dixa StableIntegrationConnectRequestDixa) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeDixa

	typStr := IntegrationDixa(typ)
	dixa.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestDixa: &dixa,
		Type:                                typ,
	}
}

func CreateStableIntegrationConnectRequestSunshine(sunshine StableIntegrationConnectRequestSunshine) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeSunshine

	typStr := IntegrationSunshine(typ)
	sunshine.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestSunshine: &sunshine,
		Type:                                    typ,
	}
}

func CreateStableIntegrationConnectRequestZendesk(zendesk StableIntegrationConnectRequestZendesk) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeZendesk

	typStr := IntegrationZendesk(typ)
	zendesk.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestZendesk: &zendesk,
		Type:                                   typ,
	}
}

func CreateStableIntegrationConnectRequestSalesforce(salesforce StableIntegrationConnectRequestSalesforce) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeSalesforce

	typStr := IntegrationSalesforce(typ)
	salesforce.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestSalesforce: &salesforce,
		Type: typ,
	}
}

func CreateStableIntegrationConnectRequestShopify(shopify StableIntegrationConnectRequestShopify) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeShopify

	typStr := IntegrationShopify(typ)
	shopify.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestShopify: &shopify,
		Type:                                   typ,
	}
}

func CreateStableIntegrationConnectRequestGoogleSheets(googleSheets StableIntegrationConnectRequestGoogleSheets) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeGoogleSheets

	typStr := IntegrationGoogleSheets(typ)
	googleSheets.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestGoogleSheets: &googleSheets,
		Type: typ,
	}
}

func CreateStableIntegrationConnectRequestGoogleGmail(googleGmail StableIntegrationConnectRequestGoogleGmail) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeGoogleGmail

	typStr := IntegrationGoogleGmail(typ)
	googleGmail.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestGoogleGmail: &googleGmail,
		Type: typ,
	}
}

func CreateStableIntegrationConnectRequestAirtable(airtable StableIntegrationConnectRequestAirtable) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeAirtable

	typStr := IntegrationAirtable(typ)
	airtable.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestAirtable: &airtable,
		Type:                                    typ,
	}
}

func CreateStableIntegrationConnectRequestMake(make StableIntegrationConnectRequestMake) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeMake

	typStr := IntegrationMake(typ)
	make.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestMake: &make,
		Type:                                typ,
	}
}

func CreateStableIntegrationConnectRequestHubspot(hubspot StableIntegrationConnectRequestHubspot) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeHubspot

	typStr := IntegrationHubspot(typ)
	hubspot.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestHubspot: &hubspot,
		Type:                                   typ,
	}
}

func CreateStableIntegrationConnectRequestExample(example StableIntegrationConnectRequestExample) StableIntegrationConnectRequest {
	typ := StableIntegrationConnectRequestTypeExample

	typStr := IntegrationExample(typ)
	example.Integration = typStr

	return StableIntegrationConnectRequest{
		StableIntegrationConnectRequestExample: &example,
		Type:                                   typ,
	}
}

func (u *StableIntegrationConnectRequest) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Integration string `json:"integration"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Integration {
	case "eleven_labs":
		stableIntegrationConnectRequestElevenLabs := new(StableIntegrationConnectRequestElevenLabs)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestElevenLabs, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == eleven_labs) type StableIntegrationConnectRequestElevenLabs within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestElevenLabs = stableIntegrationConnectRequestElevenLabs
		u.Type = StableIntegrationConnectRequestTypeElevenLabs
		return nil
	case "twilio":
		stableIntegrationConnectRequestTwilio := new(StableIntegrationConnectRequestTwilio)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestTwilio, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == twilio) type StableIntegrationConnectRequestTwilio within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestTwilio = stableIntegrationConnectRequestTwilio
		u.Type = StableIntegrationConnectRequestTypeTwilio
		return nil
	case "ujet":
		stableIntegrationConnectRequestUjet := new(StableIntegrationConnectRequestUjet)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestUjet, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == ujet) type StableIntegrationConnectRequestUjet within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestUjet = stableIntegrationConnectRequestUjet
		u.Type = StableIntegrationConnectRequestTypeUjet
		return nil
	case "genesys":
		stableIntegrationConnectRequestGenesys := new(StableIntegrationConnectRequestGenesys)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestGenesys, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == genesys) type StableIntegrationConnectRequestGenesys within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestGenesys = stableIntegrationConnectRequestGenesys
		u.Type = StableIntegrationConnectRequestTypeGenesys
		return nil
	case "kustomer":
		stableIntegrationConnectRequestKustomer := new(StableIntegrationConnectRequestKustomer)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestKustomer, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == kustomer) type StableIntegrationConnectRequestKustomer within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestKustomer = stableIntegrationConnectRequestKustomer
		u.Type = StableIntegrationConnectRequestTypeKustomer
		return nil
	case "dixa":
		stableIntegrationConnectRequestDixa := new(StableIntegrationConnectRequestDixa)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestDixa, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == dixa) type StableIntegrationConnectRequestDixa within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestDixa = stableIntegrationConnectRequestDixa
		u.Type = StableIntegrationConnectRequestTypeDixa
		return nil
	case "sunshine":
		stableIntegrationConnectRequestSunshine := new(StableIntegrationConnectRequestSunshine)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestSunshine, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == sunshine) type StableIntegrationConnectRequestSunshine within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestSunshine = stableIntegrationConnectRequestSunshine
		u.Type = StableIntegrationConnectRequestTypeSunshine
		return nil
	case "zendesk":
		stableIntegrationConnectRequestZendesk := new(StableIntegrationConnectRequestZendesk)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestZendesk, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == zendesk) type StableIntegrationConnectRequestZendesk within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestZendesk = stableIntegrationConnectRequestZendesk
		u.Type = StableIntegrationConnectRequestTypeZendesk
		return nil
	case "salesforce":
		stableIntegrationConnectRequestSalesforce := new(StableIntegrationConnectRequestSalesforce)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestSalesforce, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == salesforce) type StableIntegrationConnectRequestSalesforce within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestSalesforce = stableIntegrationConnectRequestSalesforce
		u.Type = StableIntegrationConnectRequestTypeSalesforce
		return nil
	case "shopify":
		stableIntegrationConnectRequestShopify := new(StableIntegrationConnectRequestShopify)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestShopify, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == shopify) type StableIntegrationConnectRequestShopify within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestShopify = stableIntegrationConnectRequestShopify
		u.Type = StableIntegrationConnectRequestTypeShopify
		return nil
	case "google_sheets":
		stableIntegrationConnectRequestGoogleSheets := new(StableIntegrationConnectRequestGoogleSheets)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestGoogleSheets, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == google_sheets) type StableIntegrationConnectRequestGoogleSheets within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestGoogleSheets = stableIntegrationConnectRequestGoogleSheets
		u.Type = StableIntegrationConnectRequestTypeGoogleSheets
		return nil
	case "google_gmail":
		stableIntegrationConnectRequestGoogleGmail := new(StableIntegrationConnectRequestGoogleGmail)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestGoogleGmail, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == google_gmail) type StableIntegrationConnectRequestGoogleGmail within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestGoogleGmail = stableIntegrationConnectRequestGoogleGmail
		u.Type = StableIntegrationConnectRequestTypeGoogleGmail
		return nil
	case "airtable":
		stableIntegrationConnectRequestAirtable := new(StableIntegrationConnectRequestAirtable)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestAirtable, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == airtable) type StableIntegrationConnectRequestAirtable within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestAirtable = stableIntegrationConnectRequestAirtable
		u.Type = StableIntegrationConnectRequestTypeAirtable
		return nil
	case "make":
		stableIntegrationConnectRequestMake := new(StableIntegrationConnectRequestMake)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestMake, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == make) type StableIntegrationConnectRequestMake within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestMake = stableIntegrationConnectRequestMake
		u.Type = StableIntegrationConnectRequestTypeMake
		return nil
	case "hubspot":
		stableIntegrationConnectRequestHubspot := new(StableIntegrationConnectRequestHubspot)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestHubspot, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == hubspot) type StableIntegrationConnectRequestHubspot within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestHubspot = stableIntegrationConnectRequestHubspot
		u.Type = StableIntegrationConnectRequestTypeHubspot
		return nil
	case "example":
		stableIntegrationConnectRequestExample := new(StableIntegrationConnectRequestExample)
		if err := utils.UnmarshalJSON(data, &stableIntegrationConnectRequestExample, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Integration == example) type StableIntegrationConnectRequestExample within StableIntegrationConnectRequest: %w", string(data), err)
		}

		u.StableIntegrationConnectRequestExample = stableIntegrationConnectRequestExample
		u.Type = StableIntegrationConnectRequestTypeExample
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableIntegrationConnectRequest", string(data))
}

func (u StableIntegrationConnectRequest) MarshalJSON() ([]byte, error) {
	if u.StableIntegrationConnectRequestElevenLabs != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestElevenLabs, "", true)
	}

	if u.StableIntegrationConnectRequestTwilio != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestTwilio, "", true)
	}

	if u.StableIntegrationConnectRequestUjet != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestUjet, "", true)
	}

	if u.StableIntegrationConnectRequestGenesys != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestGenesys, "", true)
	}

	if u.StableIntegrationConnectRequestKustomer != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestKustomer, "", true)
	}

	if u.StableIntegrationConnectRequestDixa != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestDixa, "", true)
	}

	if u.StableIntegrationConnectRequestSunshine != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestSunshine, "", true)
	}

	if u.StableIntegrationConnectRequestZendesk != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestZendesk, "", true)
	}

	if u.StableIntegrationConnectRequestSalesforce != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestSalesforce, "", true)
	}

	if u.StableIntegrationConnectRequestShopify != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestShopify, "", true)
	}

	if u.StableIntegrationConnectRequestGoogleSheets != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestGoogleSheets, "", true)
	}

	if u.StableIntegrationConnectRequestGoogleGmail != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestGoogleGmail, "", true)
	}

	if u.StableIntegrationConnectRequestAirtable != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestAirtable, "", true)
	}

	if u.StableIntegrationConnectRequestMake != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestMake, "", true)
	}

	if u.StableIntegrationConnectRequestHubspot != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestHubspot, "", true)
	}

	if u.StableIntegrationConnectRequestExample != nil {
		return utils.MarshalJSON(u.StableIntegrationConnectRequestExample, "", true)
	}

	return nil, errors.New("could not marshal union type StableIntegrationConnectRequest: all fields are null")
}
