// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: debe09b3e55b

package components

type StableWidgetGetSnippetResponse struct {
	// The complete `<script>` tag to paste into the website, just before the closing `</body>` of every page the widget should appear on. Already filled in with the right verification key, runtime endpoints and render block — it is meant to be copied verbatim, not edited.
	Snippet string `json:"snippet"`
}

func (s *StableWidgetGetSnippetResponse) GetSnippet() string {
	if s == nil {
		return ""
	}
	return s.Snippet
}
