// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d49770ee1613

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// Visibility - Whether the value can be revealed in the Voiceflow UI. `restricted` secrets can never be read back by anyone.
type Visibility string

const (
	VisibilityRestricted Visibility = "restricted"
	VisibilityMasked     Visibility = "masked"
)

func (e Visibility) ToPointer() *Visibility {
	return &e
}
func (e *Visibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "restricted":
		fallthrough
	case "masked":
		*e = Visibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Visibility: %v", v)
	}
}

type StableSecretCreateRequest struct {
	// The name of the secret. Must be unique within the project.
	Name string `json:"name"`
	// The project-level value. Omit to create the secret as a placeholder with no value — a teammate can fill it in later through the Voiceflow UI or CLI.
	DefaultValue *string `json:"defaultValue,omitzero"`
	// Whether the value can be revealed in the Voiceflow UI. `restricted` secrets can never be read back by anyone.
	Visibility *Visibility `default:"masked" json:"visibility"`
}

func (s StableSecretCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableSecretCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableSecretCreateRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableSecretCreateRequest) GetDefaultValue() *string {
	if s == nil {
		return nil
	}
	return s.DefaultValue
}

func (s *StableSecretCreateRequest) GetVisibility() *Visibility {
	if s == nil {
		return nil
	}
	return s.Visibility
}
