// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 87bd7dcce009

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableMCPServerResponseV2 struct {
	McpServer StableMCPServerV2 `json:"mcpServer"`
	// References this write kept as literal text instead of binding, each with the reason. The write still succeeded.
	UnresolvedReferences []StableUnresolvedReference `json:"unresolvedReferences,omitzero"`
}

func (s StableMCPServerResponseV2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableMCPServerResponseV2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableMCPServerResponseV2) GetMcpServer() StableMCPServerV2 {
	if s == nil {
		return StableMCPServerV2{}
	}
	return s.McpServer
}

func (s *StableMCPServerResponseV2) GetUnresolvedReferences() []StableUnresolvedReference {
	if s == nil {
		return nil
	}
	return s.UnresolvedReferences
}

// #region class-body-stablemcpserverresponsev2
// #endregion class-body-stablemcpserverresponsev2
