// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 09765658151f

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableTestCheckUpdateRequestTypeTool string

const (
	StableTestCheckUpdateRequestTypeToolTool StableTestCheckUpdateRequestTypeTool = "tool"
)

func (e StableTestCheckUpdateRequestTypeTool) ToPointer() *StableTestCheckUpdateRequestTypeTool {
	return &e
}
func (e *StableTestCheckUpdateRequestTypeTool) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tool":
		*e = StableTestCheckUpdateRequestTypeTool(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestCheckUpdateRequestTypeTool: %v", v)
	}
}

type StableTestCheckUpdateRequestTool struct {
	Type    StableTestCheckUpdateRequestTypeTool `json:"type"`
	Payload *ToolSimulationTurnTestPayload       `json:"payload,omitzero"`
}

func (s StableTestCheckUpdateRequestTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestCheckUpdateRequestTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestCheckUpdateRequestTool) GetType() StableTestCheckUpdateRequestTypeTool {
	if s == nil {
		return StableTestCheckUpdateRequestTypeTool("")
	}
	return s.Type
}

func (s *StableTestCheckUpdateRequestTool) GetPayload() *ToolSimulationTurnTestPayload {
	if s == nil {
		return nil
	}
	return s.Payload
}

type StableTestCheckUpdateRequestTypeRouting string

const (
	StableTestCheckUpdateRequestTypeRoutingRouting StableTestCheckUpdateRequestTypeRouting = "routing"
)

func (e StableTestCheckUpdateRequestTypeRouting) ToPointer() *StableTestCheckUpdateRequestTypeRouting {
	return &e
}
func (e *StableTestCheckUpdateRequestTypeRouting) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "routing":
		*e = StableTestCheckUpdateRequestTypeRouting(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestCheckUpdateRequestTypeRouting: %v", v)
	}
}

type StableTestCheckUpdateRequestRouting struct {
	Type    StableTestCheckUpdateRequestTypeRouting `json:"type"`
	Payload *RoutingSimulationTurnTestPayload       `json:"payload,omitzero"`
}

func (s StableTestCheckUpdateRequestRouting) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestCheckUpdateRequestRouting) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestCheckUpdateRequestRouting) GetType() StableTestCheckUpdateRequestTypeRouting {
	if s == nil {
		return StableTestCheckUpdateRequestTypeRouting("")
	}
	return s.Type
}

func (s *StableTestCheckUpdateRequestRouting) GetPayload() *RoutingSimulationTurnTestPayload {
	if s == nil {
		return nil
	}
	return s.Payload
}

type StableTestCheckUpdateRequestTypeResponse string

const (
	StableTestCheckUpdateRequestTypeResponseResponse StableTestCheckUpdateRequestTypeResponse = "response"
)

func (e StableTestCheckUpdateRequestTypeResponse) ToPointer() *StableTestCheckUpdateRequestTypeResponse {
	return &e
}
func (e *StableTestCheckUpdateRequestTypeResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "response":
		*e = StableTestCheckUpdateRequestTypeResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableTestCheckUpdateRequestTypeResponse: %v", v)
	}
}

type StableTestCheckUpdateRequestResponse struct {
	Type    StableTestCheckUpdateRequestTypeResponse `json:"type"`
	Payload *ResponseSimulationTurnTestPayload       `json:"payload,omitzero"`
}

func (s StableTestCheckUpdateRequestResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableTestCheckUpdateRequestResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableTestCheckUpdateRequestResponse) GetType() StableTestCheckUpdateRequestTypeResponse {
	if s == nil {
		return StableTestCheckUpdateRequestTypeResponse("")
	}
	return s.Type
}

func (s *StableTestCheckUpdateRequestResponse) GetPayload() *ResponseSimulationTurnTestPayload {
	if s == nil {
		return nil
	}
	return s.Payload
}

func (s *StableTestCheckUpdateRequestResponse) GetPayloadEqual() *SimulationTurnTestJudgeEqual {
	if v := s.GetPayload(); v != nil {
		return v.SimulationTurnTestJudgeEqual
	}
	return nil
}

func (s *StableTestCheckUpdateRequestResponse) GetPayloadLlmEval() *SimulationTurnTestJudgeLLMEval {
	if v := s.GetPayload(); v != nil {
		return v.SimulationTurnTestJudgeLLMEval
	}
	return nil
}

type StableTestCheckUpdateRequestType string

const (
	StableTestCheckUpdateRequestTypeResponseValue StableTestCheckUpdateRequestType = "response"
	StableTestCheckUpdateRequestTypeRoutingValue  StableTestCheckUpdateRequestType = "routing"
	StableTestCheckUpdateRequestTypeToolValue     StableTestCheckUpdateRequestType = "tool"
)

type StableTestCheckUpdateRequest struct {
	StableTestCheckUpdateRequestResponse *StableTestCheckUpdateRequestResponse `queryParam:"inline" union:"member"`
	StableTestCheckUpdateRequestRouting  *StableTestCheckUpdateRequestRouting  `queryParam:"inline" union:"member"`
	StableTestCheckUpdateRequestTool     *StableTestCheckUpdateRequestTool     `queryParam:"inline" union:"member"`

	Type StableTestCheckUpdateRequestType
}

func CreateStableTestCheckUpdateRequestResponse(response StableTestCheckUpdateRequestResponse) StableTestCheckUpdateRequest {
	typ := StableTestCheckUpdateRequestTypeResponseValue

	typStr := StableTestCheckUpdateRequestTypeResponse(typ)
	response.Type = typStr

	return StableTestCheckUpdateRequest{
		StableTestCheckUpdateRequestResponse: &response,
		Type:                                 typ,
	}
}

func CreateStableTestCheckUpdateRequestRouting(routing StableTestCheckUpdateRequestRouting) StableTestCheckUpdateRequest {
	typ := StableTestCheckUpdateRequestTypeRoutingValue

	typStr := StableTestCheckUpdateRequestTypeRouting(typ)
	routing.Type = typStr

	return StableTestCheckUpdateRequest{
		StableTestCheckUpdateRequestRouting: &routing,
		Type:                                typ,
	}
}

func CreateStableTestCheckUpdateRequestTool(tool StableTestCheckUpdateRequestTool) StableTestCheckUpdateRequest {
	typ := StableTestCheckUpdateRequestTypeToolValue

	typStr := StableTestCheckUpdateRequestTypeTool(typ)
	tool.Type = typStr

	return StableTestCheckUpdateRequest{
		StableTestCheckUpdateRequestTool: &tool,
		Type:                             typ,
	}
}

func (u *StableTestCheckUpdateRequest) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.Type {
	case "response":
		stableTestCheckUpdateRequestResponse := new(StableTestCheckUpdateRequestResponse)
		if err := utils.UnmarshalJSON(data, &stableTestCheckUpdateRequestResponse, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == response) type StableTestCheckUpdateRequestResponse within StableTestCheckUpdateRequest: %w", string(data), err)
		}

		u.StableTestCheckUpdateRequestResponse = stableTestCheckUpdateRequestResponse
		u.Type = StableTestCheckUpdateRequestTypeResponseValue
		return nil
	case "routing":
		stableTestCheckUpdateRequestRouting := new(StableTestCheckUpdateRequestRouting)
		if err := utils.UnmarshalJSON(data, &stableTestCheckUpdateRequestRouting, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == routing) type StableTestCheckUpdateRequestRouting within StableTestCheckUpdateRequest: %w", string(data), err)
		}

		u.StableTestCheckUpdateRequestRouting = stableTestCheckUpdateRequestRouting
		u.Type = StableTestCheckUpdateRequestTypeRoutingValue
		return nil
	case "tool":
		stableTestCheckUpdateRequestTool := new(StableTestCheckUpdateRequestTool)
		if err := utils.UnmarshalJSON(data, &stableTestCheckUpdateRequestTool, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == tool) type StableTestCheckUpdateRequestTool within StableTestCheckUpdateRequest: %w", string(data), err)
		}

		u.StableTestCheckUpdateRequestTool = stableTestCheckUpdateRequestTool
		u.Type = StableTestCheckUpdateRequestTypeToolValue
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for StableTestCheckUpdateRequest", string(data))
}

func (u StableTestCheckUpdateRequest) MarshalJSON() ([]byte, error) {
	if u.StableTestCheckUpdateRequestResponse != nil {
		return utils.MarshalJSON(u.StableTestCheckUpdateRequestResponse, "", true)
	}

	if u.StableTestCheckUpdateRequestRouting != nil {
		return utils.MarshalJSON(u.StableTestCheckUpdateRequestRouting, "", true)
	}

	if u.StableTestCheckUpdateRequestTool != nil {
		return utils.MarshalJSON(u.StableTestCheckUpdateRequestTool, "", true)
	}

	return nil, errors.New("could not marshal union type StableTestCheckUpdateRequest: all fields are null")
}
