// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: b268c8cca81d

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type Operation string

const (
	OperationIs             Operation = "is"
	OperationIsNot          Operation = "is_not"
	OperationGreaterThan    Operation = "greater_than"
	OperationGreaterOrEqual Operation = "greater_or_equal"
	OperationLessThan       Operation = "less_than"
	OperationLessOrEqual    Operation = "less_or_equal"
	OperationContains       Operation = "contains"
	OperationNotContains    Operation = "not_contains"
	OperationStartsWith     Operation = "starts_with"
	OperationEndsWith       Operation = "ends_with"
	OperationIsEmpty        Operation = "is_empty"
	OperationIsNotEmpty     Operation = "is_not_empty"
)

func (e Operation) ToPointer() *Operation {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *Operation) IsExact() bool {
	if e != nil {
		switch *e {
		case "is", "is_not", "greater_than", "greater_or_equal", "less_than", "less_or_equal", "contains", "not_contains", "starts_with", "ends_with", "is_empty", "is_not_empty":
			return true
		}
	}
	return false
}

type StableConditionAssertion struct {
	Key string                `json:"key"`
	LHS ConditionAssertionLHS `json:"lhs"`
	// Plain text; markdown is not interpreted. {variable_name} inserts a variable or entity, {variable_name.path} a field of a variable. Escape a literal { or \ with a backslash. A name matching neither is stored as literal text and reported in unresolvedReferences; secrets are not available here.
	RHS       string     `json:"rhs"`
	Operation *Operation `default:"is" json:"operation"`
}

func (s StableConditionAssertion) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableConditionAssertion) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableConditionAssertion) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *StableConditionAssertion) GetLHS() ConditionAssertionLHS {
	if s == nil {
		return ConditionAssertionLHS{}
	}
	return s.LHS
}

func (s *StableConditionAssertion) GetRHS() string {
	if s == nil {
		return ""
	}
	return s.RHS
}

func (s *StableConditionAssertion) GetOperation() *Operation {
	if s == nil {
		return nil
	}
	return s.Operation
}
