// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StableWorkspaceListResponse struct {
	Workspaces []StableWorkspace `json:"workspaces"`
}

func (s *StableWorkspaceListResponse) GetWorkspaces() []StableWorkspace {
	if s == nil {
		return []StableWorkspace{}
	}
	return s.Workspaces
}
