// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4f50558d8384

package components

type StableTestCheckListResponse struct {
	Checks []StableTestCheck `json:"checks"`
}

func (s *StableTestCheckListResponse) GetChecks() []StableTestCheck {
	if s == nil {
		return []StableTestCheck{}
	}
	return s.Checks
}
