// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c02790e6d00b

package components

type StableAnalyticsQueryOrganizationTokenUsageResponseRow struct {
	Model string  `json:"model"`
	Count float64 `json:"count"`
}

func (s *StableAnalyticsQueryOrganizationTokenUsageResponseRow) GetModel() string {
	if s == nil {
		return ""
	}
	return s.Model
}

func (s *StableAnalyticsQueryOrganizationTokenUsageResponseRow) GetCount() float64 {
	if s == nil {
		return 0.0
	}
	return s.Count
}

type StableAnalyticsQueryOrganizationTokenUsageResponse struct {
	Rows []StableAnalyticsQueryOrganizationTokenUsageResponseRow `json:"rows"`
}

func (s *StableAnalyticsQueryOrganizationTokenUsageResponse) GetRows() []StableAnalyticsQueryOrganizationTokenUsageResponseRow {
	if s == nil {
		return []StableAnalyticsQueryOrganizationTokenUsageResponseRow{}
	}
	return s.Rows
}
