// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type StableFunctionVariableResponse struct {
	Variable StableFunctionVariable `json:"variable"`
}

func (s *StableFunctionVariableResponse) GetVariable() StableFunctionVariable {
	if s == nil {
		return StableFunctionVariable{}
	}
	return s.Variable
}
