// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/optionalnullable"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// StableEvaluationTypeOption - Identifies an evaluation that selects one of a predefined set of options.
type StableEvaluationTypeOption string

const (
	StableEvaluationTypeOptionOption StableEvaluationTypeOption = "option"
)

func (e StableEvaluationTypeOption) ToPointer() *StableEvaluationTypeOption {
	return &e
}
func (e *StableEvaluationTypeOption) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "option":
		*e = StableEvaluationTypeOption(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableEvaluationTypeOption: %v", v)
	}
}

type StableEvaluationOption1 struct {
	// The value assigned to the evaluation result when this option is selected.
	Value string `json:"value"`
	// The criteria describing when the evaluator should select this option.
	Prompt string `json:"prompt"`
	// Whether this option is available for the evaluator to select.
	Included bool `json:"included"`
	// The color used to display this option in the Voiceflow UI.
	Color string `json:"color"`
}

func (s StableEvaluationOption1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationOption1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationOption1) GetValue() string {
	if s == nil {
		return ""
	}
	return s.Value
}

func (s *StableEvaluationOption1) GetPrompt() string {
	if s == nil {
		return ""
	}
	return s.Prompt
}

func (s *StableEvaluationOption1) GetIncluded() bool {
	if s == nil {
		return false
	}
	return s.Included
}

func (s *StableEvaluationOption1) GetColor() string {
	if s == nil {
		return ""
	}
	return s.Color
}

// #region class-body-stableevaluationoption1
// #endregion class-body-stableevaluationoption1

type StableEvaluationRealtime4 struct {
	Voice     *string `json:"voice,omitzero"`
	Eagerness *string `json:"eagerness,omitzero"`
}

func (s StableEvaluationRealtime4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationRealtime4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationRealtime4) GetVoice() *string {
	if s == nil {
		return nil
	}
	return s.Voice
}

func (s *StableEvaluationRealtime4) GetEagerness() *string {
	if s == nil {
		return nil
	}
	return s.Eagerness
}

// #region class-body-stableevaluationrealtime4
// #endregion class-body-stableevaluationrealtime4

type StableEvaluationReasoningEffort4 string

const (
	StableEvaluationReasoningEffort4Minimal StableEvaluationReasoningEffort4 = "minimal"
	StableEvaluationReasoningEffort4Low     StableEvaluationReasoningEffort4 = "low"
	StableEvaluationReasoningEffort4Medium  StableEvaluationReasoningEffort4 = "medium"
	StableEvaluationReasoningEffort4High    StableEvaluationReasoningEffort4 = "high"
)

func (e StableEvaluationReasoningEffort4) ToPointer() *StableEvaluationReasoningEffort4 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StableEvaluationReasoningEffort4) IsExact() bool {
	if e != nil {
		switch *e {
		case "minimal", "low", "medium", "high":
			return true
		}
	}
	return false
}

type StableEvaluationSettings4 struct {
	Model           *AIModel                                                            `json:"model,omitzero"`
	Realtime        *StableEvaluationRealtime4                                          `json:"realtime,omitzero"`
	MaxTokens       *float64                                                            `json:"maxTokens,omitzero"`
	Temperature     *float64                                                            `json:"temperature,omitzero"`
	ReasoningEffort optionalnullable.OptionalNullable[StableEvaluationReasoningEffort4] `json:"reasoningEffort,omitzero"`
}

func (s StableEvaluationSettings4) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationSettings4) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationSettings4) GetModel() *AIModel {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableEvaluationSettings4) GetRealtime() *StableEvaluationRealtime4 {
	if s == nil {
		return nil
	}
	return s.Realtime
}

func (s *StableEvaluationSettings4) GetMaxTokens() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxTokens
}

func (s *StableEvaluationSettings4) GetTemperature() *float64 {
	if s == nil {
		return nil
	}
	return s.Temperature
}

func (s *StableEvaluationSettings4) GetReasoningEffort() optionalnullable.OptionalNullable[StableEvaluationReasoningEffort4] {
	if s == nil {
		return nil
	}
	return s.ReasoningEffort
}

// #region class-body-stableevaluationsettings4
// #endregion class-body-stableevaluationsettings4

type StableEvaluationOption2 struct {
	// Identifies an evaluation that selects one of a predefined set of options.
	Type    StableEvaluationTypeOption `json:"type"`
	Options []StableEvaluationOption1  `json:"options"`
	ID      string                     `json:"id"`
	Name    string                     `json:"name"`
	// The criteria the evaluator uses to judge a transcript.
	Prompt string `json:"prompt"`
	// Whether this is a built-in default evaluation.
	Default bool `json:"default"`
	// Whether this evaluation runs automatically against new transcripts.
	Enabled bool `json:"enabled"`
	// The ID of the project this evaluation belongs to.
	ProjectID string                     `json:"projectID"`
	Settings  *StableEvaluationSettings4 `json:"settings"`
	// The average LLM cost incurred each time this evaluation runs.
	AverageCost *float64 `json:"averageCost"`
	// A human-readable description of what this evaluation measures.
	Description *string `json:"description"`
}

func (s StableEvaluationOption2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationOption2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationOption2) GetType() StableEvaluationTypeOption {
	if s == nil {
		return StableEvaluationTypeOption("")
	}
	return s.Type
}

func (s *StableEvaluationOption2) GetOptions() []StableEvaluationOption1 {
	if s == nil {
		return []StableEvaluationOption1{}
	}
	return s.Options
}

func (s *StableEvaluationOption2) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StableEvaluationOption2) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableEvaluationOption2) GetPrompt() string {
	if s == nil {
		return ""
	}
	return s.Prompt
}

func (s *StableEvaluationOption2) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}

func (s *StableEvaluationOption2) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StableEvaluationOption2) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableEvaluationOption2) GetSettings() *StableEvaluationSettings4 {
	if s == nil {
		return nil
	}
	return s.Settings
}

func (s *StableEvaluationOption2) GetAverageCost() *float64 {
	if s == nil {
		return nil
	}
	return s.AverageCost
}

func (s *StableEvaluationOption2) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

// #region class-body-stableevaluationoption2
// #endregion class-body-stableevaluationoption2

// StableEvaluationTypeString - Identifies an evaluation that produces a free-form text result.
type StableEvaluationTypeString string

const (
	StableEvaluationTypeStringString StableEvaluationTypeString = "string"
)

func (e StableEvaluationTypeString) ToPointer() *StableEvaluationTypeString {
	return &e
}
func (e *StableEvaluationTypeString) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "string":
		*e = StableEvaluationTypeString(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableEvaluationTypeString: %v", v)
	}
}

type StableEvaluationRealtime3 struct {
	Voice     *string `json:"voice,omitzero"`
	Eagerness *string `json:"eagerness,omitzero"`
}

func (s StableEvaluationRealtime3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationRealtime3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationRealtime3) GetVoice() *string {
	if s == nil {
		return nil
	}
	return s.Voice
}

func (s *StableEvaluationRealtime3) GetEagerness() *string {
	if s == nil {
		return nil
	}
	return s.Eagerness
}

// #region class-body-stableevaluationrealtime3
// #endregion class-body-stableevaluationrealtime3

type StableEvaluationReasoningEffort3 string

const (
	StableEvaluationReasoningEffort3Minimal StableEvaluationReasoningEffort3 = "minimal"
	StableEvaluationReasoningEffort3Low     StableEvaluationReasoningEffort3 = "low"
	StableEvaluationReasoningEffort3Medium  StableEvaluationReasoningEffort3 = "medium"
	StableEvaluationReasoningEffort3High    StableEvaluationReasoningEffort3 = "high"
)

func (e StableEvaluationReasoningEffort3) ToPointer() *StableEvaluationReasoningEffort3 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StableEvaluationReasoningEffort3) IsExact() bool {
	if e != nil {
		switch *e {
		case "minimal", "low", "medium", "high":
			return true
		}
	}
	return false
}

type StableEvaluationSettings3 struct {
	Model           *AIModel                                                            `json:"model,omitzero"`
	Realtime        *StableEvaluationRealtime3                                          `json:"realtime,omitzero"`
	MaxTokens       *float64                                                            `json:"maxTokens,omitzero"`
	Temperature     *float64                                                            `json:"temperature,omitzero"`
	ReasoningEffort optionalnullable.OptionalNullable[StableEvaluationReasoningEffort3] `json:"reasoningEffort,omitzero"`
}

func (s StableEvaluationSettings3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationSettings3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationSettings3) GetModel() *AIModel {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableEvaluationSettings3) GetRealtime() *StableEvaluationRealtime3 {
	if s == nil {
		return nil
	}
	return s.Realtime
}

func (s *StableEvaluationSettings3) GetMaxTokens() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxTokens
}

func (s *StableEvaluationSettings3) GetTemperature() *float64 {
	if s == nil {
		return nil
	}
	return s.Temperature
}

func (s *StableEvaluationSettings3) GetReasoningEffort() optionalnullable.OptionalNullable[StableEvaluationReasoningEffort3] {
	if s == nil {
		return nil
	}
	return s.ReasoningEffort
}

// #region class-body-stableevaluationsettings3
// #endregion class-body-stableevaluationsettings3

type StableEvaluationString struct {
	// Identifies an evaluation that produces a free-form text result.
	Type StableEvaluationTypeString `json:"type"`
	ID   string                     `json:"id"`
	Name string                     `json:"name"`
	// The criteria the evaluator uses to judge a transcript.
	Prompt string `json:"prompt"`
	// Whether this is a built-in default evaluation.
	Default bool `json:"default"`
	// Whether this evaluation runs automatically against new transcripts.
	Enabled bool `json:"enabled"`
	// The ID of the project this evaluation belongs to.
	ProjectID string                     `json:"projectID"`
	Settings  *StableEvaluationSettings3 `json:"settings"`
	// The average LLM cost incurred each time this evaluation runs.
	AverageCost *float64 `json:"averageCost"`
	// A human-readable description of what this evaluation measures.
	Description *string `json:"description"`
}

func (s StableEvaluationString) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationString) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationString) GetType() StableEvaluationTypeString {
	if s == nil {
		return StableEvaluationTypeString("")
	}
	return s.Type
}

func (s *StableEvaluationString) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StableEvaluationString) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableEvaluationString) GetPrompt() string {
	if s == nil {
		return ""
	}
	return s.Prompt
}

func (s *StableEvaluationString) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}

func (s *StableEvaluationString) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StableEvaluationString) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableEvaluationString) GetSettings() *StableEvaluationSettings3 {
	if s == nil {
		return nil
	}
	return s.Settings
}

func (s *StableEvaluationString) GetAverageCost() *float64 {
	if s == nil {
		return nil
	}
	return s.AverageCost
}

func (s *StableEvaluationString) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

// StableEvaluationTypeNumber - Identifies an evaluation that produces a numeric score.
type StableEvaluationTypeNumber string

const (
	StableEvaluationTypeNumberNumber StableEvaluationTypeNumber = "number"
)

func (e StableEvaluationTypeNumber) ToPointer() *StableEvaluationTypeNumber {
	return &e
}
func (e *StableEvaluationTypeNumber) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "number":
		*e = StableEvaluationTypeNumber(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableEvaluationTypeNumber: %v", v)
	}
}

type StableEvaluationRealtime2 struct {
	Voice     *string `json:"voice,omitzero"`
	Eagerness *string `json:"eagerness,omitzero"`
}

func (s StableEvaluationRealtime2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationRealtime2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationRealtime2) GetVoice() *string {
	if s == nil {
		return nil
	}
	return s.Voice
}

func (s *StableEvaluationRealtime2) GetEagerness() *string {
	if s == nil {
		return nil
	}
	return s.Eagerness
}

// #region class-body-stableevaluationrealtime2
// #endregion class-body-stableevaluationrealtime2

type StableEvaluationReasoningEffort2 string

const (
	StableEvaluationReasoningEffort2Minimal StableEvaluationReasoningEffort2 = "minimal"
	StableEvaluationReasoningEffort2Low     StableEvaluationReasoningEffort2 = "low"
	StableEvaluationReasoningEffort2Medium  StableEvaluationReasoningEffort2 = "medium"
	StableEvaluationReasoningEffort2High    StableEvaluationReasoningEffort2 = "high"
)

func (e StableEvaluationReasoningEffort2) ToPointer() *StableEvaluationReasoningEffort2 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StableEvaluationReasoningEffort2) IsExact() bool {
	if e != nil {
		switch *e {
		case "minimal", "low", "medium", "high":
			return true
		}
	}
	return false
}

type StableEvaluationSettings2 struct {
	Model           *AIModel                                                            `json:"model,omitzero"`
	Realtime        *StableEvaluationRealtime2                                          `json:"realtime,omitzero"`
	MaxTokens       *float64                                                            `json:"maxTokens,omitzero"`
	Temperature     *float64                                                            `json:"temperature,omitzero"`
	ReasoningEffort optionalnullable.OptionalNullable[StableEvaluationReasoningEffort2] `json:"reasoningEffort,omitzero"`
}

func (s StableEvaluationSettings2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationSettings2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationSettings2) GetModel() *AIModel {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableEvaluationSettings2) GetRealtime() *StableEvaluationRealtime2 {
	if s == nil {
		return nil
	}
	return s.Realtime
}

func (s *StableEvaluationSettings2) GetMaxTokens() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxTokens
}

func (s *StableEvaluationSettings2) GetTemperature() *float64 {
	if s == nil {
		return nil
	}
	return s.Temperature
}

func (s *StableEvaluationSettings2) GetReasoningEffort() optionalnullable.OptionalNullable[StableEvaluationReasoningEffort2] {
	if s == nil {
		return nil
	}
	return s.ReasoningEffort
}

// #region class-body-stableevaluationsettings2
// #endregion class-body-stableevaluationsettings2

type StableEvaluationNumber struct {
	// Identifies an evaluation that produces a numeric score.
	Type StableEvaluationTypeNumber `json:"type"`
	// The lowest score the evaluator can assign.
	MinimumValue float64 `json:"minimumValue"`
	// The highest score the evaluator can assign.
	MaximumValue float64 `json:"maximumValue"`
	// The criteria describing what warrants the `minimumValue` score.
	MinimumPrompt string `json:"minimumPrompt"`
	// The criteria describing what warrants the `maximumValue` score.
	MaximumPrompt string `json:"maximumPrompt"`
	ID            string `json:"id"`
	Name          string `json:"name"`
	// The criteria the evaluator uses to judge a transcript.
	Prompt string `json:"prompt"`
	// Whether this is a built-in default evaluation.
	Default bool `json:"default"`
	// Whether this evaluation runs automatically against new transcripts.
	Enabled bool `json:"enabled"`
	// The ID of the project this evaluation belongs to.
	ProjectID string                     `json:"projectID"`
	Settings  *StableEvaluationSettings2 `json:"settings"`
	// The average LLM cost incurred each time this evaluation runs.
	AverageCost *float64 `json:"averageCost"`
	// A human-readable description of what this evaluation measures.
	Description *string `json:"description"`
}

func (s StableEvaluationNumber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationNumber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationNumber) GetType() StableEvaluationTypeNumber {
	if s == nil {
		return StableEvaluationTypeNumber("")
	}
	return s.Type
}

func (s *StableEvaluationNumber) GetMinimumValue() float64 {
	if s == nil {
		return 0.0
	}
	return s.MinimumValue
}

func (s *StableEvaluationNumber) GetMaximumValue() float64 {
	if s == nil {
		return 0.0
	}
	return s.MaximumValue
}

func (s *StableEvaluationNumber) GetMinimumPrompt() string {
	if s == nil {
		return ""
	}
	return s.MinimumPrompt
}

func (s *StableEvaluationNumber) GetMaximumPrompt() string {
	if s == nil {
		return ""
	}
	return s.MaximumPrompt
}

func (s *StableEvaluationNumber) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StableEvaluationNumber) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableEvaluationNumber) GetPrompt() string {
	if s == nil {
		return ""
	}
	return s.Prompt
}

func (s *StableEvaluationNumber) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}

func (s *StableEvaluationNumber) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StableEvaluationNumber) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableEvaluationNumber) GetSettings() *StableEvaluationSettings2 {
	if s == nil {
		return nil
	}
	return s.Settings
}

func (s *StableEvaluationNumber) GetAverageCost() *float64 {
	if s == nil {
		return nil
	}
	return s.AverageCost
}

func (s *StableEvaluationNumber) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

// StableEvaluationTypeBoolean - Identifies an evaluation that produces a true/false result.
type StableEvaluationTypeBoolean string

const (
	StableEvaluationTypeBooleanBoolean StableEvaluationTypeBoolean = "boolean"
)

func (e StableEvaluationTypeBoolean) ToPointer() *StableEvaluationTypeBoolean {
	return &e
}
func (e *StableEvaluationTypeBoolean) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "boolean":
		*e = StableEvaluationTypeBoolean(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableEvaluationTypeBoolean: %v", v)
	}
}

type StableEvaluationRealtime1 struct {
	Voice     *string `json:"voice,omitzero"`
	Eagerness *string `json:"eagerness,omitzero"`
}

func (s StableEvaluationRealtime1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationRealtime1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationRealtime1) GetVoice() *string {
	if s == nil {
		return nil
	}
	return s.Voice
}

func (s *StableEvaluationRealtime1) GetEagerness() *string {
	if s == nil {
		return nil
	}
	return s.Eagerness
}

// #region class-body-stableevaluationrealtime1
// #endregion class-body-stableevaluationrealtime1

type StableEvaluationReasoningEffort1 string

const (
	StableEvaluationReasoningEffort1Minimal StableEvaluationReasoningEffort1 = "minimal"
	StableEvaluationReasoningEffort1Low     StableEvaluationReasoningEffort1 = "low"
	StableEvaluationReasoningEffort1Medium  StableEvaluationReasoningEffort1 = "medium"
	StableEvaluationReasoningEffort1High    StableEvaluationReasoningEffort1 = "high"
)

func (e StableEvaluationReasoningEffort1) ToPointer() *StableEvaluationReasoningEffort1 {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *StableEvaluationReasoningEffort1) IsExact() bool {
	if e != nil {
		switch *e {
		case "minimal", "low", "medium", "high":
			return true
		}
	}
	return false
}

type StableEvaluationSettings1 struct {
	Model           *AIModel                                                            `json:"model,omitzero"`
	Realtime        *StableEvaluationRealtime1                                          `json:"realtime,omitzero"`
	MaxTokens       *float64                                                            `json:"maxTokens,omitzero"`
	Temperature     *float64                                                            `json:"temperature,omitzero"`
	ReasoningEffort optionalnullable.OptionalNullable[StableEvaluationReasoningEffort1] `json:"reasoningEffort,omitzero"`
}

func (s StableEvaluationSettings1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationSettings1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationSettings1) GetModel() *AIModel {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableEvaluationSettings1) GetRealtime() *StableEvaluationRealtime1 {
	if s == nil {
		return nil
	}
	return s.Realtime
}

func (s *StableEvaluationSettings1) GetMaxTokens() *float64 {
	if s == nil {
		return nil
	}
	return s.MaxTokens
}

func (s *StableEvaluationSettings1) GetTemperature() *float64 {
	if s == nil {
		return nil
	}
	return s.Temperature
}

func (s *StableEvaluationSettings1) GetReasoningEffort() optionalnullable.OptionalNullable[StableEvaluationReasoningEffort1] {
	if s == nil {
		return nil
	}
	return s.ReasoningEffort
}

// #region class-body-stableevaluationsettings1
// #endregion class-body-stableevaluationsettings1

type StableEvaluationBoolean struct {
	// Identifies an evaluation that produces a true/false result.
	Type StableEvaluationTypeBoolean `json:"type"`
	// The criteria describing when the evaluator should return `true`.
	TruePrompt string `json:"truePrompt"`
	// The criteria describing when the evaluator should return `false`.
	FalsePrompt string `json:"falsePrompt"`
	ID          string `json:"id"`
	Name        string `json:"name"`
	// The criteria the evaluator uses to judge a transcript.
	Prompt string `json:"prompt"`
	// Whether this is a built-in default evaluation.
	Default bool `json:"default"`
	// Whether this evaluation runs automatically against new transcripts.
	Enabled bool `json:"enabled"`
	// The ID of the project this evaluation belongs to.
	ProjectID string                     `json:"projectID"`
	Settings  *StableEvaluationSettings1 `json:"settings"`
	// The average LLM cost incurred each time this evaluation runs.
	AverageCost *float64 `json:"averageCost"`
	// A human-readable description of what this evaluation measures.
	Description *string `json:"description"`
}

func (s StableEvaluationBoolean) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableEvaluationBoolean) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableEvaluationBoolean) GetType() StableEvaluationTypeBoolean {
	if s == nil {
		return StableEvaluationTypeBoolean("")
	}
	return s.Type
}

func (s *StableEvaluationBoolean) GetTruePrompt() string {
	if s == nil {
		return ""
	}
	return s.TruePrompt
}

func (s *StableEvaluationBoolean) GetFalsePrompt() string {
	if s == nil {
		return ""
	}
	return s.FalsePrompt
}

func (s *StableEvaluationBoolean) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}

func (s *StableEvaluationBoolean) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableEvaluationBoolean) GetPrompt() string {
	if s == nil {
		return ""
	}
	return s.Prompt
}

func (s *StableEvaluationBoolean) GetDefault() bool {
	if s == nil {
		return false
	}
	return s.Default
}

func (s *StableEvaluationBoolean) GetEnabled() bool {
	if s == nil {
		return false
	}
	return s.Enabled
}

func (s *StableEvaluationBoolean) GetProjectID() string {
	if s == nil {
		return ""
	}
	return s.ProjectID
}

func (s *StableEvaluationBoolean) GetSettings() *StableEvaluationSettings1 {
	if s == nil {
		return nil
	}
	return s.Settings
}

func (s *StableEvaluationBoolean) GetAverageCost() *float64 {
	if s == nil {
		return nil
	}
	return s.AverageCost
}

func (s *StableEvaluationBoolean) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

type StableEvaluationType string

const (
	StableEvaluationTypeBooleanValue StableEvaluationType = "boolean"
	StableEvaluationTypeNumberValue  StableEvaluationType = "number"
	StableEvaluationTypeStringValue  StableEvaluationType = "string"
	StableEvaluationTypeOptionObj    StableEvaluationType = "option"
	StableEvaluationTypeUnknown      StableEvaluationType = "UNKNOWN"
)

type StableEvaluation struct {
	StableEvaluationBoolean *StableEvaluationBoolean `queryParam:"inline" union:"member"`
	StableEvaluationNumber  *StableEvaluationNumber  `queryParam:"inline" union:"member"`
	StableEvaluationString  *StableEvaluationString  `queryParam:"inline" union:"member"`
	StableEvaluationOption2 *StableEvaluationOption2 `queryParam:"inline" union:"member"`
	UnknownRaw              json.RawMessage          `json:"-" union:"unknown"`

	Type StableEvaluationType
}

func CreateStableEvaluationBoolean(boolean StableEvaluationBoolean) StableEvaluation {
	typ := StableEvaluationTypeBooleanValue

	typStr := StableEvaluationTypeBoolean(typ)
	boolean.Type = typStr

	return StableEvaluation{
		StableEvaluationBoolean: &boolean,
		Type:                    typ,
	}
}

func CreateStableEvaluationNumber(number StableEvaluationNumber) StableEvaluation {
	typ := StableEvaluationTypeNumberValue

	typStr := StableEvaluationTypeNumber(typ)
	number.Type = typStr

	return StableEvaluation{
		StableEvaluationNumber: &number,
		Type:                   typ,
	}
}

func CreateStableEvaluationString(stringT StableEvaluationString) StableEvaluation {
	typ := StableEvaluationTypeStringValue

	typStr := StableEvaluationTypeString(typ)
	stringT.Type = typStr

	return StableEvaluation{
		StableEvaluationString: &stringT,
		Type:                   typ,
	}
}

func CreateStableEvaluationOptionObj(optionT StableEvaluationOption2) StableEvaluation {
	typ := StableEvaluationTypeOptionObj

	typStr := StableEvaluationTypeOption(typ)
	optionT.Type = typStr

	return StableEvaluation{
		StableEvaluationOption2: &optionT,
		Type:                    typ,
	}
}

func CreateStableEvaluationUnknown(raw json.RawMessage) StableEvaluation {
	return StableEvaluation{
		UnknownRaw: raw,
		Type:       StableEvaluationTypeUnknown,
	}
}

func (u StableEvaluation) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u StableEvaluation) IsUnknown() bool {
	return u.Type == StableEvaluationTypeUnknown
}

func (u *StableEvaluation) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		Type string `json:"type"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StableEvaluationTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StableEvaluationTypeUnknown
		return nil
	}

	switch dis.Type {
	case "boolean":
		stableEvaluationBoolean := new(StableEvaluationBoolean)
		if err := utils.UnmarshalJSON(data, &stableEvaluationBoolean, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == boolean) type StableEvaluationBoolean within StableEvaluation: %w", string(data), err)
		}

		u.StableEvaluationBoolean = stableEvaluationBoolean
		u.Type = StableEvaluationTypeBooleanValue
		return nil
	case "number":
		stableEvaluationNumber := new(StableEvaluationNumber)
		if err := utils.UnmarshalJSON(data, &stableEvaluationNumber, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == number) type StableEvaluationNumber within StableEvaluation: %w", string(data), err)
		}

		u.StableEvaluationNumber = stableEvaluationNumber
		u.Type = StableEvaluationTypeNumberValue
		return nil
	case "string":
		stableEvaluationString := new(StableEvaluationString)
		if err := utils.UnmarshalJSON(data, &stableEvaluationString, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == string) type StableEvaluationString within StableEvaluation: %w", string(data), err)
		}

		u.StableEvaluationString = stableEvaluationString
		u.Type = StableEvaluationTypeStringValue
		return nil
	case "option":
		stableEvaluationOption2 := new(StableEvaluationOption2)
		if err := utils.UnmarshalJSON(data, &stableEvaluationOption2, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (Type == option) type StableEvaluationOption2 within StableEvaluation: %w", string(data), err)
		}

		u.StableEvaluationOption2 = stableEvaluationOption2
		u.Type = StableEvaluationTypeOptionObj
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = StableEvaluationTypeUnknown
		return nil
	}

}

func (u StableEvaluation) MarshalJSON() ([]byte, error) {
	if u.StableEvaluationBoolean != nil {
		return utils.MarshalJSON(u.StableEvaluationBoolean, "", true)
	}

	if u.StableEvaluationNumber != nil {
		return utils.MarshalJSON(u.StableEvaluationNumber, "", true)
	}

	if u.StableEvaluationString != nil {
		return utils.MarshalJSON(u.StableEvaluationString, "", true)
	}

	if u.StableEvaluationOption2 != nil {
		return utils.MarshalJSON(u.StableEvaluationOption2, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type StableEvaluation: all fields are null")
}
