// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 459bea50b1e5

package components

import (
	"encoding/json"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type StableDocumentCreateSitemapRequestMetadatum struct {
	// The name of the metadata field.
	Key string `json:"key"`
	// The values assigned to this metadata field.
	Values []string `json:"values"`
}

func (s *StableDocumentCreateSitemapRequestMetadatum) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *StableDocumentCreateSitemapRequestMetadatum) GetValues() []string {
	if s == nil {
		return []string{}
	}
	return s.Values
}

// StableDocumentCreateSitemapRequestRefreshRate - How often the URL is automatically re-crawled to refresh the document content.
type StableDocumentCreateSitemapRequestRefreshRate string

const (
	StableDocumentCreateSitemapRequestRefreshRateDaily   StableDocumentCreateSitemapRequestRefreshRate = "daily"
	StableDocumentCreateSitemapRequestRefreshRateWeekly  StableDocumentCreateSitemapRequestRefreshRate = "weekly"
	StableDocumentCreateSitemapRequestRefreshRateMonthly StableDocumentCreateSitemapRequestRefreshRate = "monthly"
	StableDocumentCreateSitemapRequestRefreshRateNever   StableDocumentCreateSitemapRequestRefreshRate = "never"
)

func (e StableDocumentCreateSitemapRequestRefreshRate) ToPointer() *StableDocumentCreateSitemapRequestRefreshRate {
	return &e
}
func (e *StableDocumentCreateSitemapRequestRefreshRate) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "daily":
		fallthrough
	case "weekly":
		fallthrough
	case "monthly":
		fallthrough
	case "never":
		*e = StableDocumentCreateSitemapRequestRefreshRate(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StableDocumentCreateSitemapRequestRefreshRate: %v", v)
	}
}

type StableDocumentCreateSitemapRequest struct {
	// The HTTPS URL of the sitemap to read. A bare site URL works too — when it does not end in `.xml`, `/sitemap.xml`, `/sitemap_index.xml` and `/sitemap/sitemap.xml` are probed in turn.
	SitemapURL string `json:"sitemapURL"`
	// Patterns that drop a URL from the import when any one of them matches. Matching is case-insensitive and unanchored: a pattern with no `*` matches any URL containing it as a substring (`/blog/`), while `*` matches any run of characters (`*/tag/*`, `*.pdf`).
	Exclude []string `json:"exclude,omitzero"`
	// Metadata tags attached to the document, used to filter knowledge base retrieval at runtime.
	Metadata []StableDocumentCreateSitemapRequestMetadatum `json:"metadata,omitzero"`
	// How often the URL is automatically re-crawled to refresh the document content.
	RefreshRate *StableDocumentCreateSitemapRequestRefreshRate `default:"never" json:"refreshRate"`
}

func (s StableDocumentCreateSitemapRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableDocumentCreateSitemapRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableDocumentCreateSitemapRequest) GetSitemapURL() string {
	if s == nil {
		return ""
	}
	return s.SitemapURL
}

func (s *StableDocumentCreateSitemapRequest) GetExclude() []string {
	if s == nil {
		return nil
	}
	return s.Exclude
}

func (s *StableDocumentCreateSitemapRequest) GetMetadata() []StableDocumentCreateSitemapRequestMetadatum {
	if s == nil {
		return nil
	}
	return s.Metadata
}

func (s *StableDocumentCreateSitemapRequest) GetRefreshRate() *StableDocumentCreateSitemapRequestRefreshRate {
	if s == nil {
		return nil
	}
	return s.RefreshRate
}
