// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

// Schema - Declares which top-level keys of each row are full-text searchable versus row-level metadata.
type Schema struct {
	// Per-row metadata, returned with results. NOT consulted by the default system tool's filter UI.
	MetadataFields []string `json:"metadataFields,omitzero"`
	// Full-text indexed; what semantic search matches against.
	SearchableFields []string `json:"searchableFields,omitzero"`
}

func (s Schema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Schema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Schema) GetMetadataFields() []string {
	if s == nil {
		return nil
	}
	return s.MetadataFields
}

func (s *Schema) GetSearchableFields() []string {
	if s == nil {
		return nil
	}
	return s.SearchableFields
}

type StableDocumentCreateTableRequestMetadatum struct {
	// The name of the metadata field.
	Key string `json:"key"`
	// The values assigned to this metadata field.
	Values []string `json:"values"`
}

func (s *StableDocumentCreateTableRequestMetadatum) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

func (s *StableDocumentCreateTableRequestMetadatum) GetValues() []string {
	if s == nil {
		return []string{}
	}
	return s.Values
}

type StableDocumentCreateTableRequest struct {
	// An optional source URL to associate with the table document.
	URL  *string `json:"url,omitzero"`
	Name string  `json:"name"`
	// The table rows to ingest; each row is a flat object and becomes its own chunk.
	Items []map[string]any `json:"items"`
	// Declares which top-level keys of each row are full-text searchable versus row-level metadata.
	Schema *Schema `json:"schema,omitzero"`
	// Properties that can be filtered on at runtime (static or dynamic from a variable). Put your most common filter dimensions here.
	Metadata []StableDocumentCreateTableRequestMetadatum `json:"metadata,omitzero"`
}

func (s StableDocumentCreateTableRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *StableDocumentCreateTableRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *StableDocumentCreateTableRequest) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

func (s *StableDocumentCreateTableRequest) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StableDocumentCreateTableRequest) GetItems() []map[string]any {
	if s == nil {
		return []map[string]any{}
	}
	return s.Items
}

func (s *StableDocumentCreateTableRequest) GetSchema() *Schema {
	if s == nil {
		return nil
	}
	return s.Schema
}

func (s *StableDocumentCreateTableRequest) GetMetadata() []StableDocumentCreateTableRequestMetadatum {
	if s == nil {
		return nil
	}
	return s.Metadata
}
