// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7c06b3619589

package components

type StableAnalyticsQueryProjectTokenUsageResponseRow struct {
	Model             *string `json:"model"`
	Count             float64 `json:"count"`
	IntervalStartDate string  `json:"intervalStartDate"`
}

func (s *StableAnalyticsQueryProjectTokenUsageResponseRow) GetModel() *string {
	if s == nil {
		return nil
	}
	return s.Model
}

func (s *StableAnalyticsQueryProjectTokenUsageResponseRow) GetCount() float64 {
	if s == nil {
		return 0.0
	}
	return s.Count
}

func (s *StableAnalyticsQueryProjectTokenUsageResponseRow) GetIntervalStartDate() string {
	if s == nil {
		return ""
	}
	return s.IntervalStartDate
}

type StableAnalyticsQueryProjectTokenUsageResponse struct {
	Rows []StableAnalyticsQueryProjectTokenUsageResponseRow `json:"rows"`
}

func (s *StableAnalyticsQueryProjectTokenUsageResponse) GetRows() []StableAnalyticsQueryProjectTokenUsageResponseRow {
	if s == nil {
		return []StableAnalyticsQueryProjectTokenUsageResponseRow{}
	}
	return s.Rows
}
