// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 60f52fa75b2a

package components

type StableTestTurnResponse struct {
	Turn StableTestTurn `json:"turn"`
}

func (s *StableTestTurnResponse) GetTurn() StableTestTurn {
	if s == nil {
		return StableTestTurn{}
	}
	return s.Turn
}

func (s *StableTestTurnResponse) GetTurnUser() *StableTestTurnUser {
	return s.GetTurn().StableTestTurnUser
}

func (s *StableTestTurnResponse) GetTurnAgent() *StableTestTurnAgent {
	return s.GetTurn().StableTestTurnAgent
}

func (s *StableTestTurnResponse) GetTurnSimulation() *StableTestTurnSimulation {
	return s.GetTurn().StableTestTurnSimulation
}
