// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d3014fc64d73

package components

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/voiceflow/cli/internal/sdk/sdkinternal/utils"
)

type ToolCallTraceType string

const (
	ToolCallTraceTypeToolCall ToolCallTraceType = "tool-call"
)

func (e ToolCallTraceType) ToPointer() *ToolCallTraceType {
	return &e
}
func (e *ToolCallTraceType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "tool-call":
		*e = ToolCallTraceType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ToolCallTraceType: %v", v)
	}
}

type ToolCallTraceStateEnd string

const (
	ToolCallTraceStateEndEnd ToolCallTraceStateEnd = "end"
)

func (e ToolCallTraceStateEnd) ToPointer() *ToolCallTraceStateEnd {
	return &e
}
func (e *ToolCallTraceStateEnd) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "end":
		*e = ToolCallTraceStateEnd(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ToolCallTraceStateEnd: %v", v)
	}
}

type ToolCallTracePayloadEnd struct {
	State  ToolCallTraceStateEnd `json:"state"`
	CallID string                `json:"callID"`
}

func (t ToolCallTracePayloadEnd) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolCallTracePayloadEnd) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolCallTracePayloadEnd) GetState() ToolCallTraceStateEnd {
	if t == nil {
		return ToolCallTraceStateEnd("")
	}
	return t.State
}

func (t *ToolCallTracePayloadEnd) GetCallID() string {
	if t == nil {
		return ""
	}
	return t.CallID
}

type Sound struct {
	Ref    string   `json:"ref"`
	Volume *float64 `json:"volume,omitzero"`
}

func (s Sound) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *Sound) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *Sound) GetRef() string {
	if s == nil {
		return ""
	}
	return s.Ref
}

func (s *Sound) GetVolume() *float64 {
	if s == nil {
		return nil
	}
	return s.Volume
}

type ToolCallTraceStateStart string

const (
	ToolCallTraceStateStartStart ToolCallTraceStateStart = "start"
)

func (e ToolCallTraceStateStart) ToPointer() *ToolCallTraceStateStart {
	return &e
}
func (e *ToolCallTraceStateStart) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "start":
		*e = ToolCallTraceStateStart(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ToolCallTraceStateStart: %v", v)
	}
}

type ToolCallTracePayloadStart struct {
	CallID string                  `json:"callID"`
	Sound  *Sound                  `json:"sound,omitzero"`
	State  ToolCallTraceStateStart `json:"state"`
}

func (t ToolCallTracePayloadStart) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolCallTracePayloadStart) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolCallTracePayloadStart) GetCallID() string {
	if t == nil {
		return ""
	}
	return t.CallID
}

func (t *ToolCallTracePayloadStart) GetSound() *Sound {
	if t == nil {
		return nil
	}
	return t.Sound
}

func (t *ToolCallTracePayloadStart) GetState() ToolCallTraceStateStart {
	if t == nil {
		return ToolCallTraceStateStart("")
	}
	return t.State
}

type ToolCallTracePayloadUnionType string

const (
	ToolCallTracePayloadUnionTypeStart   ToolCallTracePayloadUnionType = "start"
	ToolCallTracePayloadUnionTypeEnd     ToolCallTracePayloadUnionType = "end"
	ToolCallTracePayloadUnionTypeUnknown ToolCallTracePayloadUnionType = "UNKNOWN"
)

type ToolCallTracePayloadUnion struct {
	ToolCallTracePayloadStart *ToolCallTracePayloadStart `queryParam:"inline" union:"member"`
	ToolCallTracePayloadEnd   *ToolCallTracePayloadEnd   `queryParam:"inline" union:"member"`
	UnknownRaw                json.RawMessage            `json:"-" union:"unknown"`

	Type ToolCallTracePayloadUnionType
}

func CreateToolCallTracePayloadUnionStart(start ToolCallTracePayloadStart) ToolCallTracePayloadUnion {
	typ := ToolCallTracePayloadUnionTypeStart

	typStr := ToolCallTraceStateStart(typ)
	start.State = typStr

	return ToolCallTracePayloadUnion{
		ToolCallTracePayloadStart: &start,
		Type:                      typ,
	}
}

func CreateToolCallTracePayloadUnionEnd(end ToolCallTracePayloadEnd) ToolCallTracePayloadUnion {
	typ := ToolCallTracePayloadUnionTypeEnd

	typStr := ToolCallTraceStateEnd(typ)
	end.State = typStr

	return ToolCallTracePayloadUnion{
		ToolCallTracePayloadEnd: &end,
		Type:                    typ,
	}
}

func CreateToolCallTracePayloadUnionUnknown(raw json.RawMessage) ToolCallTracePayloadUnion {
	return ToolCallTracePayloadUnion{
		UnknownRaw: raw,
		Type:       ToolCallTracePayloadUnionTypeUnknown,
	}
}

func (u ToolCallTracePayloadUnion) GetUnknownRaw() json.RawMessage {
	return u.UnknownRaw
}

func (u ToolCallTracePayloadUnion) IsUnknown() bool {
	return u.Type == ToolCallTracePayloadUnionTypeUnknown
}

func (u *ToolCallTracePayloadUnion) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		State string `json:"state"`
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolCallTracePayloadUnionTypeUnknown
		return nil
	}
	if dis == nil {
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolCallTracePayloadUnionTypeUnknown
		return nil
	}

	switch dis.State {
	case "start":
		toolCallTracePayloadStart := new(ToolCallTracePayloadStart)
		if err := utils.UnmarshalJSON(data, &toolCallTracePayloadStart, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == start) type ToolCallTracePayloadStart within ToolCallTracePayloadUnion: %w", string(data), err)
		}

		u.ToolCallTracePayloadStart = toolCallTracePayloadStart
		u.Type = ToolCallTracePayloadUnionTypeStart
		return nil
	case "end":
		toolCallTracePayloadEnd := new(ToolCallTracePayloadEnd)
		if err := utils.UnmarshalJSON(data, &toolCallTracePayloadEnd, "", true, nil); err != nil {
			return fmt.Errorf("could not unmarshal `%s` into expected (State == end) type ToolCallTracePayloadEnd within ToolCallTracePayloadUnion: %w", string(data), err)
		}

		u.ToolCallTracePayloadEnd = toolCallTracePayloadEnd
		u.Type = ToolCallTracePayloadUnionTypeEnd
		return nil
	default:
		u.UnknownRaw = json.RawMessage(data)
		u.Type = ToolCallTracePayloadUnionTypeUnknown
		return nil
	}

}

func (u ToolCallTracePayloadUnion) MarshalJSON() ([]byte, error) {
	if u.ToolCallTracePayloadStart != nil {
		return utils.MarshalJSON(u.ToolCallTracePayloadStart, "", true)
	}

	if u.ToolCallTracePayloadEnd != nil {
		return utils.MarshalJSON(u.ToolCallTracePayloadEnd, "", true)
	}

	if u.UnknownRaw != nil {
		return json.RawMessage(u.UnknownRaw), nil
	}
	return nil, errors.New("could not marshal union type ToolCallTracePayloadUnion: all fields are null")
}

type ToolCallTrace struct {
	Type        ToolCallTraceType         `json:"type"`
	Paths       []TracePath               `json:"paths,omitzero"`
	DefaultPath *float64                  `json:"defaultPath,omitzero"`
	Time        *float64                  `json:"time,omitzero"`
	TurnID      *string                   `json:"turnID,omitzero"`
	HandleID    *string                   `json:"handleID,omitzero"`
	Payload     ToolCallTracePayloadUnion `json:"payload"`
}

func (t ToolCallTrace) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *ToolCallTrace) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *ToolCallTrace) GetType() ToolCallTraceType {
	if t == nil {
		return ToolCallTraceType("")
	}
	return t.Type
}

func (t *ToolCallTrace) GetPaths() []TracePath {
	if t == nil {
		return nil
	}
	return t.Paths
}

func (t *ToolCallTrace) GetDefaultPath() *float64 {
	if t == nil {
		return nil
	}
	return t.DefaultPath
}

func (t *ToolCallTrace) GetTime() *float64 {
	if t == nil {
		return nil
	}
	return t.Time
}

func (t *ToolCallTrace) GetTurnID() *string {
	if t == nil {
		return nil
	}
	return t.TurnID
}

func (t *ToolCallTrace) GetHandleID() *string {
	if t == nil {
		return nil
	}
	return t.HandleID
}

func (t *ToolCallTrace) GetPayload() ToolCallTracePayloadUnion {
	if t == nil {
		return ToolCallTracePayloadUnion{}
	}
	return t.Payload
}

func (t *ToolCallTrace) GetPayloadStart() *ToolCallTracePayloadStart {
	return t.GetPayload().ToolCallTracePayloadStart
}

func (t *ToolCallTrace) GetPayloadEnd() *ToolCallTracePayloadEnd {
	return t.GetPayload().ToolCallTracePayloadEnd
}
