// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 3fa8c5620067

package components

type WidgetSettingsChatDisclaimer struct {
	Enabled             bool   `json:"enabled"`
	Title               string `json:"title"`
	Description         string `json:"description"`
	PrimaryButtonText   string `json:"primaryButtonText"`
	SecondaryButtonText string `json:"secondaryButtonText"`
	SecondaryButtonURL  string `json:"secondaryButtonURL"`
}

func (w *WidgetSettingsChatDisclaimer) GetEnabled() bool {
	if w == nil {
		return false
	}
	return w.Enabled
}

func (w *WidgetSettingsChatDisclaimer) GetTitle() string {
	if w == nil {
		return ""
	}
	return w.Title
}

func (w *WidgetSettingsChatDisclaimer) GetDescription() string {
	if w == nil {
		return ""
	}
	return w.Description
}

func (w *WidgetSettingsChatDisclaimer) GetPrimaryButtonText() string {
	if w == nil {
		return ""
	}
	return w.PrimaryButtonText
}

func (w *WidgetSettingsChatDisclaimer) GetSecondaryButtonText() string {
	if w == nil {
		return ""
	}
	return w.SecondaryButtonText
}

func (w *WidgetSettingsChatDisclaimer) GetSecondaryButtonURL() string {
	if w == nil {
		return ""
	}
	return w.SecondaryButtonURL
}
