// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9567f96d12bd

package components

type WidgetSettingsWidgetPosition string

const (
	WidgetSettingsWidgetPositionRight WidgetSettingsWidgetPosition = "right"
	WidgetSettingsWidgetPositionLeft  WidgetSettingsWidgetPosition = "left"
)

func (e WidgetSettingsWidgetPosition) ToPointer() *WidgetSettingsWidgetPosition {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *WidgetSettingsWidgetPosition) IsExact() bool {
	if e != nil {
		switch *e {
		case "right", "left":
			return true
		}
	}
	return false
}
